#!/usr/bin/env python3
"""
Writes src/Koral/Generated/Enums.g.cs from the C++ headers: every enumeration the C# API shares with
C++, with the same names (the `e` prefix included) and the same values, so a value crosses the C
interface as itself. Run it after changing one of them; `--check` (a ctest) fails when the file is stale.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "Koral" / "Generated" / "Enums.g.cs"

# (header, the class the C++ enumeration is inside or None, its name, the C# type it goes in or None, C# kind)
ENUMS = [
    ("buffer.h", "Buffer", "Usage", "Buffer", "class"),
    ("buffer.h", "Buffer", "Type", "Buffer", "class"),
    ("image.h", "Image", "Type", "Image", "class"),
    ("image.h", "Image", "Format", "Image", "class"),
    ("image.h", "Image", "Usage", "Image", "class"),
    ("image.h", "Image", "ViewCoverage", "Image", "class"),
    ("imageView.h", "ImageView", "Type", "ImageView", "class"),
    ("imageView.h", "ImageView", "Swizzle", "ImageView", "class"),
    ("sampler.h", "Sampler", "MipmapMode", "Sampler", "class"),
    ("sampler.h", "Sampler", "AddressMode", "Sampler", "class"),
    ("shader.h", "Shader", "Stage", "Shader", "class"),
    ("shader.h", "Shader", "Lang", "Shader", "class"),
    ("shader.h", "Shader", "AccessKind", "Shader", "class"),
    ("accelerationStructure.h", "AccelerationStructure", "Type", "AccelerationStructure", "class"),
    ("commandBuffer.h", "CommandBuffer", "Usage", "CommandBuffer", "class"),
    ("window.h", "Window", "Format", "Window", "class"),
    ("input.h", "Input", "CursorMode", "Input", "class"),
    ("input.h", "InputSource", "Kind", "InputSource", "struct"),
    ("log.h", None, "Level", "Log", "static class"),
] + [("structs.h", None, name, None, None) for name in [
    "ChannelType", "ResourceAccess", "ImageShape", "DescriptorType", "Topology", "PolygonMode", "CullMode", "FrontFace",
    "SampleCount", "CompareOp", "StencilOp", "BlendFactor", "LogicOp", "BlendOp", "ColorComponent", "ResolveMode",
    "Filter", "LoadOperation", "StoreOperation", "StencilFace", "DynamicState",
]] + [
    ("error.h", None, "ErrorCode", None, None),
    ("input.h", None, "Key", None, None),
    ("input.h", None, "MouseButton", None, None),
    ("input.h", None, "GamepadButton", None, None),
    ("input.h", None, "GamepadAxis", None, None),
    ("input.h", None, "KeyState", None, None),
    ("input.h", None, "SpecialKey", None, None),
    ("context.h", None, "API", None, None),
    ("context.h", None, "WindowPlatform", None, None),
    ("shaderValue.h", None, "ValueScalar", None, None),
]

TYPES = {"std::uint8_t": "byte", "std::uint16_t": "ushort", "std::uint32_t": "uint", "std::int32_t": "int", None: "int"}


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse(header, owner, name):
    text = strip_comments((ROOT / "include" / header).read_text())
    start = 0
    if owner:
        anchor = re.search(r"\b(class|struct)\s+(KORAL_API\s+)?" + owner + r"\b[^;]*?\{", text)
        if not anchor:
            raise SystemExit(f"{header}: no {owner}")
        start = anchor.end()
    match = re.compile(r"enum\s+class\s+" + name + r"\s*(?::\s*([\w:]+))?\s*\{(.*?)\}", re.S).search(text, start)
    if not match:
        raise SystemExit(f"{header}: no enum class {name}")
    underlying, body = match.group(1), match.group(2)
    values, entries, nxt = {}, [], 0
    for item in [i.strip() for i in body.split(",") if i.strip()]:
        if "=" in item:
            key, expr = [p.strip() for p in item.split("=", 1)]
            value = eval(re.sub(r"\b(e\w+)\b", lambda m: str(values[m.group(1)]), expr))
            alias = expr if re.fullmatch(r"e\w+", expr) else None
        else:
            key, value, alias = item, nxt, None
        values[key] = value
        entries.append((key, value, alias))
        nxt = value + 1
    flags = re.search(r"enable_flags<\s*(\w+::)?" + (owner + "::" if owner else "") + name + r"\s*>", strip_comments(
        "".join(p.read_text() for p in (ROOT / "include").glob("*.h"))))
    return TYPES.get(underlying, "int"), entries, bool(flags)


def emit_enum(name, underlying, entries, flags, indent):
    pad = " " * indent
    lines = []
    if flags:
        lines.append(f"{pad}[Flags]")
    lines.append(f"{pad}public enum {name} : {underlying}")
    lines.append(pad + "{")
    for key, value, alias in entries:
        lines.append(f"{pad}    {key} = {alias if alias else value},")
    lines.append(pad + "}")
    return lines


def generate():
    out = ["// <auto-generated> by tools/generate_enums.py from the C++ headers: do not edit. </auto-generated>",
           "#nullable enable", "#pragma warning disable CS1591", "", "namespace Koral;", ""]
    nested = {}
    for header, owner, name, target, kind in ENUMS:
        underlying, entries, flags = parse(header, owner, name)
        if target:
            nested.setdefault((target, kind), []).append((name, underlying, entries, flags))
        else:
            out += [f"/// <summary>kor::{name}.</summary>"] + emit_enum(name, underlying, entries, flags, 0) + [""]
    for (target, kind), enums in nested.items():
        out.append(f"public {'readonly partial struct' if kind == 'struct' else 'static partial class' if kind == 'static class' else 'sealed partial class'} {target}")
        out.append("{")
        for i, (name, underlying, entries, flags) in enumerate(enums):
            if i:
                out.append("")
            out.append(f"    /// <summary>kor::{target}::{name}.</summary>")
            out += emit_enum(name, underlying, entries, flags, 4)
        out += ["}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    text = generate()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is stale: run {pathlib.Path(__file__).name}")
            sys.exit(1)
        print("up to date")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"wrote {OUT}")
