// <auto-generated> by tools/generate_kotlin.py from the C++ headers: do not edit. </auto-generated>
@file:Suppress("EnumEntryName", "unused")

package koral.ui

/** kui::StrokeCap: the same names and values, so a value crosses the C interface as itself. */
enum class StrokeCap(val value: Int) {
    eButt(0),
    eRound(1),
    eSquare(2),
    ;
    companion object { fun of(value: Int): StrokeCap = entries.first { it.value == value } }
}

/** kui::StrokeJoin: the same names and values, so a value crosses the C interface as itself. */
enum class StrokeJoin(val value: Int) {
    eMiter(0),
    eRound(1),
    eBevel(2),
    ;
    companion object { fun of(value: Int): StrokeJoin = entries.first { it.value == value } }
}

/** kui::FillRule: the same names and values, so a value crosses the C interface as itself. */
enum class FillRule(val value: Int) {
    eNonZero(0),
    eEvenOdd(1),
    ;
    companion object { fun of(value: Int): FillRule = entries.first { it.value == value } }
}

/** kui::TextAlign: the same names and values, so a value crosses the C interface as itself. */
enum class TextAlign(val value: Int) {
    eStart(0),
    eCenter(1),
    eEnd(2),
    ;
    companion object { fun of(value: Int): TextAlign = entries.first { it.value == value } }
}

/** kui::Axis: the same names and values, so a value crosses the C interface as itself. */
enum class Axis(val value: Int) {
    eHorizontal(0),
    eVertical(1),
    ;
    companion object { fun of(value: Int): Axis = entries.first { it.value == value } }
}

/** kui::MainAxisAlignment: the same names and values, so a value crosses the C interface as itself. */
enum class MainAxisAlignment(val value: Int) {
    eStart(0),
    eEnd(1),
    eCenter(2),
    eSpaceBetween(3),
    eSpaceAround(4),
    eSpaceEvenly(5),
    ;
    companion object { fun of(value: Int): MainAxisAlignment = entries.first { it.value == value } }
}

/** kui::CrossAxisAlignment: the same names and values, so a value crosses the C interface as itself. */
enum class CrossAxisAlignment(val value: Int) {
    eStart(0),
    eEnd(1),
    eCenter(2),
    eStretch(3),
    ;
    companion object { fun of(value: Int): CrossAxisAlignment = entries.first { it.value == value } }
}

/** kui::MainAxisSize: the same names and values, so a value crosses the C interface as itself. */
enum class MainAxisSize(val value: Int) {
    eMin(0),
    eMax(1),
    ;
    companion object { fun of(value: Int): MainAxisSize = entries.first { it.value == value } }
}

/** kui::ImageFit: the same names and values, so a value crosses the C interface as itself. */
enum class ImageFit(val value: Int) {
    eFill(0),
    eContain(1),
    eCover(2),
    eNone(3),
    ;
    companion object { fun of(value: Int): ImageFit = entries.first { it.value == value } }
}

/** kui::ButtonStyle: the same names and values, so a value crosses the C interface as itself. */
enum class ButtonStyle(val value: Int) {
    ePrimary(0),
    eSecondary(1),
    ePlain(2),
    ;
    companion object { fun of(value: Int): ButtonStyle = entries.first { it.value == value } }
}

/** kui::DockSide: the same names and values, so a value crosses the C interface as itself. */
enum class DockSide(val value: Int) {
    eLeft(0),
    eRight(1),
    eTop(2),
    eBottom(3),
    eCenter(4),
    ;
    companion object { fun of(value: Int): DockSide = entries.first { it.value == value } }
}

/** kui::IconStyle: the same names and values, so a value crosses the C interface as itself. */
enum class IconStyle(val value: Int) {
    eFilled(0),
    eOutlined(1),
    eRounded(2),
    eSharp(3),
    eTwoTone(4),
    ;
    companion object { fun of(value: Int): IconStyle = entries.first { it.value == value } }
}
