#!/usr/bin/env python3
"""
Writes koral-ui/src/main/kotlin/koral/compose/MaterialIcons.kt from the UI module's icons: one property per
Material icon in modules/ui/icons/material/filled, named as Compose names it (`arrow_back` is `ArrowBack`,
`3d_rotation` `_3dRotation`), and the auto-mirrored ones that automirrored.txt lists. Run it after adding or
removing an icon; `--check` (a ctest) fails when the file is stale.
"""
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
ICONS = ROOT / "modules" / "ui" / "icons" / "material"
OUT = pathlib.Path(__file__).resolve().parents[1] / "koral-ui" / "src" / "main" / "kotlin" / "koral" / "compose" / "MaterialIcons.kt"


def compose_name(snake):
    name = "".join(w[:1].upper() + w[1:] for w in snake.split("_"))
    return "_" + name if name[0].isdigit() else name


def properties(names):
    return [f'    val {compose_name(n)}: ImageVector get() = icon("{n}")' for n in sorted(names, key=compose_name)]


def generate():
    names = [f.stem for f in (ICONS / "filled").glob("*.svg")]
    mirrored = (ICONS / "automirrored.txt").read_text().split()
    return "\n".join([
        f"// <auto-generated> by tools/{pathlib.Path(__file__).name} from modules/ui/icons/material: do not edit. </auto-generated>",
        '@file:Suppress("unused", "PropertyName", "ObjectPropertyName")',
        "",
        "package koral.compose",
        "",
        "import koral.ui.IconStyle",
        "",
        f"/** One style of the Material icons — all {len(names)} of Compose's, core and extended — by Compose's names. */",
        "open class MaterialIcons internal constructor(style: IconStyle) : IconSet(style) {",
        *properties(names),
        "}",
        "",
        "/**",
        " * The icons that point a way, as Compose's AutoMirrored has them. They would turn round for a language written",
        " * right to left; koral-ui lays everything out left to right, so they are drawn as they are.",
        " */",
        "open class MirroredIcons internal constructor(style: IconStyle) : IconSet(style) {",
        *properties(mirrored),
        "}",
        "",
    ])


if __name__ == "__main__":
    text = generate()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is stale: run {pathlib.Path(__file__).name}")
            sys.exit(1)
        print("up to date")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT}")
