// <auto-generated> by tools/generate_kotlin.py from modules/net/include/koralNet_c.h: do not edit. </auto-generated>
@file:Suppress("FunctionName", "LocalVariableName", "unused", "ObjectPropertyName", "PropertyName")

package koral.net.interop

import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout.*
import java.lang.invoke.MethodHandle
import koral.interop.Native

/** The C structs' layouts, with C's padding. */
object KnetLayouts {
    val KnetTlsOptions: StructLayout = MemoryLayout.structLayout(
        JAVA_BOOLEAN.withName("verify_peer"),
        MemoryLayout.paddingLayout(7),
        ADDRESS.withName("server_name"),
        ADDRESS.withName("ca_pem"),
    )
    val KnetHttpRequest: StructLayout = MemoryLayout.structLayout(
        ADDRESS.withName("method"),
        ADDRESS.withName("url"),
        ADDRESS.withName("header_names"),
        ADDRESS.withName("header_values"),
        JAVA_LONG.withName("header_count"),
        ADDRESS.withName("body"),
        JAVA_LONG.withName("body_size"),
        JAVA_INT.withName("timeout_ms"),
        JAVA_INT.withName("max_redirects"),
        KnetTlsOptions.withName("tls"),
    )
    val KnetWebSocketOptions: StructLayout = MemoryLayout.structLayout(
        ADDRESS.withName("header_names"),
        ADDRESS.withName("header_values"),
        JAVA_LONG.withName("header_count"),
        ADDRESS.withName("protocols"),
        JAVA_LONG.withName("protocol_count"),
        JAVA_INT.withName("timeout_ms"),
        MemoryLayout.paddingLayout(4),
        KnetTlsOptions.withName("tls"),
        JAVA_LONG.withName("max_message"),
    )
    val KnetNetworkSimulation: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("latency_ms"),
        JAVA_INT.withName("jitter_ms"),
        JAVA_FLOAT.withName("loss"),
        JAVA_FLOAT.withName("duplicate"),
    )
    val KnetHostOptions: StructLayout = MemoryLayout.structLayout(
        JAVA_SHORT.withName("port"),
        MemoryLayout.paddingLayout(6),
        ADDRESS.withName("address"),
        JAVA_INT.withName("max_peers"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("protocol_id"),
        ADDRESS.withName("channels"),
        JAVA_LONG.withName("channel_count"),
        JAVA_INT.withName("timeout_ms"),
        JAVA_INT.withName("connect_timeout_ms"),
        JAVA_INT.withName("keep_alive_ms"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("max_message"),
        KnetNetworkSimulation.withName("simulation"),
    )
    val KnetEvent: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("peer"),
        JAVA_INT.withName("channel"),
        JAVA_INT.withName("reason"),
        ADDRESS.withName("data"),
        JAVA_LONG.withName("size"),
    )
    val KnetPeerStats: StructLayout = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("rtt"),
        JAVA_FLOAT.withName("packet_loss"),
        JAVA_FLOAT.withName("sent_bytes_per_second"),
        JAVA_FLOAT.withName("received_bytes_per_second"),
        JAVA_LONG.withName("packets_sent"),
        JAVA_LONG.withName("packets_received"),
        JAVA_LONG.withName("packets_lost"),
    )
}

object KnetNative {
    // A call to a void function is a statement, which Kotlin's call site types as void, as the handle is;
    // anything else is cast, which types the call site's return.
    private fun handle(name: String, descriptor: FunctionDescriptor): MethodHandle {
        val symbol = Native.koralNet.find(name).orElseThrow { UnsatisfiedLinkError("KnetNative: no " + name) }
        return Native.linker.downcallHandle(symbol, descriptor)
    }

    private val h_knet_op_ready by lazy { handle("knet_op_ready", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS)) }
    fun knet_op_ready(op: MemorySegment): Boolean = h_knet_op_ready.invokeExact(op) as Boolean
    private val h_knet_op_failed by lazy { handle("knet_op_failed", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS)) }
    fun knet_op_failed(op: MemorySegment): Boolean = h_knet_op_failed.invokeExact(op) as Boolean
    private val h_knet_op_error_code by lazy { handle("knet_op_error_code", FunctionDescriptor.of(JAVA_INT, ADDRESS)) }
    fun knet_op_error_code(op: MemorySegment): Int = h_knet_op_error_code.invokeExact(op) as Int
    private val h_knet_op_error by lazy { handle("knet_op_error", FunctionDescriptor.of(ADDRESS, ADDRESS)) }
    fun knet_op_error(op: MemorySegment): String = Native.kString(h_knet_op_error.invokeExact(op) as MemorySegment)
    private val h_knet_op_destroy by lazy { handle("knet_op_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_op_destroy(op: MemorySegment): Unit { h_knet_op_destroy.invokeExact(op) }
    private val h_knet_op_bytes by lazy { handle("knet_op_bytes", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_op_bytes(op: MemorySegment, size: MemorySegment): MemorySegment = h_knet_op_bytes.invokeExact(op, size) as MemorySegment
    private val h_knet_op_take_stream by lazy { handle("knet_op_take_stream", FunctionDescriptor.of(ADDRESS, ADDRESS)) }
    fun knet_op_take_stream(op: MemorySegment): MemorySegment = h_knet_op_take_stream.invokeExact(op) as MemorySegment
    private val h_knet_op_take_websocket by lazy { handle("knet_op_take_websocket", FunctionDescriptor.of(ADDRESS, ADDRESS)) }
    fun knet_op_take_websocket(op: MemorySegment): MemorySegment = h_knet_op_take_websocket.invokeExact(op) as MemorySegment
    private val h_knet_op_address by lazy { handle("knet_op_address", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG, ADDRESS)) }
    fun knet_op_address(op: MemorySegment, index: Long, port: MemorySegment): String = Native.kString(h_knet_op_address.invokeExact(op, index, port) as MemorySegment)
    private val h_knet_op_count by lazy { handle("knet_op_count", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_op_count(op: MemorySegment): Long = h_knet_op_count.invokeExact(op) as Long
    private val h_knet_op_binary by lazy { handle("knet_op_binary", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS)) }
    fun knet_op_binary(op: MemorySegment): Boolean = h_knet_op_binary.invokeExact(op) as Boolean
    private val h_knet_op_status by lazy { handle("knet_op_status", FunctionDescriptor.of(JAVA_INT, ADDRESS)) }
    fun knet_op_status(op: MemorySegment): Int = h_knet_op_status.invokeExact(op) as Int
    private val h_knet_op_url by lazy { handle("knet_op_url", FunctionDescriptor.of(ADDRESS, ADDRESS)) }
    fun knet_op_url(op: MemorySegment): String = Native.kString(h_knet_op_url.invokeExact(op) as MemorySegment)
    private val h_knet_op_header_count by lazy { handle("knet_op_header_count", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_op_header_count(op: MemorySegment): Long = h_knet_op_header_count.invokeExact(op) as Long
    private val h_knet_op_header_name by lazy { handle("knet_op_header_name", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG)) }
    fun knet_op_header_name(op: MemorySegment, index: Long): String = Native.kString(h_knet_op_header_name.invokeExact(op, index) as MemorySegment)
    private val h_knet_op_header_value by lazy { handle("knet_op_header_value", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG)) }
    fun knet_op_header_value(op: MemorySegment, index: Long): String = Native.kString(h_knet_op_header_value.invokeExact(op, index) as MemorySegment)
    private val h_knet_op_header by lazy { handle("knet_op_header", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_op_header(op: MemorySegment, name: String?): String = Arena.ofConfined().use { a -> Native.kString(h_knet_op_header.invokeExact(op, Native.cString(a, name)) as MemorySegment) }
    private val h_knet_tls_options_default by lazy { handle("knet_tls_options_default", FunctionDescriptor.of(KnetLayouts.KnetTlsOptions)) }
    fun knet_tls_options_default(allocator: SegmentAllocator): MemorySegment = h_knet_tls_options_default.invokeExact(allocator) as MemorySegment
    private val h_knet_resolve by lazy { handle("knet_resolve", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_SHORT, ADDRESS)) }
    fun knet_resolve(host: String?, port: Short, done: MemorySegment): MemorySegment = Arena.ofConfined().use { a -> h_knet_resolve.invokeExact(Native.cString(a, host), port, done) as MemorySegment }
    private val h_knet_tcp_connect by lazy { handle("knet_tcp_connect", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_SHORT, JAVA_INT, ADDRESS, ADDRESS)) }
    fun knet_tcp_connect(host: String?, port: Short, timeout_ms: Int, tls: MemorySegment, done: MemorySegment): MemorySegment = Arena.ofConfined().use { a -> h_knet_tcp_connect.invokeExact(Native.cString(a, host), port, timeout_ms, tls, done) as MemorySegment }
    private val h_knet_stream_read_some by lazy { handle("knet_stream_read_some", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT, ADDRESS)) }
    fun knet_stream_read_some(stream: MemorySegment, max_bytes: Long, timeout_ms: Int, done: MemorySegment): MemorySegment = h_knet_stream_read_some.invokeExact(stream, max_bytes, timeout_ms, done) as MemorySegment
    private val h_knet_stream_read_exactly by lazy { handle("knet_stream_read_exactly", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT, ADDRESS)) }
    fun knet_stream_read_exactly(stream: MemorySegment, bytes: Long, timeout_ms: Int, done: MemorySegment): MemorySegment = h_knet_stream_read_exactly.invokeExact(stream, bytes, timeout_ms, done) as MemorySegment
    private val h_knet_stream_read_until by lazy { handle("knet_stream_read_until", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT, ADDRESS)) }
    fun knet_stream_read_until(stream: MemorySegment, delimiter: String?, limit: Long, timeout_ms: Int, done: MemorySegment): MemorySegment = Arena.ofConfined().use { a -> h_knet_stream_read_until.invokeExact(stream, Native.cString(a, delimiter), limit, timeout_ms, done) as MemorySegment }
    private val h_knet_stream_read_to_end by lazy { handle("knet_stream_read_to_end", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT, ADDRESS)) }
    fun knet_stream_read_to_end(stream: MemorySegment, limit: Long, timeout_ms: Int, done: MemorySegment): MemorySegment = h_knet_stream_read_to_end.invokeExact(stream, limit, timeout_ms, done) as MemorySegment
    private val h_knet_stream_write by lazy { handle("knet_stream_write", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT, ADDRESS)) }
    fun knet_stream_write(stream: MemorySegment, data: MemorySegment, size: Long, timeout_ms: Int, done: MemorySegment): MemorySegment = h_knet_stream_write.invokeExact(stream, data, size, timeout_ms, done) as MemorySegment
    private val h_knet_stream_close by lazy { handle("knet_stream_close", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_stream_close(stream: MemorySegment): Unit { h_knet_stream_close.invokeExact(stream) }
    private val h_knet_stream_secure by lazy { handle("knet_stream_secure", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS)) }
    fun knet_stream_secure(stream: MemorySegment): Boolean = h_knet_stream_secure.invokeExact(stream) as Boolean
    private val h_knet_stream_local by lazy { handle("knet_stream_local", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_stream_local(stream: MemorySegment, port: MemorySegment): String = Native.kString(h_knet_stream_local.invokeExact(stream, port) as MemorySegment)
    private val h_knet_stream_remote by lazy { handle("knet_stream_remote", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_stream_remote(stream: MemorySegment, port: MemorySegment): String = Native.kString(h_knet_stream_remote.invokeExact(stream, port) as MemorySegment)
    private val h_knet_stream_destroy by lazy { handle("knet_stream_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_stream_destroy(stream: MemorySegment): Unit { h_knet_stream_destroy.invokeExact(stream) }
    private val h_knet_listener_listen by lazy { handle("knet_listener_listen", FunctionDescriptor.of(ADDRESS, JAVA_SHORT, ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_listener_listen(port: Short, address: String?, certificate_pem: String?, private_key_pem: String?): MemorySegment = Arena.ofConfined().use { a -> h_knet_listener_listen.invokeExact(port, Native.cString(a, address), Native.cString(a, certificate_pem), Native.cString(a, private_key_pem)) as MemorySegment }
    private val h_knet_listener_accept by lazy { handle("knet_listener_accept", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_listener_accept(listener: MemorySegment, done: MemorySegment): MemorySegment = h_knet_listener_accept.invokeExact(listener, done) as MemorySegment
    private val h_knet_listener_port by lazy { handle("knet_listener_port", FunctionDescriptor.of(JAVA_SHORT, ADDRESS)) }
    fun knet_listener_port(listener: MemorySegment): Short = h_knet_listener_port.invokeExact(listener) as Short
    private val h_knet_listener_close by lazy { handle("knet_listener_close", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_listener_close(listener: MemorySegment): Unit { h_knet_listener_close.invokeExact(listener) }
    private val h_knet_listener_destroy by lazy { handle("knet_listener_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_listener_destroy(listener: MemorySegment): Unit { h_knet_listener_destroy.invokeExact(listener) }
    private val h_knet_udp_bind by lazy { handle("knet_udp_bind", FunctionDescriptor.of(ADDRESS, JAVA_SHORT, ADDRESS)) }
    fun knet_udp_bind(port: Short, address: String?): MemorySegment = Arena.ofConfined().use { a -> h_knet_udp_bind.invokeExact(port, Native.cString(a, address)) as MemorySegment }
    private val h_knet_udp_receive by lazy { handle("knet_udp_receive", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_INT, ADDRESS)) }
    fun knet_udp_receive(socket: MemorySegment, timeout_ms: Int, done: MemorySegment): MemorySegment = h_knet_udp_receive.invokeExact(socket, timeout_ms, done) as MemorySegment
    private val h_knet_udp_send_to by lazy { handle("knet_udp_send_to", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS, JAVA_SHORT, ADDRESS, JAVA_LONG, ADDRESS)) }
    fun knet_udp_send_to(socket: MemorySegment, address: String?, port: Short, data: MemorySegment, size: Long, done: MemorySegment): MemorySegment = Arena.ofConfined().use { a -> h_knet_udp_send_to.invokeExact(socket, Native.cString(a, address), port, data, size, done) as MemorySegment }
    private val h_knet_udp_port by lazy { handle("knet_udp_port", FunctionDescriptor.of(JAVA_SHORT, ADDRESS)) }
    fun knet_udp_port(socket: MemorySegment): Short = h_knet_udp_port.invokeExact(socket) as Short
    private val h_knet_udp_close by lazy { handle("knet_udp_close", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_udp_close(socket: MemorySegment): Unit { h_knet_udp_close.invokeExact(socket) }
    private val h_knet_udp_destroy by lazy { handle("knet_udp_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_udp_destroy(socket: MemorySegment): Unit { h_knet_udp_destroy.invokeExact(socket) }
    private val h_knet_http_request_default by lazy { handle("knet_http_request_default", FunctionDescriptor.of(KnetLayouts.KnetHttpRequest, ADDRESS)) }
    fun knet_http_request_default(allocator: SegmentAllocator, url: String?): MemorySegment = Arena.ofConfined().use { a -> h_knet_http_request_default.invokeExact(allocator, Native.cString(a, url)) as MemorySegment }
    private val h_knet_http_fetch by lazy { handle("knet_http_fetch", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_http_fetch(request: MemorySegment, done: MemorySegment): MemorySegment = h_knet_http_fetch.invokeExact(request, done) as MemorySegment
    private val h_knet_websocket_options_default by lazy { handle("knet_websocket_options_default", FunctionDescriptor.of(KnetLayouts.KnetWebSocketOptions)) }
    fun knet_websocket_options_default(allocator: SegmentAllocator): MemorySegment = h_knet_websocket_options_default.invokeExact(allocator) as MemorySegment
    private val h_knet_websocket_connect by lazy { handle("knet_websocket_connect", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_websocket_connect(url: String?, options: MemorySegment, done: MemorySegment): MemorySegment = Arena.ofConfined().use { a -> h_knet_websocket_connect.invokeExact(Native.cString(a, url), options, done) as MemorySegment }
    private val h_knet_websocket_accept by lazy { handle("knet_websocket_accept", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG, ADDRESS)) }
    fun knet_websocket_accept(stream: MemorySegment, max_message: Long, done: MemorySegment): MemorySegment = h_knet_websocket_accept.invokeExact(stream, max_message, done) as MemorySegment
    private val h_knet_websocket_send_text by lazy { handle("knet_websocket_send_text", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_websocket_send_text(socket: MemorySegment, text: String?, done: MemorySegment): MemorySegment = Arena.ofConfined().use { a -> h_knet_websocket_send_text.invokeExact(socket, Native.cString(a, text), done) as MemorySegment }
    private val h_knet_websocket_send_binary by lazy { handle("knet_websocket_send_binary", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS)) }
    fun knet_websocket_send_binary(socket: MemorySegment, data: MemorySegment, size: Long, done: MemorySegment): MemorySegment = h_knet_websocket_send_binary.invokeExact(socket, data, size, done) as MemorySegment
    private val h_knet_websocket_receive by lazy { handle("knet_websocket_receive", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_websocket_receive(socket: MemorySegment, done: MemorySegment): MemorySegment = h_knet_websocket_receive.invokeExact(socket, done) as MemorySegment
    private val h_knet_websocket_close by lazy { handle("knet_websocket_close", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_SHORT, ADDRESS, ADDRESS)) }
    fun knet_websocket_close(socket: MemorySegment, code: Short, reason: String?, done: MemorySegment): MemorySegment = Arena.ofConfined().use { a -> h_knet_websocket_close.invokeExact(socket, code, Native.cString(a, reason), done) as MemorySegment }
    private val h_knet_websocket_open by lazy { handle("knet_websocket_open", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS)) }
    fun knet_websocket_open(socket: MemorySegment): Boolean = h_knet_websocket_open.invokeExact(socket) as Boolean
    private val h_knet_websocket_close_code by lazy { handle("knet_websocket_close_code", FunctionDescriptor.of(JAVA_SHORT, ADDRESS)) }
    fun knet_websocket_close_code(socket: MemorySegment): Short = h_knet_websocket_close_code.invokeExact(socket) as Short
    private val h_knet_websocket_protocol by lazy { handle("knet_websocket_protocol", FunctionDescriptor.of(ADDRESS, ADDRESS)) }
    fun knet_websocket_protocol(socket: MemorySegment): String = Native.kString(h_knet_websocket_protocol.invokeExact(socket) as MemorySegment)
    private val h_knet_websocket_destroy by lazy { handle("knet_websocket_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_websocket_destroy(socket: MemorySegment): Unit { h_knet_websocket_destroy.invokeExact(socket) }
    private val h_knet_bit_writer_create by lazy { handle("knet_bit_writer_create", FunctionDescriptor.of(ADDRESS)) }
    fun knet_bit_writer_create(): MemorySegment = h_knet_bit_writer_create.invokeExact() as MemorySegment
    private val h_knet_bit_writer_destroy by lazy { handle("knet_bit_writer_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_bit_writer_destroy(writer: MemorySegment): Unit { h_knet_bit_writer_destroy.invokeExact(writer) }
    private val h_knet_bit_writer_write_bits by lazy { handle("knet_bit_writer_write_bits", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_INT)) }
    fun knet_bit_writer_write_bits(writer: MemorySegment, value: Long, bits: Int): Unit { h_knet_bit_writer_write_bits.invokeExact(writer, value, bits) }
    private val h_knet_bit_writer_write_var_uint by lazy { handle("knet_bit_writer_write_var_uint", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG)) }
    fun knet_bit_writer_write_var_uint(writer: MemorySegment, value: Long): Unit { h_knet_bit_writer_write_var_uint.invokeExact(writer, value) }
    private val h_knet_bit_writer_write_var_int by lazy { handle("knet_bit_writer_write_var_int", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG)) }
    fun knet_bit_writer_write_var_int(writer: MemorySegment, value: Long): Unit { h_knet_bit_writer_write_var_int.invokeExact(writer, value) }
    private val h_knet_bit_writer_write_float by lazy { handle("knet_bit_writer_write_float", FunctionDescriptor.ofVoid(ADDRESS, JAVA_FLOAT)) }
    fun knet_bit_writer_write_float(writer: MemorySegment, value: Float): Unit { h_knet_bit_writer_write_float.invokeExact(writer, value) }
    private val h_knet_bit_writer_write_double by lazy { handle("knet_bit_writer_write_double", FunctionDescriptor.ofVoid(ADDRESS, JAVA_DOUBLE)) }
    fun knet_bit_writer_write_double(writer: MemorySegment, value: Double): Unit { h_knet_bit_writer_write_double.invokeExact(writer, value) }
    private val h_knet_bit_writer_write_quantized by lazy { handle("knet_bit_writer_write_quantized", FunctionDescriptor.ofVoid(ADDRESS, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_INT)) }
    fun knet_bit_writer_write_quantized(writer: MemorySegment, value: Float, min: Float, max: Float, bits: Int): Unit { h_knet_bit_writer_write_quantized.invokeExact(writer, value, min, max, bits) }
    private val h_knet_bit_writer_write_string by lazy { handle("knet_bit_writer_write_string", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS)) }
    fun knet_bit_writer_write_string(writer: MemorySegment, text: String?): Unit { Arena.ofConfined().use { a -> h_knet_bit_writer_write_string.invokeExact(writer, Native.cString(a, text)); Unit } }
    private val h_knet_bit_writer_write_bytes by lazy { handle("knet_bit_writer_write_bytes", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, JAVA_LONG)) }
    fun knet_bit_writer_write_bytes(writer: MemorySegment, data: MemorySegment, size: Long): Unit { h_knet_bit_writer_write_bytes.invokeExact(writer, data, size) }
    private val h_knet_bit_writer_write_quat by lazy { handle("knet_bit_writer_write_quat", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, JAVA_INT)) }
    fun knet_bit_writer_write_quat(writer: MemorySegment, q: MemorySegment, bits_per_component: Int): Unit { h_knet_bit_writer_write_quat.invokeExact(writer, q, bits_per_component) }
    private val h_knet_bit_writer_align by lazy { handle("knet_bit_writer_align", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_bit_writer_align(writer: MemorySegment): Unit { h_knet_bit_writer_align.invokeExact(writer) }
    private val h_knet_bit_writer_data by lazy { handle("knet_bit_writer_data", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_bit_writer_data(writer: MemorySegment, size: MemorySegment): MemorySegment = h_knet_bit_writer_data.invokeExact(writer, size) as MemorySegment
    private val h_knet_bit_writer_bit_count by lazy { handle("knet_bit_writer_bit_count", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_bit_writer_bit_count(writer: MemorySegment): Long = h_knet_bit_writer_bit_count.invokeExact(writer) as Long
    private val h_knet_bit_writer_clear by lazy { handle("knet_bit_writer_clear", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_bit_writer_clear(writer: MemorySegment): Unit { h_knet_bit_writer_clear.invokeExact(writer) }
    private val h_knet_bit_reader_create by lazy { handle("knet_bit_reader_create", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_LONG)) }
    fun knet_bit_reader_create(data: MemorySegment, size: Long): MemorySegment = h_knet_bit_reader_create.invokeExact(data, size) as MemorySegment
    private val h_knet_bit_reader_destroy by lazy { handle("knet_bit_reader_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_bit_reader_destroy(reader: MemorySegment): Unit { h_knet_bit_reader_destroy.invokeExact(reader) }
    private val h_knet_bit_reader_read_bits by lazy { handle("knet_bit_reader_read_bits", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_INT)) }
    fun knet_bit_reader_read_bits(reader: MemorySegment, bits: Int): Long = h_knet_bit_reader_read_bits.invokeExact(reader, bits) as Long
    private val h_knet_bit_reader_read_var_uint by lazy { handle("knet_bit_reader_read_var_uint", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_bit_reader_read_var_uint(reader: MemorySegment): Long = h_knet_bit_reader_read_var_uint.invokeExact(reader) as Long
    private val h_knet_bit_reader_read_var_int by lazy { handle("knet_bit_reader_read_var_int", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_bit_reader_read_var_int(reader: MemorySegment): Long = h_knet_bit_reader_read_var_int.invokeExact(reader) as Long
    private val h_knet_bit_reader_read_float by lazy { handle("knet_bit_reader_read_float", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS)) }
    fun knet_bit_reader_read_float(reader: MemorySegment): Float = h_knet_bit_reader_read_float.invokeExact(reader) as Float
    private val h_knet_bit_reader_read_double by lazy { handle("knet_bit_reader_read_double", FunctionDescriptor.of(JAVA_DOUBLE, ADDRESS)) }
    fun knet_bit_reader_read_double(reader: MemorySegment): Double = h_knet_bit_reader_read_double.invokeExact(reader) as Double
    private val h_knet_bit_reader_read_quantized by lazy { handle("knet_bit_reader_read_quantized", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT, JAVA_INT)) }
    fun knet_bit_reader_read_quantized(reader: MemorySegment, min: Float, max: Float, bits: Int): Float = h_knet_bit_reader_read_quantized.invokeExact(reader, min, max, bits) as Float
    private val h_knet_bit_reader_read_string by lazy { handle("knet_bit_reader_read_string", FunctionDescriptor.of(ADDRESS, ADDRESS)) }
    fun knet_bit_reader_read_string(reader: MemorySegment): String = Native.kString(h_knet_bit_reader_read_string.invokeExact(reader) as MemorySegment)
    private val h_knet_bit_reader_read_bytes by lazy { handle("knet_bit_reader_read_bytes", FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_bit_reader_read_bytes(reader: MemorySegment, size: MemorySegment): MemorySegment = h_knet_bit_reader_read_bytes.invokeExact(reader, size) as MemorySegment
    private val h_knet_bit_reader_read_quat by lazy { handle("knet_bit_reader_read_quat", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, JAVA_INT)) }
    fun knet_bit_reader_read_quat(reader: MemorySegment, q: MemorySegment, bits_per_component: Int): Unit { h_knet_bit_reader_read_quat.invokeExact(reader, q, bits_per_component) }
    private val h_knet_bit_reader_align by lazy { handle("knet_bit_reader_align", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_bit_reader_align(reader: MemorySegment): Unit { h_knet_bit_reader_align.invokeExact(reader) }
    private val h_knet_bit_reader_failed by lazy { handle("knet_bit_reader_failed", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS)) }
    fun knet_bit_reader_failed(reader: MemorySegment): Boolean = h_knet_bit_reader_failed.invokeExact(reader) as Boolean
    private val h_knet_bit_reader_bits_left by lazy { handle("knet_bit_reader_bits_left", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_bit_reader_bits_left(reader: MemorySegment): Long = h_knet_bit_reader_bits_left.invokeExact(reader) as Long
    private val h_knet_encode_delta by lazy { handle("knet_encode_delta", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_LONG, ADDRESS, JAVA_LONG, ADDRESS, JAVA_LONG)) }
    fun knet_encode_delta(base: MemorySegment, base_size: Long, state: MemorySegment, state_size: Long, out: MemorySegment, capacity: Long): Long = h_knet_encode_delta.invokeExact(base, base_size, state, state_size, out, capacity) as Long
    private val h_knet_decode_delta by lazy { handle("knet_decode_delta", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_LONG, ADDRESS, JAVA_LONG, ADDRESS, JAVA_LONG)) }
    fun knet_decode_delta(base: MemorySegment, base_size: Long, delta: MemorySegment, delta_size: Long, out: MemorySegment, capacity: Long): Long = h_knet_decode_delta.invokeExact(base, base_size, delta, delta_size, out, capacity) as Long
    private val h_knet_host_options_default by lazy { handle("knet_host_options_default", FunctionDescriptor.of(KnetLayouts.KnetHostOptions)) }
    fun knet_host_options_default(allocator: SegmentAllocator): MemorySegment = h_knet_host_options_default.invokeExact(allocator) as MemorySegment
    private val h_knet_host_create by lazy { handle("knet_host_create", FunctionDescriptor.of(ADDRESS, ADDRESS)) }
    fun knet_host_create(options: MemorySegment): MemorySegment = h_knet_host_create.invokeExact(options) as MemorySegment
    private val h_knet_host_destroy by lazy { handle("knet_host_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_host_destroy(host: MemorySegment): Unit { h_knet_host_destroy.invokeExact(host) }
    private val h_knet_host_connect by lazy { handle("knet_host_connect", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_SHORT)) }
    fun knet_host_connect(host: MemorySegment, address: String?, port: Short): Int = Arena.ofConfined().use { a -> h_knet_host_connect.invokeExact(host, Native.cString(a, address), port) as Int }
    private val h_knet_host_send by lazy { handle("knet_host_send", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, JAVA_INT, JAVA_BYTE, ADDRESS, JAVA_LONG)) }
    fun knet_host_send(host: MemorySegment, peer: Int, channel: Byte, data: MemorySegment, size: Long): Boolean = h_knet_host_send.invokeExact(host, peer, channel, data, size) as Boolean
    private val h_knet_host_broadcast by lazy { handle("knet_host_broadcast", FunctionDescriptor.ofVoid(ADDRESS, JAVA_BYTE, ADDRESS, JAVA_LONG, JAVA_INT)) }
    fun knet_host_broadcast(host: MemorySegment, channel: Byte, data: MemorySegment, size: Long, except: Int): Unit { h_knet_host_broadcast.invokeExact(host, channel, data, size, except) }
    private val h_knet_host_disconnect by lazy { handle("knet_host_disconnect", FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT)) }
    fun knet_host_disconnect(host: MemorySegment, peer: Int): Unit { h_knet_host_disconnect.invokeExact(host, peer) }
    private val h_knet_host_update by lazy { handle("knet_host_update", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_host_update(host: MemorySegment): Long = h_knet_host_update.invokeExact(host) as Long
    private val h_knet_host_event by lazy { handle("knet_host_event", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, JAVA_LONG, ADDRESS)) }
    fun knet_host_event(host: MemorySegment, index: Long, event: MemorySegment): Boolean = h_knet_host_event.invokeExact(host, index, event) as Boolean
    private val h_knet_host_flush by lazy { handle("knet_host_flush", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_host_flush(host: MemorySegment): Unit { h_knet_host_flush.invokeExact(host) }
    private val h_knet_host_peer_count by lazy { handle("knet_host_peer_count", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_host_peer_count(host: MemorySegment): Long = h_knet_host_peer_count.invokeExact(host) as Long
    private val h_knet_host_peer_at by lazy { handle("knet_host_peer_at", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_LONG)) }
    fun knet_host_peer_at(host: MemorySegment, index: Long): Int = h_knet_host_peer_at.invokeExact(host, index) as Int
    private val h_knet_host_connected by lazy { handle("knet_host_connected", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, JAVA_INT)) }
    fun knet_host_connected(host: MemorySegment, peer: Int): Boolean = h_knet_host_connected.invokeExact(host, peer) as Boolean
    private val h_knet_host_address by lazy { handle("knet_host_address", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_INT, ADDRESS)) }
    fun knet_host_address(host: MemorySegment, peer: Int, port: MemorySegment): String = Native.kString(h_knet_host_address.invokeExact(host, peer, port) as MemorySegment)
    private val h_knet_host_stats by lazy { handle("knet_host_stats", FunctionDescriptor.of(KnetLayouts.KnetPeerStats, ADDRESS, JAVA_INT)) }
    fun knet_host_stats(allocator: SegmentAllocator, host: MemorySegment, peer: Int): MemorySegment = h_knet_host_stats.invokeExact(allocator, host, peer) as MemorySegment
    private val h_knet_host_port by lazy { handle("knet_host_port", FunctionDescriptor.of(JAVA_SHORT, ADDRESS)) }
    fun knet_host_port(host: MemorySegment): Short = h_knet_host_port.invokeExact(host) as Short
    private val h_knet_host_set_simulation by lazy { handle("knet_host_set_simulation", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS)) }
    fun knet_host_set_simulation(host: MemorySegment, simulation: MemorySegment): Unit { h_knet_host_set_simulation.invokeExact(host, simulation) }
    private val h_knet_replicator_create by lazy { handle("knet_replicator_create", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_BYTE, JAVA_BYTE)) }
    fun knet_replicator_create(host: MemorySegment, control_channel: Byte, snapshot_channel: Byte): MemorySegment = h_knet_replicator_create.invokeExact(host, control_channel, snapshot_channel) as MemorySegment
    private val h_knet_replicator_destroy by lazy { handle("knet_replicator_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_replicator_destroy(replicator: MemorySegment): Unit { h_knet_replicator_destroy.invokeExact(replicator) }
    private val h_knet_replicator_spawn by lazy { handle("knet_replicator_spawn", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT)) }
    fun knet_replicator_spawn(replicator: MemorySegment, `type`: String?, state: MemorySegment, size: Long, owner: Int): Int = Arena.ofConfined().use { a -> h_knet_replicator_spawn.invokeExact(replicator, Native.cString(a, `type`), state, size, owner) as Int }
    private val h_knet_replicator_set_state by lazy { handle("knet_replicator_set_state", FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT, ADDRESS, JAVA_LONG)) }
    fun knet_replicator_set_state(replicator: MemorySegment, id: Int, state: MemorySegment, size: Long): Unit { h_knet_replicator_set_state.invokeExact(replicator, id, state, size) }
    private val h_knet_replicator_despawn by lazy { handle("knet_replicator_despawn", FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT)) }
    fun knet_replicator_despawn(replicator: MemorySegment, id: Int): Unit { h_knet_replicator_despawn.invokeExact(replicator, id) }
    private val h_knet_replicator_count by lazy { handle("knet_replicator_count", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_replicator_count(replicator: MemorySegment): Long = h_knet_replicator_count.invokeExact(replicator) as Long
    private val h_knet_replicator_send_snapshot by lazy { handle("knet_replicator_send_snapshot", FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT)) }
    fun knet_replicator_send_snapshot(replicator: MemorySegment, tick: Int): Unit { h_knet_replicator_send_snapshot.invokeExact(replicator, tick) }
    private val h_knet_replicator_handle by lazy { handle("knet_replicator_handle", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, ADDRESS)) }
    fun knet_replicator_handle(replicator: MemorySegment, event: MemorySegment): Boolean = h_knet_replicator_handle.invokeExact(replicator, event) as Boolean
    private val h_knet_replicator_last_snapshot_bytes by lazy { handle("knet_replicator_last_snapshot_bytes", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_INT)) }
    fun knet_replicator_last_snapshot_bytes(replicator: MemorySegment, peer: Int): Long = h_knet_replicator_last_snapshot_bytes.invokeExact(replicator, peer) as Long
    private val h_knet_replica_set_create by lazy { handle("knet_replica_set_create", FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_INT, JAVA_BYTE, JAVA_BYTE)) }
    fun knet_replica_set_create(host: MemorySegment, server: Int, control_channel: Byte, snapshot_channel: Byte): MemorySegment = h_knet_replica_set_create.invokeExact(host, server, control_channel, snapshot_channel) as MemorySegment
    private val h_knet_replica_set_destroy by lazy { handle("knet_replica_set_destroy", FunctionDescriptor.ofVoid(ADDRESS)) }
    fun knet_replica_set_destroy(replicas: MemorySegment): Unit { h_knet_replica_set_destroy.invokeExact(replicas) }
    private val h_knet_replica_set_handle by lazy { handle("knet_replica_set_handle", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, ADDRESS)) }
    fun knet_replica_set_handle(replicas: MemorySegment, event: MemorySegment): Boolean = h_knet_replica_set_handle.invokeExact(replicas, event) as Boolean
    private val h_knet_replica_set_take_changes by lazy { handle("knet_replica_set_take_changes", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_replica_set_take_changes(replicas: MemorySegment): Long = h_knet_replica_set_take_changes.invokeExact(replicas) as Long
    private val h_knet_replica_set_change by lazy { handle("knet_replica_set_change", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, JAVA_LONG, ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_replica_set_change(replicas: MemorySegment, index: Long, kind: MemorySegment, id: MemorySegment, `type`: MemorySegment): Boolean = h_knet_replica_set_change.invokeExact(replicas, index, kind, id, `type`) as Boolean
    private val h_knet_replica_set_count by lazy { handle("knet_replica_set_count", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun knet_replica_set_count(replicas: MemorySegment): Long = h_knet_replica_set_count.invokeExact(replicas) as Long
    private val h_knet_replica_set_id_at by lazy { handle("knet_replica_set_id_at", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_LONG)) }
    fun knet_replica_set_id_at(replicas: MemorySegment, index: Long): Int = h_knet_replica_set_id_at.invokeExact(replicas, index) as Int
    private val h_knet_replica_set_find by lazy { handle("knet_replica_set_find", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, JAVA_INT, ADDRESS, ADDRESS, ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_replica_set_find(replicas: MemorySegment, id: Int, state: MemorySegment, size: MemorySegment, tick: MemorySegment, owned: MemorySegment, `type`: MemorySegment): Boolean = h_knet_replica_set_find.invokeExact(replicas, id, state, size, tick, owned, `type`) as Boolean
    private val h_knet_replica_set_latest_tick by lazy { handle("knet_replica_set_latest_tick", FunctionDescriptor.of(JAVA_INT, ADDRESS)) }
    fun knet_replica_set_latest_tick(replicas: MemorySegment): Int = h_knet_replica_set_latest_tick.invokeExact(replicas) as Int
    private val h_knet_replica_set_states_around by lazy { handle("knet_replica_set_states_around", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, JAVA_INT, JAVA_FLOAT, ADDRESS, ADDRESS, ADDRESS, ADDRESS, ADDRESS)) }
    fun knet_replica_set_states_around(replicas: MemorySegment, id: Int, tick: Float, from: MemorySegment, from_size: MemorySegment, to: MemorySegment, to_size: MemorySegment, alpha: MemorySegment): Boolean = h_knet_replica_set_states_around.invokeExact(replicas, id, tick, from, from_size, to, to_size, alpha) as Boolean
}
