#!/usr/bin/env python3
"""
kmath's generated code, for every language from one description, so all of them are the same API:
  - C++: the swizzles of kor::Vec (include/kmath/detail/swizzle{2,3,4}.inl);
  - C: the vector and matrix types and every GLSL-chapter function (the generated half of koral_math_c.h,
    and src/core/capi/math_glsl.cpp, whose exports wrap the C++ templates);
  - C#: the vector and matrix types and KMath's GLSL chapters (bindings/csharp/src/Koral/Math/Generated);
  - Kotlin: the same (bindings/kotlin/koral/src/main/kotlin/koral/math/generated).
The functions are spec.py's; the bodies of the C# and Kotlin ones are its little language (dsl.py), so the
two ports do their arithmetic in C++'s order and agree with it bit for bit where IEEE says they must.
`--check` (a ctest) fails when a generated file is stale.
"""
import itertools, pathlib, re, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import dsl  # noqa: E402
import spec  # noqa: E402
from dsl import literal, lower_camel, vec_name  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = {}   # path -> text
HEADER_CS = "// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>"
HEADER_C = "/* <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated> */"
CS_DIR = "bindings/csharp/src/Koral/Math/Generated"
KT_DIR = "bindings/kotlin/koral/src/main/kotlin/koral/math/generated"
XYZW = "xyzw"


def emit(path, text):
    OUT[ROOT / path] = text


def snake(name):
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", s)
    return s.lower()


# ---- types ---------------------------------------------------------------------------------------------------

SCALARS = "fdiub"
C_SCALAR = {"f": "float", "d": "double", "i": "int32_t", "u": "uint32_t", "b": "bool", "h": "uint16_t"}
CPP_SCALAR = {"f": "float", "d": "double", "i": "kor::i32", "u": "kor::u32", "b": "bool", "h": "kor::u16"}
CS_SCALAR = {"f": "float", "d": "double", "i": "int", "u": "uint", "b": "bool", "h": "ushort"}
KT_SCALAR = {"f": "Float", "d": "Double", "i": "Int", "u": "UInt", "b": "Boolean", "h": "UShort"}
C_PREFIX = {"f": "float", "d": "double", "i": "int", "u": "uint", "b": "bool"}
MAT_PREFIX = {"f": "", "d": "D"}


def mat_name(t, c, r):
    return f"{MAT_PREFIX[t]}Mat{c}" if c == r else f"{MAT_PREFIX[t]}Mat{c}x{r}"


def type_name(lang, ty):
    """ty: (code,) scalar or (code, n) vector or (code, c, r) matrix."""
    if len(ty) == 1:
        return {"c": C_SCALAR, "cpp": CPP_SCALAR, "cs": CS_SCALAR, "kt": KT_SCALAR}[lang][ty[0]]
    name = vec_name(ty[0], ty[1]) if len(ty) == 2 else mat_name(*ty)
    if lang == "c":
        return "Koral" + name
    if lang == "cpp":
        return f"kor::Vec<{CPP_SCALAR[ty[0]]}, {ty[1]}>" if len(ty) == 2 else f"kor::Mat<{CPP_SCALAR[ty[0]]}, {ty[1]}, {ty[2]}>"
    return name


def c_prefix(ty):
    if len(ty) == 1:
        return C_PREFIX[ty[0]]
    return (vec_name(*ty) if len(ty) == 2 else mat_name(*ty)).lower()


# ---- function instances -------------------------------------------------------------------------------------

class Param:
    def __init__(self, name, ty, mode, default, mapped):
        self.name, self.ty, self.mode, self.default, self.mapped = name, ty, mode, default, mapped   # mode: "", "out", "ref"


class Inst:
    def __init__(self, fn, t, n, params, ret, how, bcast=False):
        self.fn, self.t, self.n, self.params, self.ret, self.how, self.bcast = fn, t, n, params, ret, how, bcast


def resolve(kind, t, n, mapped):
    """A spec kind as a type, in the scalar function (mapped=False) or its vector form of size n."""
    fixed = {"int": ("i",), "bool": ("b",), "u32": ("u",), "i32": ("i",), "f32": ("f",), "f64": ("d",), "u16": ("h",),
             "f2": ("f", 2), "f4": ("f", 4), "u2": ("u", 2), "void": None}
    if kind == "T":
        return (t, n) if mapped else (t,)
    if kind == "int*":
        return ("i", n) if mapped else ("i",)
    if mapped and kind in ("bool", "u32", "i32", "f32", "int"):
        return (fixed[kind][0], n)
    if kind in fixed:
        return fixed[kind]
    m = re.fullmatch(r"(B|I)?V(\d)?", kind)
    if m:
        code = {"B": "b", "I": "i", None: t}[m.group(1)]
        return (code, int(m.group(2)) if m.group(2) else n)
    raise SystemExit(f"unknown kind {kind}")


def instances():
    out = []
    for fn in spec.FNS:
        kinds = [k.rstrip("&@") for _, k, _ in fn.params] + [fn.ret]
        sized = any(re.fullmatch(r"(B|I)?V", k) for k in kinds)
        for t in fn.types:
            def make(n, mapped, how, bcast=False):
                params = []
                for name, kind, default in fn.params:
                    mode = "out" if kind.endswith("&") else "ref" if kind.endswith("@") else ""
                    k = kind.rstrip("&@")
                    is_mapped = mapped and (k in ("T", "int*") or (mode and k == "int")) and not (bcast and name in fn.bcast)
                    params.append(Param(name, resolve(k, t, n, is_mapped), mode, default, is_mapped))
                return Inst(fn, t, n, params, resolve(fn.ret, t, n, mapped) if fn.ret != "void" else None, how, bcast)
            if sized:
                for n in fn.sizes:
                    out.append(make(n, False, "body"))
            else:
                fixed = [int(m.group(1)) for k in kinds if (m := re.fullmatch(r"(?:B|I)?V(\d)", k))]
                out.append(make(fixed[0] if fixed else None, False, "body"))
            if fn.map:
                for n in (2, 3, 4):
                    out.append(make(n, True, "map"))
                    if fn.bcast:
                        out.append(make(n, True, "map", bcast=True))
    return out


INSTANCES = instances()


def c_name(inst):
    fn = inst.fn
    if fn.chapter.startswith("packing"):
        return "koral_" + snake(fn.name)
    vecs = [p.ty for p in inst.params if len(p.ty) > 1] + ([inst.ret] if inst.ret and len(inst.ret) > 1 else [])
    vec = next((v for v in vecs if v[0] == inst.t), None) or next(iter(vecs), None)
    prefix = c_prefix(vec) if vec else C_PREFIX[inst.t]
    return f"koral_{prefix}_{snake(fn.name)}{'_s' if inst.bcast else ''}"


# ---- swizzles (C++) -----------------------------------------------------------------------------------------

def swizzles(n):
    """Every read swizzle of an n-component vector: 2 to 4 components, repeats allowed."""
    letters = "xyzw"[:n]
    for length in (2, 3, 4):
        for combo in itertools.product(letters, repeat=length):
            yield "".join(combo)


def cpp_swizzles():
    for n in (2, 3, 4):
        lines = [f"// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>",
                 f"// Included inside kor::Vec<T, {n}>: every read swizzle, as glm's GLM_FORCE_SWIZZLE has them — v.ZYX(), v.XXYY().", ""]
        for s in swizzles(n):
            args = ", ".join(s)
            lines.append(f"constexpr Vec<T, {len(s)}> {s.upper()}() const {{ return {{{args}}}; }}")
        emit(f"include/kmath/detail/swizzle{n}.inl", "\n".join(lines) + "\n")


# ---- C ------------------------------------------------------------------------------------------------------

MATS = [(t, c, r) for t in "fd" for c in (2, 3, 4) for r in (2, 3, 4)]
VECS = [(t, n) for t in SCALARS for n in (2, 3, 4)]


def c_param(p):
    ty = type_name("c", p.ty)
    return f"{ty}* {p.name}" if p.mode else f"{ty} {p.name}"


def c_ret(inst):
    return type_name("c", inst.ret) if inst.ret else "void"


def matrix_c_functions():
    """(declaration, C++ body) of the matrix exports."""
    out = []

    def add(ret, name, params, body):
        out.append((ret, name, params, body))

    for t, c, r in MATS:
        M, p = type_name("c", (t, c, r)), c_prefix((t, c, r))
        col, row, s = type_name("c", (t, r)), type_name("c", (t, c)), C_SCALAR[t]
        if c == r:
            add(M, f"koral_{p}_identity", "void", f"return C({type_name('cpp', (t, c, r))}(1));")
            add(s, f"koral_{p}_determinant", f"{M} m", "return kor::Determinant(K(m));")
            add(M, f"koral_{p}_inverse", f"{M} m", "return C(kor::Inverse(K(m)));")
            add(M, f"koral_{p}_diagonal", f"{col} v", "return C(kor::Diagonal(K(v)));")
        for k in (2, 3, 4):   # this (c columns, r rows) * (k columns, c rows)
            other, res = (t, k, c), (t, k, r)
            name = f"koral_{p}_mul" if (k, c) == (c, r) and c == r else f"koral_{p}_mul_{c_prefix(other)}"
            add(type_name("c", res), name, f"{M} a, {type_name('c', other)} b", "return C(K(a) * K(b));")
        add(col, f"koral_{p}_mul_{c_prefix((t, c))}", f"{M} m, {row} v", "return C(K(m) * K(v));")
        add(row, f"koral_{c_prefix((t, r))}_mul_{p}", f"{col} v, {M} m", "return C(K(v) * K(m));")
        add(M, f"koral_{p}_add", f"{M} a, {M} b", "return C(K(a) + K(b));")
        add(M, f"koral_{p}_sub", f"{M} a, {M} b", "return C(K(a) - K(b));")
        add(M, f"koral_{p}_negate", f"{M} m", "return C(-K(m));")
        add(M, f"koral_{p}_mul_s", f"{M} m, {s} s", "return C(K(m) * s);")
        add(M, f"koral_{p}_div_s", f"{M} m, {s} s", "return C(K(m) / s);")
        add("bool", f"koral_{p}_eq", f"{M} a, {M} b", "return K(a) == K(b);")
        add(type_name("c", (t, r, c)), f"koral_{p}_transpose", f"{M} m", "return C(kor::Transpose(K(m)));")
        add(M, f"koral_{p}_matrix_comp_mult", f"{M} a, {M} b", "return C(kor::MatrixCompMult(K(a), K(b)));")
        add(M, f"koral_{p}_outer_product", f"{col} column, {row} row", "return C(kor::OuterProduct(K(column), K(row)));")
        add(row, f"koral_{p}_row", f"{M} m, int32_t r", "return C(kor::Row(K(m), r));")
        add(col, f"koral_{p}_column", f"{M} m, int32_t c", "return C(kor::Column(K(m), c));")
        add(M, f"koral_{p}_set_row", f"{M} m, int32_t r, {row} value", "return C(kor::Row(K(m), r, K(value)));")
        add(M, f"koral_{p}_set_column", f"{M} m, int32_t c, {col} value", "return C(kor::Column(K(m), c, K(value)));")
        add("bool", f"koral_{p}_approx_equal", f"{M} a, {M} b, {s} epsilon", "return kor::ApproxEqual(K(a), K(b), epsilon);")
        for t2, c2, r2 in MATS:
            if (t2, c2, r2) != (t, c, r) and (t2 == t or (c2, r2) == (c, r)):
                add(M, f"koral_{p}_from_{c_prefix((t2, c2, r2))}", f"{type_name('c', (t2, c2, r2))} m",
                    f"return C({type_name('cpp', (t, c, r))}(K(m)));")
    for t in "fd":
        p3, p4 = c_prefix((t, 3, 3)), c_prefix((t, 4, 4))
        add(type_name("c", (t, 3, 3)), f"koral_{p4}_normal_matrix", f"{type_name('c', (t, 4, 4))} model", "return C(kor::NormalMatrix(K(model)));")
        add(type_name("c", (t, 3, 3)), f"koral_{p3}_orthonormalize", f"{type_name('c', (t, 3, 3))} m", "return C(kor::Orthonormalize(K(m)));")
    return out


MATRIX_C = matrix_c_functions()


def c_header_section():
    L = [HEADER_C, "/* The vector and matrix types, and kmath's GLSL chapters: see scripts/kmath/spec.py. */", ""]
    L.append("/* ==== constants (glm's gtc/constants): KORAL_PI is the double, KORAL_PI_F the float ==== */")
    for name, dv, fv, _ in spec.CONSTANTS:
        macro = "KORAL_" + snake(name).upper()
        L.append(f"#define {macro} {dv!r}")
        L.append(f"#define {macro}_F {fv!r}f")
    L += ["", "/* ==== vector types: C++'s kor::Vec<T, N>, member for member ==== */", ""]
    for t, n in VECS:
        L.append(f"typedef struct {type_name('c', (t, n))} {{ {C_SCALAR[t]} {', '.join(XYZW[:n])}; }} {type_name('c', (t, n))};")
    L += ["", "/* ==== matrix types: C columns of R rows, column after column: m[column * R + row] ==== */", ""]
    for t, c, r in MATS:
        L.append(f"typedef struct {type_name('c', (t, c, r))} {{ {C_SCALAR[t]} m[{c * r}]; }} {type_name('c', (t, c, r))};")
    for t in "fd":
        for n in (2, 3, 4):
            L.append(f"typedef {type_name('c', (t, n, n))} Koral{MAT_PREFIX[t]}Mat{n}x{n};")
    L += ["", "/* ==== vector construction and arithmetic (inline): component by component, as C++'s operators ==== */", ""]
    for t, n in VECS:
        V, p, s = type_name("c", (t, n)), c_prefix((t, n)), C_SCALAR[t]
        comps = XYZW[:n]
        args = ", ".join(f"{s} {c}" for c in comps)
        L.append(f"static inline {V} koral_{p}({args}) {{ {V} r = {{{', '.join(comps)}}}; return r; }}")
        L.append(f"static inline {V} koral_{p}_splat({s} s) {{ {V} r = {{{', '.join('s' for _ in comps)}}}; return r; }}")
        ops = []
        if t != "b":
            ops += [("add", "+"), ("sub", "-"), ("mul", "*"), ("div", "/")]
        if t in "iu":
            ops += [("rem", "%"), ("bit_and", "&"), ("bit_or", "|"), ("bit_xor", "^"), ("shl", "<<"), ("shr", ">>")]
        if t == "b":
            ops += [("logical_and", "&&"), ("logical_or", "||")]
        for name, op in ops:
            cast = f"({s})" if t != "b" else ""
            L.append(f"static inline {V} koral_{p}_{name}({V} a, {V} b) {{ return koral_{p}({', '.join(f'{cast}(a.{c} {op} b.{c})' for c in comps)}); }}")
            if t != "b":
                L.append(f"static inline {V} koral_{p}_{name}_s({V} a, {s} s) {{ return koral_{p}({', '.join(f'{cast}(a.{c} {op} s)' for c in comps)}); }}")
        if t in "fdi":
            L.append(f"static inline {V} koral_{p}_negate({V} a) {{ return koral_{p}({', '.join(f'-a.{c}' for c in comps)}); }}")
        if t in "iu":
            L.append(f"static inline {V} koral_{p}_bit_not({V} a) {{ return koral_{p}({', '.join(f'({s})~a.{c}' for c in comps)}); }}")
        L.append(f"static inline bool koral_{p}_eq({V} a, {V} b) {{ return {' && '.join(f'a.{c} == b.{c}' for c in comps)}; }}")
        for t2 in SCALARS:
            if t2 != t:
                L.append(f"static inline {V} koral_{p}_from_{c_prefix((t2, n))}({type_name('c', (t2, n))} v) "
                         f"{{ return koral_{p}({', '.join(f'({s})v.{c}' for c in comps)}); }}")
        for m in range(n + 1, 5):
            L.append(f"static inline {V} koral_{p}_from_{c_prefix((t, m))}({type_name('c', (t, m))} v) {{ return koral_{p}({', '.join(f'v.{c}' for c in comps)}); }}")
        L.append("")
    chapter = None
    for inst in INSTANCES:
        if not inst.fn.c:
            continue
        if inst.fn.chapter != chapter:
            chapter = inst.fn.chapter
            L += ["", f"/* ==== {chapter} ==== */"]
        L.append(f"KORAL_API {c_ret(inst)} {c_name(inst)}({', '.join(c_param(p) for p in inst.params) or 'void'});")
    L += ["", "/* ==== matrices (kmath/matrix.h): koral_<a>_mul_<b> is a * b; _s takes a scalar ==== */"]
    for ret, name, params, _ in MATRIX_C:
        L.append(f"KORAL_API {ret} {name}({params});")
    L += material_c_types()
    L += ["", "/* ==== Euler angles by name (kmath/euler.h): koral_euler_angle_xyz(a, b, c) is X(a) * Y(b) * Z(c) ==== */"]
    L += euler_c()[0]
    return "\n".join(L) + "\n"


def c_source():
    L = [HEADER_C.replace("/*", "//", 1).replace(" */", ""), "// The C exports of kmath's GLSL chapters and matrices: each a C++ template, its C structs bit-cast.", "",
         "#include \"koral_math_c.h\"", "", "#include <kmath.h>", "", "#include <bit>", "", "namespace {",
         "    template<class T> requires std::is_arithmetic_v<T> T K(T v) { return v; }",
         "    template<class T> requires std::is_arithmetic_v<T> T C(T v) { return v; }"]
    for t, n in VECS:
        L.append(f"    {type_name('cpp', (t, n))} K({type_name('c', (t, n))} v) {{ return std::bit_cast<{type_name('cpp', (t, n))}>(v); }}")
        L.append(f"    {type_name('c', (t, n))} C(const {type_name('cpp', (t, n))}& v) {{ return std::bit_cast<{type_name('c', (t, n))}>(v); }}")
    for ty in MATS:
        L.append(f"    {type_name('cpp', ty)} K({type_name('c', ty)} v) {{ return std::bit_cast<{type_name('cpp', ty)}>(v); }}")
        L.append(f"    {type_name('c', ty)} C(const {type_name('cpp', ty)}& v) {{ return std::bit_cast<{type_name('c', ty)}>(v); }}")
    L += ["}", "", "extern \"C\" {", ""]
    for inst in INSTANCES:
        if not inst.fn.c:
            continue
        pre, args, post = [], [], []
        for p in inst.params:
            if p.mode:
                local = f"o_{p.name}"
                init = f"K(*{p.name})" if p.mode == "ref" else f"{type_name('cpp', p.ty)}{{}}"
                pre.append(f"auto {local} = {init};")
                args.append(local)
                post.append(f"*{p.name} = C({local});")
            else:
                args.append(f"K({p.name})")
        call = f"kor::{inst.fn.name}({', '.join(args)})"
        sig = f"{c_ret(inst)} {c_name(inst)}({', '.join(c_param(p) for p in inst.params) or 'void'})"
        if not pre and inst.ret:
            L.append(f"{sig} {{ return C({call}); }}")
        elif not inst.ret:
            L.append(f"{sig} {{ {' '.join(pre)} {call}; {' '.join(post)} }}")
        else:
            L.append(f"{sig} {{ {' '.join(pre)} const auto r = {call}; {' '.join(post)} return C(r); }}")
    L.append("")
    for ret, name, params, body in MATRIX_C:
        L.append(f"{ret} {name}({params}) {{ {body} }}")
    L += [""] + euler_c()[1]
    L += ["", "}", ""]
    return "\n".join(L)


def check_c_names():
    seen = {}
    for inst in INSTANCES:
        if inst.fn.c:
            name = c_name(inst)
            if name in seen:
                raise SystemExit(f"two C functions named {name}")
            seen[name] = inst
    for _, name, _, _ in MATRIX_C:
        if name in seen:
            raise SystemExit(f"two C functions named {name}")
        seen[name] = None


def splice_header():
    path = ROOT / "include/koral_math_c.h"
    text = path.read_text()
    begin, end = "/* ==== BEGIN generated by scripts/kmath/generate.py ==== */\n", "/* ==== END generated ==== */\n"
    a, b = text.index(begin) + len(begin), text.index(end)
    emit("include/koral_math_c.h", text[:a] + c_header_section() + text[b:])


# ---- C# and Kotlin: shared --------------------------------------------------------------------------------

CS_KEYWORDS = {"base", "in", "out", "ref", "object", "string", "params", "fixed", "checked", "operator", "event", "lock"}
KT_CLASH = {   # kotlin.math's own top-level functions of the same name and scalar types: ours would be ambiguous
    "sin": "fd", "cos": "fd", "tan": "fd", "asin": "fd", "acos": "fd", "atan": "fd", "atan2": "fd", "sinh": "fd", "cosh": "fd",
    "tanh": "fd", "asinh": "fd", "acosh": "fd", "atanh": "fd", "sqrt": "fd", "exp": "fd", "log2": "fd", "floor": "fd", "ceil": "fd",
    "round": "fd", "abs": "fdi", "sign": "fd", "min": "fdiu", "max": "fdiu",
}


def default_value(lang, p):
    if p.default == "Epsilon":
        return "DEpsilon" if p.ty[0] == "d" else "Epsilon"
    if p.default == "inf":
        return f"{CS_SCALAR[p.ty[0]]}.PositiveInfinity" if lang == "cs" else f"{KT_SCALAR[p.ty[0]]}.POSITIVE_INFINITY"
    raise SystemExit(p.default)


def raw_body(inst, lang):
    raw = inst.fn.raw[lang]
    if isinstance(raw, dict):
        raw = raw.get(inst.t, raw.get(""))
    if isinstance(raw, str):
        raw = [raw]
    T = (CS_SCALAR if lang == "cs" else KT_SCALAR)[inst.t]
    out = []
    for line in raw:
        line = line.replace("$T", T).replace("$0", literal(0, inst.t, lang))
        line = re.sub(r"@\{([^}]*)\}", lambda m: literal(float(m.group(1)), inst.t, lang), line)
        out.append(line)
    return out


def dsl_body(inst):
    body = inst.fn.body
    if isinstance(body, dict):
        body = body.get(inst.t, body.get(""))
    return body


def zero_of(lang, ty):
    if len(ty) == 1:
        return literal(0, ty[0], lang) if ty[0] != "b" else "false"
    z = literal(0, ty[0], lang) if ty[0] != "b" else "false"
    return f"new {type_name(lang, ty)}({z})" if lang == "cs" else f"{type_name(lang, ty)}({z})"


# ---- C# -----------------------------------------------------------------------------------------------------

def cs_ident(name):
    return "@" + name if name in CS_KEYWORDS else name


def cs_doc(text, indent="    "):
    text = text and text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return [f"{indent}/// <summary>{text}</summary>"] if text else []


def cs_function(inst, documented):
    L = []
    if inst.fn.doc and inst.fn.doc not in documented:
        documented.add(inst.fn.doc)
        L += cs_doc(inst.fn.doc)
    params = []
    for p in inst.params:
        s = f"{'out ' if p.mode == 'out' else 'ref ' if p.mode == 'ref' else ''}{type_name('cs', p.ty)} {cs_ident(p.name)}"
        if p.default:
            s += f" = {default_value('cs', p)}"
        params.append(s)
    ret = type_name("cs", inst.ret) if inst.ret else "void"
    sig = f"    public static {ret} {inst.fn.name}({', '.join(params)})"
    if inst.how == "map":
        n = inst.n
        outs = [p for p in inst.params if p.mode]
        calls = []
        for c in XYZW[:n]:
            args = []
            for p in inst.params:
                if p.mode:
                    args.append(f"out var {p.name}{c.upper()}")
                elif p.mapped:
                    args.append(f"{cs_ident(p.name)}.{c.upper()}")
                else:
                    args.append(cs_ident(p.name))
            calls.append(f"{inst.fn.name}({', '.join(args)})")
        if not outs:
            L.append(f"{sig} => new {type_name('cs', inst.ret)}({', '.join(calls)});")
        else:
            L.append(sig)
            L.append("    {")
            if inst.ret:
                L.append(f"        var r = new {type_name('cs', inst.ret)}({', '.join(calls)});")
            else:
                L += [f"        {c};" for c in calls]
            for p in outs:
                L.append(f"        {p.name} = new {type_name('cs', p.ty)}({', '.join(p.name + c.upper() for c in XYZW[:n])});")
            if inst.ret:
                L.append("        return r;")
            L.append("    }")
        return L
    if inst.fn.raw:
        lines = raw_body(inst, "cs")
        if len(lines) == 1 and lines[0].startswith("="):
            L.append(f"{sig} => {lines[0][1:]};")
        else:
            L += [sig, "    {"] + [f"        {line}" for line in lines] + ["    }"]
        return L
    lines = dsl.body("cs", inst.t, inst.n, dsl_body(inst), 8)
    if len(lines) == 1 and lines[0].strip().startswith("return "):
        L.append(f"{sig} => {lines[0].strip()[7:]}")
    else:
        L += [sig, "    {"] + lines + ["    }"]
    return L


def cs_functions():
    L = [HEADER_CS, "#nullable enable", "using System.Numerics;", "", "namespace Koral;", "",
         "// kmath's GLSL chapters (C++'s kmath/<chapter>.h), for every scalar type and vector size C++ has them for.", "",
         "public static partial class KMath", "{"]
    L.append("    // ---- constants (glm's gtc/constants): the float, and the double as D<name> -----------------")
    for name, dv, fv, doc in spec.CONSTANTS:
        L += cs_doc(doc)
        L.append(f"    public const float {name} = {fv!r}f;")
        L.append(f"    public const double D{name} = {dv!r};")
    L.append("    static int RoundAwayToInt(float v) => v < 0f ? -(int)(-v + 0.5f) : (int)(v + 0.5f);")
    chapter, documented = None, set()
    for inst in INSTANCES:
        if inst.fn.chapter != chapter:
            chapter = inst.fn.chapter
            L += ["", f"    // ---- {chapter} " + "-" * max(4, 100 - len(chapter)), ""]
        L += cs_function(inst, documented)
    L += ["", "    // ---- Euler angles by name (kmath/euler.h): EulerAngleXYZ(a, b, c) is X(a) * Y(b) * Z(c) " + "-" * 12, ""]
    L += euler_managed("cs")
    L.append("}")
    emit(f"{CS_DIR}/KMath.Glsl.g.cs", "\n".join(L) + "\n")


def cs_vectors():
    L = [HEADER_CS, "#nullable enable", "using System.Globalization;", "using System.Runtime.InteropServices;", "", "namespace Koral;", ""]
    for t, n in VECS:
        V, s, comps = vec_name(t, n), CS_SCALAR[t], [c.upper() for c in XYZW[:n]]
        lit = lambda v: literal(v, t, "cs")
        L.append(f"/// <summary>kor::{V}: {n} {s}s, laid out as C++'s.</summary>")
        L.append("[StructLayout(LayoutKind.Sequential)]")
        L.append(f"public partial struct {V} : IEquatable<{V}>")
        L.append("{")
        if t == "b":   # bytes underneath, as C's bool: blittable
            L.append("    " + " ".join(f"private byte _{c.lower()};" for c in comps))
            for c in comps:
                L.append(f"    public bool {c} {{ readonly get => _{c.lower()} != 0; set => _{c.lower()} = value ? (byte)1 : (byte)0; }}")
        else:
            L.append(f"    public {s} {', '.join(comps)};")
        L.append("")
        L.append(f"    public {V}({', '.join(f'{s} {c.lower()}' for c in comps)}) {{ {' '.join(f'{c} = {c.lower()};' for c in comps)} }}")
        L.append(f"    public {V}({s} s) {{ {' '.join(f'{c} = s;' for c in comps)} }}")
        sub = lambda m: vec_name(t, m)
        if n == 3:
            L.append(f"    public {V}({sub(2)} xy, {s} z) {{ X = xy.X; Y = xy.Y; Z = z; }}")
            L.append(f"    public {V}({s} x, {sub(2)} yz) {{ X = x; Y = yz.X; Z = yz.Y; }}")
        if n == 4:
            L.append(f"    public {V}({sub(3)} xyz, {s} w) {{ X = xyz.X; Y = xyz.Y; Z = xyz.Z; W = w; }}")
            L.append(f"    public {V}({s} x, {sub(3)} yzw) {{ X = x; Y = yzw.X; Z = yzw.Y; W = yzw.Z; }}")
            L.append(f"    public {V}({sub(2)} xy, {s} z, {s} w) {{ X = xy.X; Y = xy.Y; Z = z; W = w; }}")
            L.append(f"    public {V}({s} x, {sub(2)} yz, {s} w) {{ X = x; Y = yz.X; Z = yz.Y; W = w; }}")
            L.append(f"    public {V}({s} x, {s} y, {sub(2)} zw) {{ X = x; Y = y; Z = zw.X; W = zw.Y; }}")
            L.append(f"    public {V}({sub(2)} xy, {sub(2)} zw) {{ X = xy.X; Y = xy.Y; Z = zw.X; W = zw.Y; }}")
        L.append("")
        L.append(f"    public {s} this[int i]")
        L.append("    {")
        L.append(f"        readonly get => i switch {{ {' '.join(f'{k} => {c},' for k, c in enumerate(comps))} _ => throw new IndexOutOfRangeException() }};")
        L.append("        set")
        L.append("        {")
        L.append("            switch (i)")
        L.append("            {")
        for k, c in enumerate(comps):
            L.append(f"                case {k}: {c} = value; break;")
        L.append("                default: throw new IndexOutOfRangeException();")
        L.append("            }")
        L.append("        }")
        L.append("    }")
        L.append("")
        if t != "b":
            L.append(f"    public static {V} Zero => default;")
            L.append(f"    public static {V} One => new({lit(1)});")
            for k, c in enumerate(comps):
                L.append(f"    public static {V} Unit{c} => new({', '.join(lit(1 if j == k else 0) for j in range(n))});")
            if n == 3 and t in "fdi":
                for name, v in (("Up", (0, 1, 0)), ("Down", (0, -1, 0)), ("Right", (1, 0, 0)), ("Left", (-1, 0, 0)),
                                ("Forward", (0, 0, -1)), ("Back", (0, 0, 1))):
                    L.append(f"    public static {V} {name} => new({', '.join(lit(x) for x in v)});")
            L.append("")
            ops = ["+", "-", "*", "/"] + (["%", "&", "|", "^"] if t in "iu" else [])
            for op in ops:
                L.append(f"    public static {V} operator {op}({V} a, {V} b) => new({', '.join(f'({s})(a.{c} {op} b.{c})' if t in 'iu' else f'a.{c} {op} b.{c}' for c in comps)});")
                L.append(f"    public static {V} operator {op}({V} a, {s} s) => new({', '.join(f'({s})(a.{c} {op} s)' if t in 'iu' else f'a.{c} {op} s' for c in comps)});")
                L.append(f"    public static {V} operator {op}({s} s, {V} b) => new({', '.join(f'({s})(s {op} b.{c})' if t in 'iu' else f's {op} b.{c}' for c in comps)});")
            if t in "iu":
                for op in ("<<", ">>"):
                    L.append(f"    public static {V} operator {op}({V} a, {V} b) => new({', '.join(f'a.{c} {op} (int)b.{c}' for c in comps)});")
                    L.append(f"    public static {V} operator {op}({V} a, {s} s) => new({', '.join(f'a.{c} {op} (int)s' for c in comps)});")
                L.append(f"    public static {V} operator ~({V} a) => new({', '.join(f'~a.{c}' for c in comps)});")
            if t in "fdi":
                L.append(f"    public static {V} operator -({V} a) => new({', '.join(f'-a.{c}' for c in comps)});")
            L.append(f"    public static {V} operator +({V} a) => a;")
        else:
            for op in ("&", "|", "^"):
                L.append(f"    public static {V} operator {op}({V} a, {V} b) => new({', '.join(f'a.{c} {op} b.{c}' for c in comps)});")
            L.append(f"    public static {V} operator !({V} a) => new({', '.join(f'!a.{c}' for c in comps)});")
        L.append(f"    public static bool operator ==({V} a, {V} b) => {' && '.join(f'a.{c} == b.{c}' for c in comps)};")
        L.append(f"    public static bool operator !=({V} a, {V} b) => !(a == b);")
        L.append("")
        if t == "f":
            L.append(f"    public static implicit operator System.Numerics.Vector{n}({V} v) => new({', '.join(f'v.{c}' for c in comps)});")
            L.append(f"    public static implicit operator {V}(System.Numerics.Vector{n} v) => new({', '.join(f'v.{c}' for c in comps)});")
        L.append(f"    public static implicit operator {V}(({', '.join(f'{s} {c}' for c in comps)}) v) => new({', '.join(f'v.{c}' for c in comps)});")
        for t2 in SCALARS:
            if t2 != t:
                if t2 == "b":
                    conv = lambda c: f"v.{c} ? {lit(1)} : {lit(0)}"
                elif t == "b":
                    conv = lambda c, t2=t2: f"v.{c} != {literal(0, t2, 'cs')}"
                else:
                    conv = lambda c: f"({s})v.{c}"
                L.append(f"    public static explicit operator {V}({vec_name(t2, n)} v) => new({', '.join(conv(c) for c in comps)});")
        for m in range(n + 1, 5):
            L.append(f"    public static explicit operator {V}({vec_name(t, m)} v) => new({', '.join(f'v.{c}' for c in comps)});")
        L.append("")
        L.append(f"    public readonly void Deconstruct({', '.join(f'out {s} {c.lower()}' for c in comps)}) {{ {' '.join(f'{c.lower()} = {c};' for c in comps)} }}")
        L.append(f"    public readonly {s}[] ToArray() => [{', '.join(comps)}];")
        L.append(f"    public readonly bool Equals({V} o) => {' && '.join(f'{c}.Equals(o.{c})' for c in comps)};")
        L.append(f"    public override readonly bool Equals(object? o) => o is {V} v && Equals(v);")
        L.append(f"    public override readonly int GetHashCode() => HashCode.Combine({', '.join(comps)});")
        fmt = ", ".join("{" + c + "}" for c in comps)
        if t == "b":
            L.append(f"    public override readonly string ToString() => $\"({', '.join('{(' + c + ' ? \"true\" : \"false\")}' for c in comps)})\";")
        else:
            L.append(f"    public override readonly string ToString() => string.Create(CultureInfo.InvariantCulture, $\"({fmt})\");")
        L.append("}")
        L.append("")
    emit(f"{CS_DIR}/Vectors.g.cs", "\n".join(L))
    # Swizzles, in their own file: every read swizzle, as C++'s v.ZYX().
    S = [HEADER_CS, "namespace Koral;", ""]
    for t, n in VECS:
        S.append(f"public partial struct {vec_name(t, n)}")
        S.append("{")
        for sw in swizzles(n):
            S.append(f"    public readonly {vec_name(t, len(sw))} {sw.upper()} => new({', '.join(c.upper() for c in sw)});")
        S.append("}")
        S.append("")
    emit(f"{CS_DIR}/Swizzles.g.cs", "\n".join(S))


def mat_elem(lang, m, c, r):
    return f"{m}.C{c}.{XYZW[r].upper()}" if lang == "cs" else f"{m}[{c}, {r}]"


def mat_col(lang, m, c):
    return f"{m}.C{c}" if lang == "cs" else f"{m}[{c}]"


def new(lang, ty, args):
    return f"new {type_name(lang, ty)}({args})" if lang == "cs" else f"{type_name(lang, ty)}({args})"


def matrix_functions(lang):
    """kmath/matrix.h's functions, in C# (static methods) or Kotlin (top-level)."""
    L = []
    cs = lang == "cs"

    def fun(ret, name, params, body):
        """body: an expression, or a list of statements ending in a return."""
        nonlocal L
        tn = lambda ty: type_name(lang, ty) if isinstance(ty, tuple) else ("Int" if ty == "int" and not cs else ty)
        if cs:
            sig = f"    public static {tn(ret)} {name}({', '.join(f'{tn(ty)} {p}' for p, ty in params)})"
        else:
            sig = f"fun {lower_camel(name)}({', '.join(f'{p}: {tn(ty)}' for p, ty in params)}): {tn(ret)}"
        if isinstance(body, str):
            L.append(f"{sig} => {body};" if cs else f"{sig} = {body}")
        else:
            L.append(sig + (" {" if not cs else ""))
            if cs:
                L.append("    {")
            ind = "        " if cs else "    "
            L += [ind + line + (";" if cs else "") for line in body]
            L.append("    }" if cs else "}")

    for t, c, r in MATS:
        M = (t, c, r)
        lit = lambda v: literal(v, t, lang)
        e = lambda m, cc, rr: mat_elem(lang, m, cc, rr)
        col = lambda m, cc: mat_col(lang, m, cc)
        fn_name = (lambda n: n) if cs else lower_camel
        # Transpose
        fun((t, r, c), "Transpose", [("m", M)],
            new(lang, (t, r, c), ", ".join(new(lang, (t, c), ", ".join(e("m", cc, rr) for cc in range(c))) for rr in range(r))))
        fun(M, "MatrixCompMult", [("a", M), ("b", M)], new(lang, M, ", ".join(f"{col('a', cc)} * {col('b', cc)}" for cc in range(c))))
        fun(M, "OuterProduct", [("column", (t, r)), ("row", (t, c))],
            new(lang, M, ", ".join(f"column * row.{XYZW[cc].upper() if cs else XYZW[cc]}" for cc in range(c))))
        fun((t, c), "Row", [("m", M), ("r", "int")], f"m.Row(r)" if cs else "m.row(r)")
        fun((t, r), "Column", [("m", M), ("c", "int")], "m[c]")
        if cs:
            fun(M, "Row", [("m", M), ("r", "int"), ("value", (t, c))], [f"m[{cc}, r] = value.{XYZW[cc].upper()}" for cc in range(c)] + ["return m"])
            fun(M, "Column", [("m", M), ("c", "int"), ("value", (t, r))], ["m[c] = value", "return m"])
        else:
            fun(M, "Row", [("m", M), ("r", "Int"), ("value", (t, c))], "m" + "".join(f".with({cc}, r, value.{XYZW[cc]})" for cc in range(c)))
            fun(M, "Column", [("m", M), ("c", "Int"), ("value", (t, r))], "m.withColumn(c, value)")
        eps = "DEpsilon" if t == "d" else "Epsilon"
        if cs:
            L.append(f"    public static bool ApproxEqual({type_name(lang, M)} a, {type_name(lang, M)} b, {CS_SCALAR[t]} epsilon = {eps}) => "
                     + " && ".join(f"ApproxEqual(a.C{cc}, b.C{cc}, epsilon)" for cc in range(c)) + ";")
        else:
            L.append(f"fun approxEqual(a: {type_name(lang, M)}, b: {type_name(lang, M)}, epsilon: {KT_SCALAR[t]} = {eps}) = "
                     + " && ".join(f"approxEqual(a[{cc}], b[{cc}], epsilon)" for cc in range(c)))
        if c == r:
            n = c
            fun(M, "Diagonal", [("v", (t, n))], new(lang, M, ", ".join(new(lang, (t, n), ", ".join(
                (f"v.{XYZW[k].upper() if cs else XYZW[k]}" if k == cc else lit(0)) for k in range(n))) for cc in range(n))))
            if n == 2:
                fun((t,), "Determinant", [("m", M)], f"{e('m', 0, 0)} * {e('m', 1, 1)} - {e('m', 1, 0)} * {e('m', 0, 1)}")
                fun(M, "Inverse", [("m", M)], [f"{'var' if cs else 'val'} inv = {lit(1)} / Determinant(m)".replace("Determinant", fn_name("Determinant")),
                                                "return " + new(lang, M, f"{new(lang, (t, 2), f'{e(chr(109), 1, 1)} * inv, -{e(chr(109), 0, 1)} * inv')}, "
                                                                         f"{new(lang, (t, 2), f'-{e(chr(109), 1, 0)} * inv, {e(chr(109), 0, 0)} * inv')}")])
            if n == 3:
                fun((t,), "Determinant", [("m", M)], f"{fn_name('Dot')}({col('m', 0)}, {fn_name('Cross')}({col('m', 1)}, {col('m', 2)}))")
                v = "var" if cs else "val"
                fun(M, "Inverse", [("m", M)], [
                    f"{v} r0 = {fn_name('Cross')}({col('m', 1)}, {col('m', 2)})", f"{v} r1 = {fn_name('Cross')}({col('m', 2)}, {col('m', 0)})",
                    f"{v} r2 = {fn_name('Cross')}({col('m', 0)}, {col('m', 1)})", f"{v} inv = {lit(1)} / {fn_name('Dot')}({col('m', 0)}, r0)",
                    f"return {fn_name('Transpose')}({new(lang, M, 'r0 * inv, r1 * inv, r2 * inv')})"])
                fun(M, "Orthonormalize", [("m", M)], [
                    f"{v} c0 = {fn_name('Normalize')}({col('m', 0)})", f"{v} d0 = {fn_name('Dot')}(c0, {col('m', 1)})",
                    f"{v} c1 = {fn_name('Normalize')}({col('m', 1)} - c0 * d0)", f"{v} d1 = {fn_name('Dot')}(c1, {col('m', 2)})",
                    f"{v} d2 = {fn_name('Dot')}(c0, {col('m', 2)})", f"{v} c2 = {fn_name('Normalize')}({col('m', 2)} - (c0 * d2 + c1 * d1))",
                    f"return {new(lang, M, 'c0, c1, c2')}"])
            if n == 4:
                m = lambda cc, rr: e("m", cc, rr)
                v = "var" if cs else "val"
                det = [f"{v} s0 = {m(2,2)} * {m(3,3)} - {m(3,2)} * {m(2,3)}", f"{v} s1 = {m(2,1)} * {m(3,3)} - {m(3,1)} * {m(2,3)}",
                       f"{v} s2 = {m(2,1)} * {m(3,2)} - {m(3,1)} * {m(2,2)}", f"{v} s3 = {m(2,0)} * {m(3,3)} - {m(3,0)} * {m(2,3)}",
                       f"{v} s4 = {m(2,0)} * {m(3,2)} - {m(3,0)} * {m(2,2)}", f"{v} s5 = {m(2,0)} * {m(3,1)} - {m(3,0)} * {m(2,1)}",
                       f"{v} c0 = +({m(1,1)} * s0 - {m(1,2)} * s1 + {m(1,3)} * s2)", f"{v} c1 = -({m(1,0)} * s0 - {m(1,2)} * s3 + {m(1,3)} * s4)",
                       f"{v} c2 = +({m(1,0)} * s1 - {m(1,1)} * s3 + {m(1,3)} * s5)", f"{v} c3 = -({m(1,0)} * s2 - {m(1,1)} * s4 + {m(1,2)} * s5)",
                       f"return {m(0,0)} * c0 + {m(0,1)} * c1 + {m(0,2)} * c2 + {m(0,3)} * c3"]
                if not cs:
                    det = [d.replace("+(", "(") for d in det]
                fun((t,), "Determinant", [("m", M)], det)
                a = lambda x, y, z, w: f"{v} a{x}{y}{z}{w} = {m(z, x)} * {m(w, y)} - {m(z, y)} * {m(w, x)}"
                # aXYZW = m[Z][X] * m[W][Y] - m[Z][Y] * m[W][X]: C++'s a2323 = m[2][2]*m[3][3] - m[2][3]*m[3][2]
                subs = ["2323", "1323", "1223", "0323", "0223", "0123", "2313", "1313", "1213", "2312", "1312", "1212", "0313", "0213", "0312",
                        "0212", "0113", "0112"]
                body = [f"{v} a{s_} = {m(int(s_[2]), int(s_[0]))} * {m(int(s_[3]), int(s_[1]))} - {m(int(s_[2]), int(s_[1]))} * {m(int(s_[3]), int(s_[0]))}"
                        for s_ in subs]
                body.append(f"{v} det = {m(0,0)} * ({m(1,1)} * a2323 - {m(1,2)} * a1323 + {m(1,3)} * a1223)"
                            f" - {m(0,1)} * ({m(1,0)} * a2323 - {m(1,2)} * a0323 + {m(1,3)} * a0223)"
                            f" + {m(0,2)} * ({m(1,0)} * a1323 - {m(1,1)} * a0323 + {m(1,3)} * a0123)"
                            f" - {m(0,3)} * ({m(1,0)} * a1223 - {m(1,1)} * a0223 + {m(1,2)} * a0123)")
                body.append(f"{v} inv = {lit(1)} / det")
                R = [
                    "inv * ({m11} * a2323 - {m12} * a1323 + {m13} * a1223)", "inv * -({m01} * a2323 - {m02} * a1323 + {m03} * a1223)",
                    "inv * ({m01} * a2313 - {m02} * a1313 + {m03} * a1213)", "inv * -({m01} * a2312 - {m02} * a1312 + {m03} * a1212)",
                    "inv * -({m10} * a2323 - {m12} * a0323 + {m13} * a0223)", "inv * ({m00} * a2323 - {m02} * a0323 + {m03} * a0223)",
                    "inv * -({m00} * a2313 - {m02} * a0313 + {m03} * a0213)", "inv * ({m00} * a2312 - {m02} * a0312 + {m03} * a0212)",
                    "inv * ({m10} * a1323 - {m11} * a0323 + {m13} * a0123)", "inv * -({m00} * a1323 - {m01} * a0323 + {m03} * a0123)",
                    "inv * ({m00} * a1313 - {m01} * a0313 + {m03} * a0113)", "inv * -({m00} * a1312 - {m01} * a0312 + {m03} * a0112)",
                    "inv * -({m10} * a1223 - {m11} * a0223 + {m12} * a0123)", "inv * ({m00} * a1223 - {m01} * a0223 + {m02} * a0123)",
                    "inv * -({m00} * a1213 - {m01} * a0213 + {m02} * a0113)", "inv * ({m00} * a1212 - {m01} * a0212 + {m02} * a0112)"]
                names = {f"m{cc}{rr}": m(cc, rr) for cc in range(4) for rr in range(4)}
                R = [x.format(**names) for x in R]
                cols = [new(lang, (t, 4), ", ".join(R[cc * 4: cc * 4 + 4])) for cc in range(4)]
                body.append("return " + new(lang, M, ", ".join(cols)))
                fun(M, "Inverse", [("m", M)], body)
                fun((t, 3, 3), "NormalMatrix", [("model", M)], f"{fn_name('Transpose')}({fn_name('Inverse')}(" + (f"({type_name(lang, (t, 3, 3))})model" if cs else f"{type_name(lang, (t, 3, 3))}(model)") + "))")
    return L


def cs_matrices():
    L = [HEADER_CS, "#nullable enable", "using System.Runtime.CompilerServices;", "using System.Runtime.InteropServices;", "", "namespace Koral;", ""]
    for t, c, r in MATS:
        M, s, Col, Row = mat_name(t, c, r), CS_SCALAR[t], vec_name(t, r), vec_name(t, c)
        cols = [f"C{k}" for k in range(c)]
        lit = lambda v: literal(v, t, "cs")
        L.append(f"/// <summary>kor::{M}: {c} columns of {r} rows, column after column (<c>m[c]</c> a column, <c>m[c, r]</c> an element); "
                 f"<c>new {M}()</c> has ones on its diagonal, <c>default</c> is all zero.</summary>")
        L.append("[StructLayout(LayoutKind.Sequential)]")
        L.append(f"public struct {M} : IEquatable<{M}>")
        L.append("{")
        L.append(f"    public {Col} {', '.join(cols)};")
        L.append("")
        L.append(f"    public {M}() : this({lit(1)}) {{ }}")
        L.append(f"    public {M}({', '.join(f'{Col} c{k}' for k in range(c))}) {{ {' '.join(f'C{k} = c{k};' for k in range(c))} }}")
        L.append(f"    /// <summary><paramref name=\"diagonal\"/> on the diagonal, zero elsewhere.</summary>")
        L.append(f"    public {M}({s} diagonal) : this({', '.join(f'new {Col}(' + ', '.join('diagonal' if k == j else lit(0) for j in range(r)) + ')' for k in range(c))}) {{ }}")
        L.append(f"    /// <summary>From {c * r} values, column after column.</summary>")
        L.append(f"    public {M}(ReadOnlySpan<{s}> columnMajor)")
        L.append("    {")
        L.append(f"        if (columnMajor.Length != {c * r}) throw new ArgumentException(\"a {M} is {c * r} values\", nameof(columnMajor));")
        L.append(f"        this = MemoryMarshal.Read<{M}>(MemoryMarshal.AsBytes(columnMajor));")
        L.append("    }")
        L.append("")
        if c == r:
            L.append(f"    public static {M} Identity => new({lit(1)});")
        L.append(f"    public static {M} Zero => default;")
        L.append("")
        L.append(f"    public {Col} this[int column]")
        L.append("    {")
        L.append(f"        readonly get => column switch {{ {' '.join(f'{k} => C{k},' for k in range(c))} _ => throw new IndexOutOfRangeException() }};")
        L.append("        set")
        L.append("        {")
        L.append("            switch (column)")
        L.append("            {")
        for k in range(c):
            L.append(f"                case {k}: C{k} = value; break;")
        L.append("                default: throw new IndexOutOfRangeException();")
        L.append("            }")
        L.append("        }")
        L.append("    }")
        L.append(f"    public {s} this[int column, int row]")
        L.append("    {")
        L.append("        readonly get => this[column][row];")
        L.append("        set { var col = this[column]; col[row] = value; this[column] = col; }")
        L.append("    }")
        L.append(f"    public readonly {Row} Row(int r) => new({', '.join(f'C{k}[r]' for k in range(c))});")
        L.append(f"    /// <summary>The {c * r} values, column after column.</summary>")
        L.append(f"    public readonly {s}[] ToArray() {{ var a = new {s}[{c * r}]; MemoryMarshal.Write(MemoryMarshal.AsBytes(a.AsSpan()), in this); return a; }}")
        L.append("")
        for k in (2, 3, 4):
            other, res = mat_name(t, k, c), mat_name(t, k, r)
            L.append(f"    public static {res} operator *({M} a, {other} b) => new({', '.join(f'a * b.C{j}' for j in range(k))});")
        L.append(f"    public static {Col} operator *({M} m, {Row} v) => {' + '.join(f'm.C{k} * v.{XYZW[k].upper()}' for k in range(c))};")
        L.append(f"    public static {Row} operator *({Col} v, {M} m) => new({', '.join(f'KMath.Dot(v, m.C{k})' for k in range(c))});")
        L.append(f"    public static {M} operator *({M} m, {s} s) => new({', '.join(f'm.C{k} * s' for k in range(c))});")
        L.append(f"    public static {M} operator *({s} s, {M} m) => new({', '.join(f'm.C{k} * s' for k in range(c))});")
        L.append(f"    public static {M} operator /({M} m, {s} s) => new({', '.join(f'm.C{k} / s' for k in range(c))});")
        L.append(f"    public static {M} operator +({M} a, {M} b) => new({', '.join(f'a.C{k} + b.C{k}' for k in range(c))});")
        L.append(f"    public static {M} operator -({M} a, {M} b) => new({', '.join(f'a.C{k} - b.C{k}' for k in range(c))});")
        L.append(f"    public static {M} operator -({M} m) => new({', '.join(f'-m.C{k}' for k in range(c))});")
        L.append(f"    public static bool operator ==({M} a, {M} b) => {' && '.join(f'a.C{k} == b.C{k}' for k in range(c))};")
        L.append(f"    public static bool operator !=({M} a, {M} b) => !(a == b);")
        L.append("")
        for t2, c2, r2 in MATS:
            if (t2, c2, r2) == (t, c, r) or not (t2 == t or (c2, r2) == (c, r)):
                continue
            src = mat_name(t2, c2, r2)
            def el(cc, rr):
                if cc < c2 and rr < r2:
                    v = f"m.C{cc}.{XYZW[rr].upper()}"
                    return v if t2 == t else f"({s}){v}"
                return lit(1 if cc == rr else 0)
            L.append(f"    /// <summary>The overlap of a {src}; the rest is the identity's.</summary>" if t2 == t and (c2, r2) != (c, r) else "")
            L.append(f"    public {M}({src} m) : this({', '.join(f'new {Col}(' + ', '.join(el(cc, rr) for rr in range(r)) + ')' for cc in range(c))}) {{ }}")
            L.append(f"    public static explicit operator {M}({src} m) => new(m);")
        if (t, c, r) == ("f", 4, 4):
            L.append(f"    public static implicit operator System.Numerics.Matrix4x4({M} m) => Unsafe.BitCast<{M}, System.Numerics.Matrix4x4>(m);")
            L.append(f"    public static implicit operator {M}(System.Numerics.Matrix4x4 m) => Unsafe.BitCast<System.Numerics.Matrix4x4, {M}>(m);")
        if (t, c, r) == ("f", 3, 2):
            L.append(f"    public static implicit operator System.Numerics.Matrix3x2({M} m) => Unsafe.BitCast<{M}, System.Numerics.Matrix3x2>(m);")
            L.append(f"    public static implicit operator {M}(System.Numerics.Matrix3x2 m) => Unsafe.BitCast<System.Numerics.Matrix3x2, {M}>(m);")
        L.append("")
        L.append(f"    public readonly bool Equals({M} o) => {' && '.join(f'C{k}.Equals(o.C{k})' for k in range(c))};")
        L.append(f"    public override readonly bool Equals(object? o) => o is {M} m && Equals(m);")
        L.append(f"    public override readonly int GetHashCode() => HashCode.Combine({', '.join(cols)});")
        L.append(f"    public override readonly string ToString() => $\"[{'; '.join('{Row(' + str(k) + ')}' for k in range(r))}]\";")
        L.append("}")
        L.append("")
    L.append("public static partial class KMath")
    L.append("{")
    L.append("    // ---- matrices (kmath/matrix.h) ------------------------------------------------------------------")
    L += matrix_functions("cs")
    L.append("}")
    emit(f"{CS_DIR}/Matrices.g.cs", "\n".join(x for x in L) + "\n")


# ---- Kotlin -------------------------------------------------------------------------------------------------

def kt_function(inst, documented):
    L = []
    if inst.fn.doc and inst.fn.doc not in documented:
        documented.add(inst.fn.doc)
        L.append(f"/** {inst.fn.doc} */")
    name = lower_camel(inst.fn.name)
    scalar_only = all(len(p.ty) == 1 for p in inst.params) and (not inst.ret or len(inst.ret) == 1)
    private = scalar_only and inst.t in KT_CLASH.get(name, "")
    params = []
    for p in inst.params:
        ty = type_name("kt", p.ty)
        s = f"{p.name}: {'Ref<' + ty + '>' if p.mode else ty}"
        if p.default:
            s += f" = {default_value('kt', p)}"
        params.append(s)
    ret = type_name("kt", inst.ret) if inst.ret else "Unit"
    sig = f"{'private ' if private else ''}fun {name}({', '.join(params)}): {ret}"
    if inst.how == "map":
        n = inst.n
        outs = [p for p in inst.params if p.mode]
        calls = []
        for c in XYZW[:n]:
            args = []
            for p in inst.params:
                if p.mode:
                    args.append(f"{p.name}{c.upper()}")
                elif p.mapped:
                    args.append(f"{p.name}.{c}")
                else:
                    args.append(p.name)
            calls.append(f"{name}({', '.join(args)})")
        if not outs:
            L.append(f"{sig} = {type_name('kt', inst.ret)}({', '.join(calls)})")
        else:
            L.append(sig + " {")
            for p in outs:
                for c in XYZW[:n]:
                    L.append(f"    val {p.name}{c.upper()} = Ref({zero_of('kt', (p.ty[0],))})")
            if inst.ret:
                L.append(f"    val r = {type_name('kt', inst.ret)}({', '.join(calls)})")
            else:
                L += [f"    {c}" for c in calls]
            for p in outs:
                L.append(f"    {p.name}.value = {type_name('kt', p.ty)}({', '.join(p.name + c.upper() + '.value' for c in XYZW[:n])})")
            if inst.ret:
                L.append("    return r")
            L.append("}")
        return L
    if inst.fn.raw:
        lines = raw_body(inst, "kt")
        if len(lines) == 1 and lines[0].startswith("="):
            L.append(f"{sig} = {lines[0][1:]}")
        else:
            L += [sig + " {"] + [f"    {line}" for line in lines] + ["}"]
        return L
    lines = dsl.body("kt", inst.t, inst.n, dsl_body(inst), 4)
    if len(lines) == 1 and lines[0].strip().startswith("return "):
        L.append(f"{sig} = {lines[0].strip()[7:]}")
    else:
        L += [sig + " {"] + lines + ["}"]
    return L


def kt_functions():
    L = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>",
         '@file:Suppress("NOTHING_TO_INLINE", "unused", "FunctionName")', '@file:JvmName("KMathGlsl")', "", "package koral", "",
         "import kotlin.math.pow", "import kotlin.math.withSign", "",
         "// kmath's GLSL chapters (C++'s kmath/<chapter>.h), for every scalar type and vector size C++ has them for. Where",
         "// kotlin.math has a scalar function of the same name (sin, sqrt, floor, min, abs, ...), the scalar one here is",
         "// private and kotlin.math's is the one to call; the vector forms are all here.", "",
         "/** A value a function writes back: C++'s reference parameters (Modf's whole part, SmoothDamp's velocity). */",
         "class Ref<T>(var value: T) { override fun toString() = \"Ref($value)\" }", ""]
    for name, dv, fv, doc in spec.CONSTANTS:
        if doc:
            L.append(f"/** {doc} */")
        L.append(f"const val {name}: Float = {fv!r}f")
        L.append(f"const val D{name}: Double = {dv!r}")
    L += ["", "private fun roundAway(v: Float): Float { val r = kotlin.math.truncate(v); return if (kotlin.math.abs(v - r) >= 0.5f) r + kotlin.math.sign(v) else r }",
          "private fun roundAway(v: Double): Double { val r = kotlin.math.truncate(v); return if (kotlin.math.abs(v - r) >= 0.5) r + kotlin.math.sign(v) else r }",
          "private fun roundAwayToInt(v: Float): Int = if (v < 0f) -((-v + 0.5f).toInt()) else (v + 0.5f).toInt()"]
    chapter, documented = None, set()
    for inst in INSTANCES:
        if inst.fn.chapter != chapter:
            chapter = inst.fn.chapter
            L += ["", f"// ---- {chapter} " + "-" * max(4, 104 - len(chapter)), ""]
        L += kt_function(inst, documented)
    L += ["", "// ---- matrices (kmath/matrix.h) " + "-" * 76, ""]
    L += matrix_functions("kt")
    L += ["", "// ---- Euler angles by name (kmath/euler.h): eulerAngleXYZ(a, b, c) is X(a) * Y(b) * Z(c) " + "-" * 16, ""]
    L += euler_managed("kt")
    emit(f"{KT_DIR}/Glsl.kt", "\n".join(L) + "\n")


KT_ARRAY = {"f": "FloatArray", "d": "DoubleArray", "i": "IntArray", "u": "UIntArray", "b": "BooleanArray"}
KT_ARRAY_OF = {"f": "floatArrayOf", "d": "doubleArrayOf", "i": "intArrayOf", "u": "uintArrayOf", "b": "booleanArrayOf"}


def kt_vectors():
    L = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>",
         '@file:Suppress("NOTHING_TO_INLINE", "unused")', '@file:OptIn(ExperimentalUnsignedTypes::class)', "", "package koral", ""]
    for t, n in VECS:
        V, s, comps = vec_name(t, n), KT_SCALAR[t], XYZW[:n]
        lit = lambda v: literal(v, t, "kt")
        L.append(f"/** kor::{V}: {n} {s}s, immutable. */")
        L.append(f"data class {V}({', '.join(f'val {c}: {s}' for c in comps)}) {{")
        L.append(f"    constructor(s: {s}) : this({', '.join('s' for _ in comps)})")
        sub = lambda m: vec_name(t, m)
        if n == 3:
            L.append(f"    constructor(xy: {sub(2)}, z: {s}) : this(xy.x, xy.y, z)")
            L.append(f"    constructor(x: {s}, yz: {sub(2)}) : this(x, yz.x, yz.y)")
        if n == 4:
            L.append(f"    constructor(xyz: {sub(3)}, w: {s}) : this(xyz.x, xyz.y, xyz.z, w)")
            L.append(f"    constructor(x: {s}, yzw: {sub(3)}) : this(x, yzw.x, yzw.y, yzw.z)")
            L.append(f"    constructor(xy: {sub(2)}, z: {s}, w: {s}) : this(xy.x, xy.y, z, w)")
            L.append(f"    constructor(x: {s}, yz: {sub(2)}, w: {s}) : this(x, yz.x, yz.y, w)")
            L.append(f"    constructor(x: {s}, y: {s}, zw: {sub(2)}) : this(x, y, zw.x, zw.y)")
            L.append(f"    constructor(xy: {sub(2)}, zw: {sub(2)}) : this(xy.x, xy.y, zw.x, zw.y)")
        for m in range(n + 1, 5):
            L.append(f"    /** The first {n} of a {vec_name(t, m)} (C++'s explicit conversion). */")
            L.append(f"    constructor(v: {vec_name(t, m)}) : this({', '.join(f'v.{c}' for c in comps)})")
        L.append("")
        L.append(f"    operator fun get(i: Int): {s} = when (i) {{ {' '.join(f'{k} -> {c};' for k, c in enumerate(comps))} else -> throw IndexOutOfBoundsException(i) }}")
        L.append(f"    /** The same with component i replaced: `v.with(1, 0f)`. */")
        L.append(f"    fun with(i: Int, value: {s}) = when (i) {{ {' '.join(f'{k} -> copy({c} = value);' for k, c in enumerate(comps))} else -> throw IndexOutOfBoundsException(i) }}")
        L.append(f"    fun toArray() = {KT_ARRAY_OF[t]}({', '.join(comps)})")
        if t != "b":
            ops = [("plus", "+"), ("minus", "-"), ("times", "*"), ("div", "/")] + ([("rem", "%")] if t in "iu" else [])
            for name, op in ops:
                L.append(f"    operator fun {name}(o: {V}) = {V}({', '.join(f'{c} {op} o.{c}' for c in comps)})")
                L.append(f"    operator fun {name}(s: {s}) = {V}({', '.join(f'{c} {op} s' for c in comps)})")
            if t in "fdi":
                L.append(f"    operator fun unaryMinus() = {V}({', '.join(f'-{c}' for c in comps)})")
            L.append(f"    operator fun unaryPlus() = this")
            if t in "iu":
                for name in ("and", "or", "xor"):
                    L.append(f"    infix fun {name}(o: {V}) = {V}({', '.join(f'{c} {name} o.{c}' for c in comps)})")
                    L.append(f"    infix fun {name}(s: {s}) = {V}({', '.join(f'{c} {name} s' for c in comps)})")
                for name in ("shl", "shr"):
                    L.append(f"    infix fun {name}(o: {V}) = {V}({', '.join(f'{c} {name} o.{c}.toInt()' for c in comps)})")
                    L.append(f"    infix fun {name}(s: Int) = {V}({', '.join(f'{c} {name} s' for c in comps)})")
                L.append(f"    fun inv() = {V}({', '.join(f'{c}.inv()' for c in comps)})")
        else:
            for name in ("and", "or", "xor"):
                L.append(f"    infix fun {name}(o: {V}) = {V}({', '.join(f'{c} {name} o.{c}' for c in comps)})")
            L.append(f"    operator fun not() = {V}({', '.join(f'!{c}' for c in comps)})")
        for t2 in SCALARS:
            if t2 == t:
                continue
            conv = {"f": "toFloat()", "d": "toDouble()", "i": "toInt()", "u": "toUInt()"}
            if t2 == "b":
                expr = lambda c: f"{c} != {lit(0)}"
            elif t == "b":
                expr = lambda c, t2=t2: f"if ({c}) {literal(1, t2, 'kt')} else {literal(0, t2, 'kt')}"
            else:
                expr = lambda c, t2=t2: f"{c}.{conv[t2]}"
            L.append(f"    fun to{vec_name(t2, n)}() = {vec_name(t2, n)}({', '.join(expr(c) for c in comps)})")
        L.append(f"    override fun toString() = \"({', '.join('$' + c for c in comps)})\"")
        if t != "b":
            L.append("")
            L.append("    companion object {")
            L.append(f"        val Zero = {V}({lit(0)})")
            L.append(f"        val One = {V}({lit(1)})")
            for k, c in enumerate(comps):
                L.append(f"        val Unit{c.upper()} = {V}({', '.join(lit(1 if j == k else 0) for j in range(n))})")
            if n == 3 and t in "fdi":
                for name, v in (("Up", (0, 1, 0)), ("Down", (0, -1, 0)), ("Right", (1, 0, 0)), ("Left", (-1, 0, 0)),
                                ("Forward", (0, 0, -1)), ("Back", (0, 0, 1))):
                    L.append(f"        val {name} = {V}({', '.join(lit(x) for x in v)})")
            L.append("    }")
        L.append("}")
        if t == "u":
            L.append(f"/** A {V} from Ints, as their bits: `{V}(1, 2{', 3' if n > 2 else ''}{', 4' if n > 3 else ''})`. */")
            L.append(f"fun {V}({', '.join(f'{c}: Int' for c in comps)}) = {V}({', '.join(f'{c}.toUInt()' for c in comps)})")
        if t != "b":
            for name, op in (("plus", "+"), ("minus", "-"), ("times", "*"), ("div", "/")):
                L.append(f"operator fun {s}.{name}(v: {V}) = {V}({', '.join(f'this {op} v.{c}' for c in comps)})")
        L.append("")
    emit(f"{KT_DIR}/Vectors.kt", "\n".join(L))
    S = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>", '@file:Suppress("unused")', "", "package koral", "",
         "// Every read swizzle, as C++'s v.ZYX(): v.zyx.", ""]
    for t, n in VECS:
        for sw in swizzles(n):
            S.append(f"val {vec_name(t, n)}.{sw}: {vec_name(t, len(sw))} get() = {vec_name(t, len(sw))}({', '.join(sw)})")
        S.append("")
    emit(f"{KT_DIR}/Swizzles.kt", "\n".join(S))


def kt_matrices():
    L = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>", '@file:Suppress("unused")', "", "package koral", ""]
    for t, c, r in MATS:
        M, s, Col, Row, arr = mat_name(t, c, r), KT_SCALAR[t], vec_name(t, r), vec_name(t, c), KT_ARRAY[t]
        lit = lambda v: literal(v, t, "kt")
        size = c * r
        L.append(f"/**")
        L.append(f" * kor::{M}: {c} columns of {r} rows, column after column (`m[column * {r} + row]`): `m[c]` is a column and `m[c, r]` an")
        L.append(f" * element. Immutable; `{M}()` has ones on its diagonal, as C++'s.")
        L.append(f" */")
        L.append(f"class {M}(values: {arr}) {{")
        L.append(f"    init {{ require(values.size == {size}) {{ \"a {M} is {size} values\" }} }}")
        L.append("    private val m = values.copyOf()")
        L.append("")
        L.append(f"    constructor() : this({lit(1)})")
        L.append(f"    /** [diagonal] on the diagonal, zero elsewhere. */")
        L.append(f"    constructor(diagonal: {s}) : this({arr}({size}) {{ if (it / {r} == it % {r}) diagonal else {lit(0)} }})")
        L.append(f"    constructor({', '.join(f'c{k}: {Col}' for k in range(c))}) : this({' + '.join(f'c{k}.toArray()' for k in range(c))})")
        for t2, c2, r2 in MATS:
            if (t2, c2, r2) == (t, c, r) or not (t2 == t or (c2, r2) == (c, r)):
                continue
            conv = "" if t2 == t else (".toFloat()" if t == "f" else ".toDouble()")
            L.append(f"    /** The overlap of a {mat_name(t2, c2, r2)}; the rest is the identity's. */" if (c2, r2) != (c, r) else
                     f"    /** A {mat_name(t2, c2, r2)} converted. */")
            L.append(f"    constructor(o: {mat_name(t2, c2, r2)}) : this({arr}({size}) {{ val cc = it / {r}; val rr = it % {r}; "
                     f"if (cc < {c2} && rr < {r2}) o[cc, rr]{conv} else if (cc == rr) {lit(1)} else {lit(0)} }})")
        L.append("")
        L.append(f"    operator fun get(column: Int, row: Int): {s} = m[column * {r} + row]")
        L.append(f"    operator fun get(column: Int): {Col} = {Col}({', '.join(f'm[column * {r} + {k}]' for k in range(r))})")
        L.append(f"    fun row(r: Int) = {Row}({', '.join(f'm[{k * r} + r]' for k in range(c))})")
        L.append(f"    /** The {size} values, column after column. */")
        L.append(f"    fun toArray(): {arr} = m.copyOf()")
        L.append(f"    /** A copy with one element changed. */")
        L.append(f"    fun with(column: Int, row: Int, value: {s}) = {M}(m.copyOf().also {{ it[column * {r} + row] = value }})")
        L.append(f"    /** A copy with one column replaced. */")
        L.append(f"    fun withColumn(column: Int, value: {Col}) = {M}(m.copyOf().also {{ value.toArray().copyInto(it, column * {r}) }})")
        L.append("")
        for k in (2, 3, 4):
            L.append(f"    operator fun times(o: {mat_name(t, k, c)}) = {mat_name(t, k, r)}({', '.join(f'this * o[{j}]' for j in range(k))})")
        L.append(f"    /** Matrix times column vector, C++'s order. */")
        L.append(f"    operator fun times(v: {Row}): {Col} = {' + '.join(f'this[{k}] * v.{XYZW[k]}' for k in range(c))}")
        L.append(f"    operator fun times(s: {s}) = {M}({arr}({size}) {{ m[it] * s }})")
        L.append(f"    operator fun div(s: {s}) = {M}({arr}({size}) {{ m[it] / s }})")
        L.append(f"    operator fun plus(o: {M}) = {M}({arr}({size}) {{ m[it] + o.m[it] }})")
        L.append(f"    operator fun minus(o: {M}) = {M}({arr}({size}) {{ m[it] - o.m[it] }})")
        L.append(f"    operator fun unaryMinus() = {M}({arr}({size}) {{ -m[it] }})")
        L.append("")
        L.append(f"    override fun equals(other: Any?) = other is {M} && m.contentEquals(other.m)")
        L.append("    override fun hashCode() = m.contentHashCode()")
        L.append(f"    override fun toString() = (0 until {r}).joinToString(\"; \", \"[\", \"]\") {{ row(it).toString() }}")
        L.append("")
        L.append("    companion object {")
        if c == r:
            L.append(f"        val Identity = {M}()")
        if (t, c, r) == ("f", 4, 4):
            L.append("        // The Kotlin bindings' earlier names, kept: the top-level functions are kmath's.")
            L.append("        fun translation(by: Vec3) = koral.translation(by)")
            L.append("        fun scale(by: Vec3) = scaling(by)")
            L.append("        fun rotation(radians: Float, axis: Vec3) = koral.rotation(radians, axis)")
            L.append("        fun perspective(fovYRadians: Float, aspect: Float, near: Float, far: Float) = koral.perspective(fovYRadians, aspect, near, far)")
            L.append("        fun lookAt(eye: Vec3, center: Vec3, up: Vec3 = Vec3.Up) = koral.lookAt(eye, center, up)")
        L.append(f"        val Zero = {M}({lit(0)})")
        L.append("    }")
        L.append("}")
        L.append(f"/** Row vector times matrix: the same as transpose(m) * v. */")
        L.append(f"operator fun {Col}.times(m: {M}) = {Row}({', '.join(f'dot(this, m[{k}])' for k in range(c))})")
        L.append(f"operator fun {s}.times(m: {M}) = m * this")
        if c != r:
            pass
        L.append("")
    for t in "fd":
        for n in (2, 3, 4):
            L.append(f"typealias {MAT_PREFIX[t]}Mat{n}x{n} = {mat_name(t, n, n)}")
    emit(f"{KT_DIR}/Matrices.kt", "\n".join(L) + "\n")


# ---- Euler angles by name (kmath/euler.h): wrappers of EulerAngles(order, ...) -------------------------------

EULER2 = ["XY", "XZ", "YX", "YZ", "ZX", "ZY"]
EULER3 = ["XYZ", "XZY", "YXZ", "YZX", "ZXY", "ZYX", "XYX", "XZX", "YXY", "YZY", "ZXZ", "ZYZ"]
AXIS = {"X": 0, "Y": 1, "Z": 2}


def euler_c():
    decl, impl = [], []
    for o in EULER2:
        sig = f"KoralMat4 koral_euler_angle_{o.lower()}(float first, float second)"
        decl.append(f"KORAL_API {sig};")
        impl.append(f"{sig} {{ return C(kor::EulerAngle{o}(first, second)); }}")
    for o in EULER3:
        sig = f"KoralMat4 koral_euler_angle_{o.lower()}(float first, float second, float third)"
        decl.append(f"KORAL_API {sig};")
        impl.append(f"{sig} {{ return C(kor::EulerAngle{o}(first, second, third)); }}")
        sig = f"KoralVec3 koral_extract_euler_angle_{o.lower()}(KoralMat4 m)"
        decl.append(f"KORAL_API {sig};")
        impl.append(f"{sig} {{ return C(kor::ExtractEulerAngle{o}(K(m))); }}")
    return decl, impl


def euler_managed(lang):
    L = []
    cs = lang == "cs"
    for o in EULER2:
        a, b = AXIS[o[0]], AXIS[o[1]]
        if cs:
            L.append(f"    public static Mat4 EulerAngle{o}(float first, float second) => AxisRotation({a}, first) * AxisRotation({b}, second);")
        else:
            L.append(f"fun eulerAngle{o}(first: Float, second: Float): Mat4 = axisRotation({a}, first) * axisRotation({b}, second)")
    for o in EULER3:
        if cs:
            L.append(f"    public static Mat4 EulerAngle{o}(float first, float second, float third) => EulerAngles(EulerOrder.{o}, new Vec3(first, second, third));")
            L.append(f"    public static Vec3 ExtractEulerAngle{o}(Mat4 m) => ExtractEulerAngles(EulerOrder.{o}, m);")
        else:
            L.append(f"fun eulerAngle{o}(first: Float, second: Float, third: Float): Mat4 = eulerAngles(EulerOrder.{o}, Vec3(first, second, third))")
            L.append(f"fun extractEulerAngle{o}(m: Mat4): Vec3 = extractEulerAngles(EulerOrder.{o}, m)")
    return L


# ---- parity tests: every generated C# and Kotlin function against its C export ---------------------------------

INEXACT = {"Sin", "Cos", "Tan", "Asin", "Acos", "Atan", "Atan2", "Sinh", "Cosh", "Tanh", "Asinh", "Acosh", "Atanh", "Pow", "Exp", "Log",
           "Exp2", "Log2", "Angle", "OrientedAngle", "Polar", "Euclidean", "Rotate", "RotateX", "RotateY", "RotateZ", "LxNorm"}
CHAPTERS = []
for _inst in INSTANCES:
    if _inst.fn.chapter not in CHAPTERS:
        CHAPTERS.append(_inst.fn.chapter)


def cs_parity():
    L = [HEADER_CS, "#nullable enable", "using Koral.Tests.Native;", "", "namespace Koral.Tests;", "",
         "// Every function of kmath's GLSL chapters, C# against the C export of the C++ template, on random arguments:",
         "// bit for bit, except what goes through the platform's sin, pow and friends (to a relative 1e-4).",
         "public static unsafe partial class Cases", "{",
         "    private static readonly Random ParityRandom = new(2024);",
         "    private static float PF() => ParityRandom.NextFloat(-4f, 4f);",
         "    private static double PD() => ParityRandom.NextFloat(-4f, 4f) + ParityRandom.NextDouble() * 1e-3;",
         "    private static int PI() { int v = ParityRandom.NextInt(1, 100); return ParityRandom.NextBool() ? v : -v; }",
         "    private static uint PU() => (uint)ParityRandom.NextInt(1, 200);",
         "    private static bool PB() => ParityRandom.NextBool();",
         "    private static int PSmall() => ParityRandom.NextInt(0, 16);",
         "    private static ushort PH() => (ushort)ParityRandom.NextU32();",
         "    private static bool PSame(float a, float b, bool exact) => BitConverter.SingleToInt32Bits(a) == BitConverter.SingleToInt32Bits(b) || (float.IsNaN(a) && float.IsNaN(b))",
         "        || (!exact && MathF.Abs(a - b) <= 1e-4f * MathF.Max(1f, MathF.Abs(a)));",
         "    private static bool PSame(double a, double b, bool exact) => BitConverter.DoubleToInt64Bits(a) == BitConverter.DoubleToInt64Bits(b) || (double.IsNaN(a) && double.IsNaN(b))",
         "        || (!exact && Math.Abs(a - b) <= 1e-9 * Math.Max(1.0, Math.Abs(a)));",
         "    private static bool PSame(int a, int b, bool exact) => a == b;",
         "    private static bool PSame(uint a, uint b, bool exact) => a == b;",
         "    private static bool PSame(ushort a, ushort b, bool exact) => a == b;",
         "    private static bool PSame(bool a, byte b, bool exact) => (a ? 1 : 0) == b;",
         "    private static bool PSame(bool a, bool b, bool exact) => a == b;"]
    for t, n in VECS:
        V = vec_name(t, n)
        L.append(f"    private static bool PSame({V} a, {V} b, bool exact) => {' && '.join(f'PSame(a.{c.upper()}, b.{c.upper()}, exact)' for c in XYZW[:n])};")
    for t, c, r in MATS:
        M = mat_name(t, c, r)
        L.append(f"    private static bool PSame({M} a, {M} b, bool exact) => {' && '.join(f'PSame(a.C{k}, b.C{k}, exact)' for k in range(c))};")
    gen = {"f": "PF()", "d": "PD()", "i": "PI()", "u": "PU()", "b": "PB()", "h": "PH()"}

    def value(ty, small=False):
        if len(ty) == 1:
            return "PSmall()" if small else gen[ty[0]]
        return f"new {type_name('cs', ty)}({', '.join(gen[ty[0]] for _ in range(ty[1]))})"
    for ci, chapter in enumerate(CHAPTERS):
        L += ["", f"    public static void MathGlsl{ci}MatchesNative()   // {chapter}", "    {",
              "        for (int iteration = 0; iteration < 40; ++iteration)", "        {"]
        for inst in INSTANCES:
            if inst.fn.chapter != chapter or not inst.fn.c:
                continue
            exact = "false" if inst.fn.name in INEXACT else "true"
            name = c_name(inst)
            L.append("            {")
            margs, nargs, checks = [], [], []
            for k, p in enumerate(inst.params):
                small = p.ty == ("i",) and inst.fn.name.startswith("Bitfield")
                if p.mode == "out":
                    margs.append(f"out var mo{k}")
                    L.append(f"                {type_name('cs', p.ty)} no{k};")
                    nargs.append(f"&no{k}")
                    checks.append(f"PSame(mo{k}, no{k}, {exact})")
                elif p.mode == "ref":
                    L.append(f"                var a{k} = {value(p.ty)};")
                    L.append(f"                var mo{k} = a{k}; var no{k} = a{k};")
                    margs.append(f"ref mo{k}")
                    nargs.append(f"&no{k}")
                    checks.append(f"PSame(mo{k}, no{k}, {exact})")
                else:
                    if p.default == "Epsilon" or (inst.fn.name in ("ApproxEqual", "EpsilonEqual", "EpsilonNotEqual") and p.name == "epsilon"):
                        L.append(f"                var a{k} = {literal(0.5, p.ty[0], 'cs')};")
                    elif p.default == "inf":
                        L.append(f"                var a{k} = {type_name('cs', p.ty)}.PositiveInfinity;")
                    else:
                        L.append(f"                var a{k} = {value(p.ty, small)};")
                    margs.append(f"a{k}")
                    nargs.append(f"(byte)(a{k} ? 1 : 0)" if p.ty == ("b",) else f"a{k}")
            if inst.ret:
                L.append(f"                var m = KMath.{inst.fn.name}({', '.join(margs)});")
                L.append(f"                var n = KoralMathNative.{name}({', '.join(nargs)});")
                checks.insert(0, f"PSame(m, n, {exact})")
            else:
                L.append(f"                KMath.{inst.fn.name}({', '.join(margs)});")
                L.append(f"                KoralMathNative.{name}({', '.join(nargs)});")
            L.append(f"                Check.That({' && '.join(checks)}, \"{name}\");")
            L.append("            }")
        L += ["        }", "    }"]
    L.append("}")
    emit("bindings/csharp/tests/Koral.Tests/Generated/GlslParity.g.cs", "\n".join(L) + "\n")


KT_LAYOUT = {"f": "JAVA_FLOAT", "d": "JAVA_DOUBLE", "i": "JAVA_INT", "u": "JAVA_INT", "b": "JAVA_BOOLEAN"}
KT_SIZE = {"f": 4, "d": 8, "i": 4, "u": 4, "b": 1}


def kt_parity():
    L = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>",
         '@file:Suppress("UNUSED_VARIABLE", "NAME_SHADOWING")', "", "package koral.tests", "",
         "import java.lang.foreign.Arena", "import java.lang.foreign.MemorySegment", "import java.lang.foreign.ValueLayout.*",
         "import koral.*", "import koral.interop.KoralMathLayouts", "import koral.interop.KoralMathNative", "import kotlin.test.Test",
         "import kotlin.test.assertTrue", "",
         "// Every function of kmath's GLSL chapters, Kotlin against the C export of the C++ template, on random arguments: bit",
         "// for bit, except what goes through the platform's sin, pow and friends (to a relative 1e-4). The scalar ones",
         "// kotlin.math already has (sin, floor, min, ...) are its, not Koral's, and not checked here.",
         "class GlslParityTest {",
         "    private val a = Arena.ofAuto()",
         "    private val r = Random(2024uL)",
         "    private var failures = mutableListOf<String>()",
         "    private fun check(ok: Boolean, what: String) { if (!ok && failures.size < 50) failures += what }",
         "    private fun pf() = r.nextFloat(-4f, 4f)",
         "    private fun pd() = r.nextFloat(-4f, 4f).toDouble() + r.nextDouble() * 1e-3",
         "    private fun pi(): Int { val v = r.nextInt(1, 100); return if (r.nextBool()) v else -v }",
         "    private fun pu() = r.nextInt(1, 200).toUInt()",
         "    private fun pb() = r.nextBool()",
         "    private fun psmall() = r.nextInt(0, 16)",
         "    private fun ph() = r.nextU32().toUShort()",
         "    private fun same(x: Float, y: Float, exact: Boolean) = x.toRawBits() == y.toRawBits() || (x.isNaN() && y.isNaN())",
         "        || (!exact && kotlin.math.abs(x - y) <= 1e-4f * kotlin.math.max(1f, kotlin.math.abs(x)))",
         "    private fun same(x: Double, y: Double, exact: Boolean) = x.toRawBits() == y.toRawBits() || (x.isNaN() && y.isNaN())",
         "        || (!exact && kotlin.math.abs(x - y) <= 1e-9 * kotlin.math.max(1.0, kotlin.math.abs(x)))",
         "    private fun same(x: Int, y: Int, exact: Boolean) = x == y",
         "    private fun same(x: UInt, y: Int, exact: Boolean) = x.toInt() == y",
         "    private fun same(x: UInt, y: UInt, exact: Boolean) = x == y",
         "    private fun same(x: UShort, y: Short, exact: Boolean) = x.toShort() == y",
         "    private fun same(x: Boolean, y: Boolean, exact: Boolean) = x == y"]
    for t, n in VECS:
        V, lay = vec_name(t, n), KT_LAYOUT[t]
        L.append(f"    private fun same(x: {V}, y: {V}, exact: Boolean) = {' && '.join(f'same(x.{c}, y.{c}, exact)' for c in XYZW[:n])}")
        put = "".join(f"s.set({lay}, {KT_SIZE[t] * k}L, v.{c}{'.toInt()' if t == 'u' else ''}); " for k, c in enumerate(XYZW[:n]))
        L.append(f"    private fun seg(v: {V}): MemorySegment {{ val s = a.allocate(KoralMathLayouts.Koral{V}); {put}return s }}")
        get = ", ".join(f"s.get({lay}, {KT_SIZE[t] * k}L){'.toUInt()' if t == 'u' else ''}" for k in range(n))
        L.append(f"    private fun r{V}(s: MemorySegment) = {V}({get})")
    for t, c, rr in MATS:
        M, lay = mat_name(t, c, rr), KT_LAYOUT[t]
        arr = "FloatArray" if t == "f" else "DoubleArray"
        L.append(f"    private fun same(x: {M}, y: {M}, exact: Boolean) = (0 until {c}).all {{ same(x[it], y[it], exact) }}")
        L.append(f"    private fun seg(v: {M}): MemorySegment = a.allocateFrom({lay}, *v.toArray())")
        L.append(f"    private fun r{M}(s: MemorySegment) = {M}(s.asSlice(0, {c * rr * KT_SIZE[t]}L).toArray({lay}))")

    def value(ty, small=False):
        gen = {"f": "pf()", "d": "pd()", "i": "pi()", "u": "pu()", "b": "pb()", "h": "ph()"}
        if len(ty) == 1:
            return "psmall()" if small else gen[ty[0]]
        return f"{type_name('kt', ty)}({', '.join(gen[ty[0]] for _ in range(ty[1]))})"

    def to_native(ty, expr):
        if len(ty) > 1:
            return f"seg({expr})"
        return {"u": f"{expr}.toInt()", "h": f"{expr}.toShort()"}.get(ty[0], expr)

    def from_native(ty, expr):
        return f"r{type_name('kt', ty)}({expr})" if len(ty) > 1 else expr

    def layout(ty):
        return f"KoralMathLayouts.{type_name('c', ty)}" if len(ty) > 1 else {"f": "JAVA_FLOAT", "d": "JAVA_DOUBLE", "i": "JAVA_INT", "u": "JAVA_INT"}[ty[0]]

    def read_out(ty, seg):
        if len(ty) > 1:
            return f"r{type_name('kt', ty)}({seg})"
        return f"{seg}.get({layout(ty)}, 0L){'.toUInt()' if ty[0] == 'u' else ''}"

    bodies, tests = [], {}
    for k_inst, inst in enumerate(INSTANCES):
        if not inst.fn.c:
            continue
        name = lower_camel(inst.fn.name)
        scalar_only = all(len(p.ty) == 1 for p in inst.params) and (not inst.ret or len(inst.ret) == 1)
        if scalar_only and inst.t in KT_CLASH.get(name, ""):
            continue
        exact = "false" if inst.fn.name in INEXACT else "true"
        cn = c_name(inst)
        B = [f"    private fun p{k_inst}() {{"]
        margs, nargs, checks = [], [], []
        if inst.ret and len(inst.ret) > 1:
            nargs.append("a")
        for k, p in enumerate(inst.params):
            small = p.ty == ("i",) and inst.fn.name.startswith("Bitfield")
            if p.mode:
                init = value(p.ty) if p.mode == "ref" else zero_of("kt", p.ty)
                B.append(f"        val v{k} = {init}")
                B.append(f"        val mo{k} = Ref(v{k})")
                if len(p.ty) > 1:
                    B.append(f"        val no{k} = seg(v{k})")
                else:
                    B.append(f"        val no{k} = a.allocate({layout(p.ty)}).also {{ it.set({layout(p.ty)}, 0L, {to_native(p.ty, f'v{k}')}) }}")
                margs.append(f"mo{k}")
                nargs.append(f"no{k}")
                checks.append(f"same(mo{k}.value, {read_out(p.ty, f'no{k}')}, {exact})")
            else:
                if inst.fn.name in ("ApproxEqual", "EpsilonEqual", "EpsilonNotEqual") and p.name == "epsilon":
                    B.append(f"        val a{k} = {literal(0.5, p.ty[0], 'kt')}")
                elif p.default == "inf":
                    B.append(f"        val a{k} = {type_name('kt', p.ty)}.POSITIVE_INFINITY")
                else:
                    B.append(f"        val a{k} = {value(p.ty, small)}")
                margs.append(f"a{k}")
                nargs.append(to_native(p.ty, f"a{k}"))
        if inst.ret:
            B.append(f"        val m = koral.{name}({', '.join(margs)})")
            B.append(f"        val n = {from_native(inst.ret, f'KoralMathNative.{cn}({', '.join(nargs)})')}")
            checks.insert(0, f"same(m, n, {exact})")
        else:
            B.append(f"        koral.{name}({', '.join(margs)})")
            B.append(f"        KoralMathNative.{cn}({', '.join(nargs)})")
        B.append(f"        check({' && '.join(checks)}, \"{cn}\")")
        B.append("    }")
        bodies += B
        tests.setdefault(CHAPTERS.index(inst.fn.chapter), []).append(f"p{k_inst}()")
    for ci, calls in sorted(tests.items()):
        L += ["", f"    @Test", f"    fun chapter{ci}() {{   // {CHAPTERS[ci]}", "        repeat(40) {"]
        L += [f"            {c}" for c in calls]
        L += ["        }", "        assertTrue(failures.isEmpty(), failures.joinToString(\"\\n\"))", "    }"]
    L.append("")
    L += bodies
    L.append("}")
    emit("bindings/kotlin/tests/src/test/kotlin/koral/tests/GlslParityTest.kt", "\n".join(L) + "\n")


# ---- Material colours (kmath/material.h): the 2014 palette, and Material 3's scheme roles ------------------------

import json  # noqa: E402

PALETTE = json.loads((pathlib.Path(__file__).resolve().parent / "material_palette.json").read_text())
HUES = [h["name"] for h in PALETTE["hues"]]
SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
ACCENTS = ["100", "200", "400", "700"]
ROLES = ("PrimaryPaletteKeyColor SecondaryPaletteKeyColor TertiaryPaletteKeyColor NeutralPaletteKeyColor NeutralVariantPaletteKeyColor "
         "Background OnBackground Surface SurfaceDim SurfaceBright SurfaceContainerLowest SurfaceContainerLow SurfaceContainer "
         "SurfaceContainerHigh SurfaceContainerHighest OnSurface SurfaceVariant OnSurfaceVariant InverseSurface InverseOnSurface Outline "
         "OutlineVariant Shadow Scrim SurfaceTint Primary OnPrimary PrimaryContainer OnPrimaryContainer InversePrimary Secondary "
         "OnSecondary SecondaryContainer OnSecondaryContainer Tertiary OnTertiary TertiaryContainer OnTertiaryContainer Error OnError "
         "ErrorContainer OnErrorContainer PrimaryFixed PrimaryFixedDim OnPrimaryFixed OnPrimaryFixedVariant SecondaryFixed "
         "SecondaryFixedDim OnSecondaryFixed OnSecondaryFixedVariant TertiaryFixed TertiaryFixedDim OnTertiaryFixed OnTertiaryFixedVariant").split()
VARIANTS = ["TonalSpot", "Neutral", "Vibrant", "Expressive", "Fidelity", "Content", "Monochrome", "Rainbow", "FruitSalad"]


def palette_entries():
    """(name, 0xRRGGBB) of every named palette colour: Red50 ... RedA700, then Black and White."""
    for h in PALETTE["hues"]:
        for shade in SHADES:
            yield f"{h['name']}{shade}", h["shades"][shade]
        for shade, value in PALETTE["accents"].get(h["name"], {}).items():
            yield f"{h['name']}A{shade}", value
    yield "Black", "0x000000"
    yield "White", "0xFFFFFF"


def material_cpp():
    L = ["// <auto-generated> by scripts/kmath/generate.py from scripts/kmath/material_palette.json: do not edit. </auto-generated>",
         "// Included inside namespace kor by kmath/material.h: the Material Design 2014 palette.", "",
         "/// The palette's hues, in its order.",
         f"enum class MaterialHue : u8 {{ {', '.join('e' + h for h in HUES)} }};", "",
         "/// Every palette colour by its name in the guidelines: material::Red500, material::TealA400, ... (sRGB).",
         "namespace material {"]
    for name, value in palette_entries():
        L.append(f"    inline constexpr Vec4 {name} = ColorFromHex({value});")
    L += ["}", "", "namespace detail {", f"    inline constexpr u32 MaterialShades[{len(HUES)}][10] = {{"]
    for h in PALETTE["hues"]:
        L.append("        {" + ", ".join(h["shades"][x] for x in SHADES) + "},")
    L += ["    };", "    /// 0: the hue has no accents.", f"    inline constexpr u32 MaterialAccents[{len(HUES)}][4] = {{"]
    for h in HUES:
        acc = PALETTE["accents"].get(h)
        L.append("        {" + ", ".join(acc[x] if acc else "0" for x in ACCENTS) + "},")
    L += ["    };", "}"]
    emit("include/kmath/detail/material_palette.inl", "\n".join(L) + "\n")
    F = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>",
         "// Included inside kor::MaterialScheme: Material 3's colour roles, as Compose's ColorScheme names them."]
    F += [f"Vec4 {lower_camel(r)};" for r in ROLES]
    emit("include/kmath/detail/material_scheme.inl", "\n".join(F) + "\n")
    G = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>",
         "// Included in MaterialScheme::FromSeed: each role from Google's DynamicScheme."]
    G += [f"s.{lower_camel(r)} = FromArgb(d.Get{r}());" for r in ROLES]
    emit("src/core/math/material_scheme_fill.inl", "\n".join(G) + "\n")


def material_c_types():
    L = ["", "/* ==== Material colours (kmath/material.h) ==== */",
         "/* The 2014 palette as 0xRRGGBB (sRGB): koral_color_from_hex(KORAL_MATERIAL_RED_500). */"]
    for name, value in palette_entries():
        m = re.fullmatch(r"([A-Za-z]+?)(A?\d+)?", name)
        macro = snake(m.group(1)).upper() + (f"_{m.group(2)}" if m.group(2) else "")
        L.append(f"#define KORAL_MATERIAL_{macro} {value}u")
    L.append("typedef enum KoralMaterialHue { " + ", ".join(f"KORAL_MATERIAL_HUE_{snake(h).upper()}" + (" = 0" if i == 0 else "") for i, h in enumerate(HUES)) + " } KoralMaterialHue;")
    L.append("typedef enum KoralSchemeVariant { " + ", ".join(f"KORAL_SCHEME_{snake(v).upper()}" + (" = 0" if i == 0 else "") for i, v in enumerate(VARIANTS)) + " } KoralSchemeVariant;")
    L.append("/** kor::Hct: hue in degrees, chroma, tone 0 (black) to 100 (white). */")
    L.append("typedef struct KoralHct { float hue, chroma, tone; } KoralHct;")
    L.append("/** kor::TonalPalette. */")
    L.append("typedef struct KoralTonalPalette { float hue, chroma; } KoralTonalPalette;")
    L.append("/** kor::MaterialScheme: every Material 3 colour role, sRGB. */")
    L.append("typedef struct KoralMaterialScheme {")
    L += [f"    KoralVec4 {snake(r)};" for r in ROLES]
    L.append("} KoralMaterialScheme;")
    return L


def material_managed(lang):
    cs = lang == "cs"
    if cs:
        L = [HEADER_CS, "namespace Koral;", "",
             "/// <summary>kor::MaterialHue: the hues of the Material Design 2014 palette.</summary>",
             f"public enum MaterialHue : byte {{ {', '.join(HUES)} }}", "",
             "/// <summary>kor::SchemeVariant: how a Material 3 scheme spreads its seed over its palettes.</summary>",
             f"public enum SchemeVariant : byte {{ {', '.join(VARIANTS)} }}", "",
             "/// <summary>Every colour of the Material Design 2014 palette by its name in the guidelines (C++'s kor::material::), sRGB.</summary>",
             "public static class MaterialColors", "{"]
        for name, value in palette_entries():
            L.append(f"    public static readonly Vec4 {name} = KMath.ColorFromHex({value});")
        L += ["}", "", "/// <summary>kor::MaterialScheme: every Material 3 colour role, sRGB; laid out as the C struct.</summary>",
              "[System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]",
              "public partial struct MaterialScheme", "{"]
        L += [f"    public Vec4 {r};" for r in ROLES]
        L += ["}", "", "public static partial class KMath", "{",
              f"    private static readonly uint[,] MaterialShades = {{ {', '.join('{' + ', '.join(h['shades'][x] for x in SHADES) + '}' for h in PALETTE['hues'])} }};",
              f"    private static readonly uint[,] MaterialAccents = {{ {', '.join('{' + ', '.join((PALETTE['accents'].get(h) or {}).get(x, '0') for x in ACCENTS) + '}' for h in HUES)} }};",
              "    private static int NearestShade(int[] shades, int shade)",
              "    {",
              "        int best = 0;",
              "        for (int i = 1; i < shades.Length; ++i) if (Math.Abs(shades[i] - shade) < Math.Abs(shades[best] - shade)) best = i;",
              "        return best;",
              "    }",
              f"    private static readonly int[] ShadeNumbers = [{', '.join(SHADES)}], AccentNumbers = [{', '.join(ACCENTS)}];",
              "    /// <summary>A palette colour: <paramref name=\"shade\"/> 50, 100, 200, ..., 900 (another number gives the nearest).</summary>",
              "    public static Vec4 MaterialColor(MaterialHue hue, int shade = 500) => ColorFromHex(MaterialShades[(int)hue, NearestShade(ShadeNumbers, shade)]);",
              "    /// <summary>An accent, A100 to A700; brown, grey and blue grey have none, and give their plain shade of the number.</summary>",
              "    public static Vec4 MaterialAccent(MaterialHue hue, int shade = 200)",
              "    {",
              "        int i = NearestShade(AccentNumbers, shade);",
              "        uint accent = MaterialAccents[(int)hue, i];",
              "        return accent != 0 ? ColorFromHex(accent) : MaterialColor(hue, AccentNumbers[i]);",
              "    }", "}"]
        emit(f"{CS_DIR}/Material.g.cs", "\n".join(L) + "\n")
        return
    L = ["// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>", '@file:Suppress("unused")', "", "package koral", "",
         "import java.lang.foreign.MemorySegment", "import java.lang.foreign.ValueLayout.JAVA_FLOAT", "",
         "/** kor::MaterialHue: the hues of the Material Design 2014 palette. */",
         f"enum class MaterialHue {{ {', '.join(HUES)} }}", "",
         "/** kor::SchemeVariant: how a Material 3 scheme spreads its seed over its palettes. */",
         f"enum class SchemeVariant {{ {', '.join(VARIANTS)} }}", "",
         "/** Every colour of the Material Design 2014 palette by its name in the guidelines (C++'s kor::material::), sRGB. */",
         "object MaterialColors {"]
    for name, value in palette_entries():
        L.append(f"    val {name} = colorFromHex({value}u)")
    L += ["}", "", "/** kor::MaterialScheme: every Material 3 colour role, sRGB. */", "data class MaterialScheme("]
    L += [f"    val {lower_camel(r)}: Vec4," for r in ROLES]
    L += [") {", "    companion object {", "        /** Read from C's KoralMaterialScheme. */", "        internal fun read(s: MemorySegment): MaterialScheme {",
          "            fun v(i: Int) = Vec4(s.get(JAVA_FLOAT, i * 16L), s.get(JAVA_FLOAT, i * 16L + 4), s.get(JAVA_FLOAT, i * 16L + 8), s.get(JAVA_FLOAT, i * 16L + 12))",
          f"            return MaterialScheme({', '.join(f'v({i})' for i in range(len(ROLES)))})", "        }", "    }", "}", "",
          f"private val materialShades = arrayOf({', '.join('uintArrayOf(' + ', '.join(h['shades'][x] + 'u' for x in SHADES) + ')' for h in PALETTE['hues'])})",
          f"private val materialAccents = arrayOf({', '.join('uintArrayOf(' + ', '.join((PALETTE['accents'].get(h) or {}).get(x, '0') + 'u' for x in ACCENTS) + ')' for h in HUES)})",
          f"private val shadeNumbers = intArrayOf({', '.join(SHADES)})",
          f"private val accentNumbers = intArrayOf({', '.join(ACCENTS)})",
          "private fun nearestShade(shades: IntArray, shade: Int) = shades.indices.minBy { kotlin.math.abs(shades[it] - shade) }",
          "/** A palette colour: [shade] 50, 100, 200, ..., 900 (another number gives the nearest). */",
          "fun materialColor(hue: MaterialHue, shade: Int = 500) = colorFromHex(materialShades[hue.ordinal][nearestShade(shadeNumbers, shade)])",
          "/** An accent, A100 to A700; brown, grey and blue grey have none, and give their plain shade of the number. */",
          "fun materialAccent(hue: MaterialHue, shade: Int = 200): Vec4 {",
          "    val i = nearestShade(accentNumbers, shade)",
          "    val accent = materialAccents[hue.ordinal][i]",
          "    return if (accent != 0u) colorFromHex(accent) else materialColor(hue, accentNumbers[i])",
          "}"]
    emit(f"{KT_DIR}/MaterialPalette.kt", "\n".join(L) + "\n")


# ---- main ---------------------------------------------------------------------------------------------------

cpp_swizzles()
check_c_names()
splice_header()
emit("src/core/capi/math_glsl.cpp", c_source())
cs_vectors()
cs_matrices()
cs_functions()
kt_vectors()
kt_matrices()
kt_functions()
material_cpp()
material_managed('cs')
material_managed('kt')
cs_parity()
kt_parity()

if __name__ == "__main__":
    stale = False
    for path, text in OUT.items():
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != text:
                print(f"{path.relative_to(ROOT)} is stale: run scripts/kmath/generate.py")
                stale = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_text() != text:
                path.write_text(text)
                print(f"wrote {path.relative_to(ROOT)}")
    if "--check" in sys.argv:
        sys.exit(1 if stale else 0)
