# Writes ICONS_OUTPUT, a C++ source holding every SVG under ICONS_DIR/<style>/<name>.svg as text, so the
# Material icons are in the library itself: nothing to find at runtime, nothing to ship beside it.
#   cmake -DICONS_DIR=<dir> -DICONS_OUTPUT=<file.cpp> -P EmbedIcons.cmake

file(GLOB ICON_FILES RELATIVE ${ICONS_DIR} ${ICONS_DIR}/*/*.svg)
list(SORT ICON_FILES)

set(ENTRIES "")
foreach(ICON ${ICON_FILES})
    get_filename_component(STYLE ${ICON} DIRECTORY)
    get_filename_component(NAME ${ICON} NAME_WE)
    file(READ ${ICONS_DIR}/${ICON} SVG)
    string(STRIP "${SVG}" SVG)
    # What is never drawn left out — the files stay as Google publishes them, the library a quarter smaller:
    # the invisible 24 by 24 boxes that keep an icon's size in an editor, and the <svg> tag's all but its viewBox.
    string(REGEX REPLACE "<(path|rect) [^>]*fill=\"none\"[^>]*/>" "" SVG "${SVG}")
    string(REGEX MATCH "viewBox=\"[^\"]*\"" VIEW_BOX "${SVG}")
    string(REGEX REPLACE "^<svg [^>]*>" "<svg ${VIEW_BOX}>" SVG "${SVG}")
    string(APPEND ENTRIES "        { \"${STYLE}\"sv, \"${NAME}\"sv, R\"svg(${SVG})svg\"sv },\n")
endforeach()

set(CONTENT "// Generated by cmake/EmbedIcons.cmake from ${ICONS_DIR}: do not edit.

#include \"materialIcons.h\"

namespace kui::detail
{
    namespace {
        // Literals that carry their lengths: measuring megabytes of them at compile time is past what compilers allow.
        using namespace std::string_view_literals;
        constexpr EmbeddedIcon icons[] = {
${ENTRIES}        };
    }

    std::span<const EmbeddedIcon> MaterialIconData() { return icons; }
}
")

# Only written when it changed, so the library is not rebuilt for nothing.
if(EXISTS ${ICONS_OUTPUT})
    file(READ ${ICONS_OUTPUT} OLD)
endif()
if(NOT "${OLD}" STREQUAL "${CONTENT}")
    file(WRITE ${ICONS_OUTPUT} "${CONTENT}")
endif()
