// <auto-generated> by scripts/kmath/generate.py from scripts/kmath/material_palette.json: do not edit. </auto-generated>
// Included inside namespace kor by kmath/material.h: the Material Design 2014 palette.

/// The palette's hues, in its order.
enum class MaterialHue : u8 { eRed, ePink, ePurple, eDeepPurple, eIndigo, eBlue, eLightBlue, eCyan, eTeal, eGreen, eLightGreen, eLime, eYellow, eAmber, eOrange, eDeepOrange, eBrown, eGrey, eBlueGrey };

/// Every palette colour by its name in the guidelines: material::Red500, material::TealA400, ... (sRGB).
namespace material {
    inline constexpr Vec4 Red50 = ColorFromHex(0xFFEBEE);
    inline constexpr Vec4 Red100 = ColorFromHex(0xFFCDD2);
    inline constexpr Vec4 Red200 = ColorFromHex(0xEF9A9A);
    inline constexpr Vec4 Red300 = ColorFromHex(0xE57373);
    inline constexpr Vec4 Red400 = ColorFromHex(0xEF5350);
    inline constexpr Vec4 Red500 = ColorFromHex(0xF44336);
    inline constexpr Vec4 Red600 = ColorFromHex(0xE53935);
    inline constexpr Vec4 Red700 = ColorFromHex(0xD32F2F);
    inline constexpr Vec4 Red800 = ColorFromHex(0xC62828);
    inline constexpr Vec4 Red900 = ColorFromHex(0xB71C1C);
    inline constexpr Vec4 RedA100 = ColorFromHex(0xFF8A80);
    inline constexpr Vec4 RedA200 = ColorFromHex(0xFF5252);
    inline constexpr Vec4 RedA400 = ColorFromHex(0xFF1744);
    inline constexpr Vec4 RedA700 = ColorFromHex(0xD50000);
    inline constexpr Vec4 Pink50 = ColorFromHex(0xFCE4EC);
    inline constexpr Vec4 Pink100 = ColorFromHex(0xF8BBD0);
    inline constexpr Vec4 Pink200 = ColorFromHex(0xF48FB1);
    inline constexpr Vec4 Pink300 = ColorFromHex(0xF06292);
    inline constexpr Vec4 Pink400 = ColorFromHex(0xEC407A);
    inline constexpr Vec4 Pink500 = ColorFromHex(0xE91E63);
    inline constexpr Vec4 Pink600 = ColorFromHex(0xD81B60);
    inline constexpr Vec4 Pink700 = ColorFromHex(0xC2185B);
    inline constexpr Vec4 Pink800 = ColorFromHex(0xAD1457);
    inline constexpr Vec4 Pink900 = ColorFromHex(0x880E4F);
    inline constexpr Vec4 PinkA100 = ColorFromHex(0xFF80AB);
    inline constexpr Vec4 PinkA200 = ColorFromHex(0xFF4081);
    inline constexpr Vec4 PinkA400 = ColorFromHex(0xF50057);
    inline constexpr Vec4 PinkA700 = ColorFromHex(0xC51162);
    inline constexpr Vec4 Purple50 = ColorFromHex(0xF3E5F5);
    inline constexpr Vec4 Purple100 = ColorFromHex(0xE1BEE7);
    inline constexpr Vec4 Purple200 = ColorFromHex(0xCE93D8);
    inline constexpr Vec4 Purple300 = ColorFromHex(0xBA68C8);
    inline constexpr Vec4 Purple400 = ColorFromHex(0xAB47BC);
    inline constexpr Vec4 Purple500 = ColorFromHex(0x9C27B0);
    inline constexpr Vec4 Purple600 = ColorFromHex(0x8E24AA);
    inline constexpr Vec4 Purple700 = ColorFromHex(0x7B1FA2);
    inline constexpr Vec4 Purple800 = ColorFromHex(0x6A1B9A);
    inline constexpr Vec4 Purple900 = ColorFromHex(0x4A148C);
    inline constexpr Vec4 PurpleA100 = ColorFromHex(0xEA80FC);
    inline constexpr Vec4 PurpleA200 = ColorFromHex(0xE040FB);
    inline constexpr Vec4 PurpleA400 = ColorFromHex(0xD500F9);
    inline constexpr Vec4 PurpleA700 = ColorFromHex(0xAA00FF);
    inline constexpr Vec4 DeepPurple50 = ColorFromHex(0xEDE7F6);
    inline constexpr Vec4 DeepPurple100 = ColorFromHex(0xD1C4E9);
    inline constexpr Vec4 DeepPurple200 = ColorFromHex(0xB39DDB);
    inline constexpr Vec4 DeepPurple300 = ColorFromHex(0x9575CD);
    inline constexpr Vec4 DeepPurple400 = ColorFromHex(0x7E57C2);
    inline constexpr Vec4 DeepPurple500 = ColorFromHex(0x673AB7);
    inline constexpr Vec4 DeepPurple600 = ColorFromHex(0x5E35B1);
    inline constexpr Vec4 DeepPurple700 = ColorFromHex(0x512DA8);
    inline constexpr Vec4 DeepPurple800 = ColorFromHex(0x4527A0);
    inline constexpr Vec4 DeepPurple900 = ColorFromHex(0x311B92);
    inline constexpr Vec4 DeepPurpleA100 = ColorFromHex(0xB388FF);
    inline constexpr Vec4 DeepPurpleA200 = ColorFromHex(0x7C4DFF);
    inline constexpr Vec4 DeepPurpleA400 = ColorFromHex(0x651FFF);
    inline constexpr Vec4 DeepPurpleA700 = ColorFromHex(0x6200EA);
    inline constexpr Vec4 Indigo50 = ColorFromHex(0xE8EAF6);
    inline constexpr Vec4 Indigo100 = ColorFromHex(0xC5CAE9);
    inline constexpr Vec4 Indigo200 = ColorFromHex(0x9FA8DA);
    inline constexpr Vec4 Indigo300 = ColorFromHex(0x7986CB);
    inline constexpr Vec4 Indigo400 = ColorFromHex(0x5C6BC0);
    inline constexpr Vec4 Indigo500 = ColorFromHex(0x3F51B5);
    inline constexpr Vec4 Indigo600 = ColorFromHex(0x3949AB);
    inline constexpr Vec4 Indigo700 = ColorFromHex(0x303F9F);
    inline constexpr Vec4 Indigo800 = ColorFromHex(0x283593);
    inline constexpr Vec4 Indigo900 = ColorFromHex(0x1A237E);
    inline constexpr Vec4 IndigoA100 = ColorFromHex(0x8C9EFF);
    inline constexpr Vec4 IndigoA200 = ColorFromHex(0x536DFE);
    inline constexpr Vec4 IndigoA400 = ColorFromHex(0x3D5AFE);
    inline constexpr Vec4 IndigoA700 = ColorFromHex(0x304FFE);
    inline constexpr Vec4 Blue50 = ColorFromHex(0xE3F2FD);
    inline constexpr Vec4 Blue100 = ColorFromHex(0xBBDEFB);
    inline constexpr Vec4 Blue200 = ColorFromHex(0x90CAF9);
    inline constexpr Vec4 Blue300 = ColorFromHex(0x64B5F6);
    inline constexpr Vec4 Blue400 = ColorFromHex(0x42A5F5);
    inline constexpr Vec4 Blue500 = ColorFromHex(0x2196F3);
    inline constexpr Vec4 Blue600 = ColorFromHex(0x1E88E5);
    inline constexpr Vec4 Blue700 = ColorFromHex(0x1976D2);
    inline constexpr Vec4 Blue800 = ColorFromHex(0x1565C0);
    inline constexpr Vec4 Blue900 = ColorFromHex(0x0D47A1);
    inline constexpr Vec4 BlueA100 = ColorFromHex(0x82B1FF);
    inline constexpr Vec4 BlueA200 = ColorFromHex(0x448AFF);
    inline constexpr Vec4 BlueA400 = ColorFromHex(0x2979FF);
    inline constexpr Vec4 BlueA700 = ColorFromHex(0x2962FF);
    inline constexpr Vec4 LightBlue50 = ColorFromHex(0xE1F5FE);
    inline constexpr Vec4 LightBlue100 = ColorFromHex(0xB3E5FC);
    inline constexpr Vec4 LightBlue200 = ColorFromHex(0x81D4FA);
    inline constexpr Vec4 LightBlue300 = ColorFromHex(0x4FC3F7);
    inline constexpr Vec4 LightBlue400 = ColorFromHex(0x29B6F6);
    inline constexpr Vec4 LightBlue500 = ColorFromHex(0x03A9F4);
    inline constexpr Vec4 LightBlue600 = ColorFromHex(0x039BE5);
    inline constexpr Vec4 LightBlue700 = ColorFromHex(0x0288D1);
    inline constexpr Vec4 LightBlue800 = ColorFromHex(0x0277BD);
    inline constexpr Vec4 LightBlue900 = ColorFromHex(0x01579B);
    inline constexpr Vec4 LightBlueA100 = ColorFromHex(0x80D8FF);
    inline constexpr Vec4 LightBlueA200 = ColorFromHex(0x40C4FF);
    inline constexpr Vec4 LightBlueA400 = ColorFromHex(0x00B0FF);
    inline constexpr Vec4 LightBlueA700 = ColorFromHex(0x0091EA);
    inline constexpr Vec4 Cyan50 = ColorFromHex(0xE0F7FA);
    inline constexpr Vec4 Cyan100 = ColorFromHex(0xB2EBF2);
    inline constexpr Vec4 Cyan200 = ColorFromHex(0x80DEEA);
    inline constexpr Vec4 Cyan300 = ColorFromHex(0x4DD0E1);
    inline constexpr Vec4 Cyan400 = ColorFromHex(0x26C6DA);
    inline constexpr Vec4 Cyan500 = ColorFromHex(0x00BCD4);
    inline constexpr Vec4 Cyan600 = ColorFromHex(0x00ACC1);
    inline constexpr Vec4 Cyan700 = ColorFromHex(0x0097A7);
    inline constexpr Vec4 Cyan800 = ColorFromHex(0x00838F);
    inline constexpr Vec4 Cyan900 = ColorFromHex(0x006064);
    inline constexpr Vec4 CyanA100 = ColorFromHex(0x84FFFF);
    inline constexpr Vec4 CyanA200 = ColorFromHex(0x18FFFF);
    inline constexpr Vec4 CyanA400 = ColorFromHex(0x00E5FF);
    inline constexpr Vec4 CyanA700 = ColorFromHex(0x00B8D4);
    inline constexpr Vec4 Teal50 = ColorFromHex(0xE0F2F1);
    inline constexpr Vec4 Teal100 = ColorFromHex(0xB2DFDB);
    inline constexpr Vec4 Teal200 = ColorFromHex(0x80CBC4);
    inline constexpr Vec4 Teal300 = ColorFromHex(0x4DB6AC);
    inline constexpr Vec4 Teal400 = ColorFromHex(0x26A69A);
    inline constexpr Vec4 Teal500 = ColorFromHex(0x009688);
    inline constexpr Vec4 Teal600 = ColorFromHex(0x00897B);
    inline constexpr Vec4 Teal700 = ColorFromHex(0x00796B);
    inline constexpr Vec4 Teal800 = ColorFromHex(0x00695C);
    inline constexpr Vec4 Teal900 = ColorFromHex(0x004D40);
    inline constexpr Vec4 TealA100 = ColorFromHex(0xA7FFEB);
    inline constexpr Vec4 TealA200 = ColorFromHex(0x64FFDA);
    inline constexpr Vec4 TealA400 = ColorFromHex(0x1DE9B6);
    inline constexpr Vec4 TealA700 = ColorFromHex(0x00BFA5);
    inline constexpr Vec4 Green50 = ColorFromHex(0xE8F5E9);
    inline constexpr Vec4 Green100 = ColorFromHex(0xC8E6C9);
    inline constexpr Vec4 Green200 = ColorFromHex(0xA5D6A7);
    inline constexpr Vec4 Green300 = ColorFromHex(0x81C784);
    inline constexpr Vec4 Green400 = ColorFromHex(0x66BB6A);
    inline constexpr Vec4 Green500 = ColorFromHex(0x4CAF50);
    inline constexpr Vec4 Green600 = ColorFromHex(0x43A047);
    inline constexpr Vec4 Green700 = ColorFromHex(0x388E3C);
    inline constexpr Vec4 Green800 = ColorFromHex(0x2E7D32);
    inline constexpr Vec4 Green900 = ColorFromHex(0x1B5E20);
    inline constexpr Vec4 GreenA100 = ColorFromHex(0xB9F6CA);
    inline constexpr Vec4 GreenA200 = ColorFromHex(0x69F0AE);
    inline constexpr Vec4 GreenA400 = ColorFromHex(0x00E676);
    inline constexpr Vec4 GreenA700 = ColorFromHex(0x00C853);
    inline constexpr Vec4 LightGreen50 = ColorFromHex(0xF1F8E9);
    inline constexpr Vec4 LightGreen100 = ColorFromHex(0xDCEDC8);
    inline constexpr Vec4 LightGreen200 = ColorFromHex(0xC5E1A5);
    inline constexpr Vec4 LightGreen300 = ColorFromHex(0xAED581);
    inline constexpr Vec4 LightGreen400 = ColorFromHex(0x9CCC65);
    inline constexpr Vec4 LightGreen500 = ColorFromHex(0x8BC34A);
    inline constexpr Vec4 LightGreen600 = ColorFromHex(0x7CB342);
    inline constexpr Vec4 LightGreen700 = ColorFromHex(0x689F38);
    inline constexpr Vec4 LightGreen800 = ColorFromHex(0x558B2F);
    inline constexpr Vec4 LightGreen900 = ColorFromHex(0x33691E);
    inline constexpr Vec4 LightGreenA100 = ColorFromHex(0xCCFF90);
    inline constexpr Vec4 LightGreenA200 = ColorFromHex(0xB2FF59);
    inline constexpr Vec4 LightGreenA400 = ColorFromHex(0x76FF03);
    inline constexpr Vec4 LightGreenA700 = ColorFromHex(0x64DD17);
    inline constexpr Vec4 Lime50 = ColorFromHex(0xF9FBE7);
    inline constexpr Vec4 Lime100 = ColorFromHex(0xF0F4C3);
    inline constexpr Vec4 Lime200 = ColorFromHex(0xE6EE9C);
    inline constexpr Vec4 Lime300 = ColorFromHex(0xDCE775);
    inline constexpr Vec4 Lime400 = ColorFromHex(0xD4E157);
    inline constexpr Vec4 Lime500 = ColorFromHex(0xCDDC39);
    inline constexpr Vec4 Lime600 = ColorFromHex(0xC0CA33);
    inline constexpr Vec4 Lime700 = ColorFromHex(0xAFB42B);
    inline constexpr Vec4 Lime800 = ColorFromHex(0x9E9D24);
    inline constexpr Vec4 Lime900 = ColorFromHex(0x827717);
    inline constexpr Vec4 LimeA100 = ColorFromHex(0xF4FF81);
    inline constexpr Vec4 LimeA200 = ColorFromHex(0xEEFF41);
    inline constexpr Vec4 LimeA400 = ColorFromHex(0xC6FF00);
    inline constexpr Vec4 LimeA700 = ColorFromHex(0xAEEA00);
    inline constexpr Vec4 Yellow50 = ColorFromHex(0xFFFDE7);
    inline constexpr Vec4 Yellow100 = ColorFromHex(0xFFF9C4);
    inline constexpr Vec4 Yellow200 = ColorFromHex(0xFFF59D);
    inline constexpr Vec4 Yellow300 = ColorFromHex(0xFFF176);
    inline constexpr Vec4 Yellow400 = ColorFromHex(0xFFEE58);
    inline constexpr Vec4 Yellow500 = ColorFromHex(0xFFEB3B);
    inline constexpr Vec4 Yellow600 = ColorFromHex(0xFDD835);
    inline constexpr Vec4 Yellow700 = ColorFromHex(0xFBC02D);
    inline constexpr Vec4 Yellow800 = ColorFromHex(0xF9A825);
    inline constexpr Vec4 Yellow900 = ColorFromHex(0xF57F17);
    inline constexpr Vec4 YellowA100 = ColorFromHex(0xFFFF8D);
    inline constexpr Vec4 YellowA200 = ColorFromHex(0xFFFF00);
    inline constexpr Vec4 YellowA400 = ColorFromHex(0xFFEA00);
    inline constexpr Vec4 YellowA700 = ColorFromHex(0xFFD600);
    inline constexpr Vec4 Amber50 = ColorFromHex(0xFFF8E1);
    inline constexpr Vec4 Amber100 = ColorFromHex(0xFFECB3);
    inline constexpr Vec4 Amber200 = ColorFromHex(0xFFE082);
    inline constexpr Vec4 Amber300 = ColorFromHex(0xFFD54F);
    inline constexpr Vec4 Amber400 = ColorFromHex(0xFFCA28);
    inline constexpr Vec4 Amber500 = ColorFromHex(0xFFC107);
    inline constexpr Vec4 Amber600 = ColorFromHex(0xFFB300);
    inline constexpr Vec4 Amber700 = ColorFromHex(0xFFA000);
    inline constexpr Vec4 Amber800 = ColorFromHex(0xFF8F00);
    inline constexpr Vec4 Amber900 = ColorFromHex(0xFF6F00);
    inline constexpr Vec4 AmberA100 = ColorFromHex(0xFFE57F);
    inline constexpr Vec4 AmberA200 = ColorFromHex(0xFFD740);
    inline constexpr Vec4 AmberA400 = ColorFromHex(0xFFC400);
    inline constexpr Vec4 AmberA700 = ColorFromHex(0xFFAB00);
    inline constexpr Vec4 Orange50 = ColorFromHex(0xFFF3E0);
    inline constexpr Vec4 Orange100 = ColorFromHex(0xFFE0B2);
    inline constexpr Vec4 Orange200 = ColorFromHex(0xFFCC80);
    inline constexpr Vec4 Orange300 = ColorFromHex(0xFFB74D);
    inline constexpr Vec4 Orange400 = ColorFromHex(0xFFA726);
    inline constexpr Vec4 Orange500 = ColorFromHex(0xFF9800);
    inline constexpr Vec4 Orange600 = ColorFromHex(0xFB8C00);
    inline constexpr Vec4 Orange700 = ColorFromHex(0xF57C00);
    inline constexpr Vec4 Orange800 = ColorFromHex(0xEF6C00);
    inline constexpr Vec4 Orange900 = ColorFromHex(0xE65100);
    inline constexpr Vec4 OrangeA100 = ColorFromHex(0xFFD180);
    inline constexpr Vec4 OrangeA200 = ColorFromHex(0xFFAB40);
    inline constexpr Vec4 OrangeA400 = ColorFromHex(0xFF9100);
    inline constexpr Vec4 OrangeA700 = ColorFromHex(0xFF6D00);
    inline constexpr Vec4 DeepOrange50 = ColorFromHex(0xFBE9E7);
    inline constexpr Vec4 DeepOrange100 = ColorFromHex(0xFFCCBC);
    inline constexpr Vec4 DeepOrange200 = ColorFromHex(0xFFAB91);
    inline constexpr Vec4 DeepOrange300 = ColorFromHex(0xFF8A65);
    inline constexpr Vec4 DeepOrange400 = ColorFromHex(0xFF7043);
    inline constexpr Vec4 DeepOrange500 = ColorFromHex(0xFF5722);
    inline constexpr Vec4 DeepOrange600 = ColorFromHex(0xF4511E);
    inline constexpr Vec4 DeepOrange700 = ColorFromHex(0xE64A19);
    inline constexpr Vec4 DeepOrange800 = ColorFromHex(0xD84315);
    inline constexpr Vec4 DeepOrange900 = ColorFromHex(0xBF360C);
    inline constexpr Vec4 DeepOrangeA100 = ColorFromHex(0xFF9E80);
    inline constexpr Vec4 DeepOrangeA200 = ColorFromHex(0xFF6E40);
    inline constexpr Vec4 DeepOrangeA400 = ColorFromHex(0xFF3D00);
    inline constexpr Vec4 DeepOrangeA700 = ColorFromHex(0xDD2C00);
    inline constexpr Vec4 Brown50 = ColorFromHex(0xEFEBE9);
    inline constexpr Vec4 Brown100 = ColorFromHex(0xD7CCC8);
    inline constexpr Vec4 Brown200 = ColorFromHex(0xBCAAA4);
    inline constexpr Vec4 Brown300 = ColorFromHex(0xA1887F);
    inline constexpr Vec4 Brown400 = ColorFromHex(0x8D6E63);
    inline constexpr Vec4 Brown500 = ColorFromHex(0x795548);
    inline constexpr Vec4 Brown600 = ColorFromHex(0x6D4C41);
    inline constexpr Vec4 Brown700 = ColorFromHex(0x5D4037);
    inline constexpr Vec4 Brown800 = ColorFromHex(0x4E342E);
    inline constexpr Vec4 Brown900 = ColorFromHex(0x3E2723);
    inline constexpr Vec4 Grey50 = ColorFromHex(0xFAFAFA);
    inline constexpr Vec4 Grey100 = ColorFromHex(0xF5F5F5);
    inline constexpr Vec4 Grey200 = ColorFromHex(0xEEEEEE);
    inline constexpr Vec4 Grey300 = ColorFromHex(0xE0E0E0);
    inline constexpr Vec4 Grey400 = ColorFromHex(0xBDBDBD);
    inline constexpr Vec4 Grey500 = ColorFromHex(0x9E9E9E);
    inline constexpr Vec4 Grey600 = ColorFromHex(0x757575);
    inline constexpr Vec4 Grey700 = ColorFromHex(0x616161);
    inline constexpr Vec4 Grey800 = ColorFromHex(0x424242);
    inline constexpr Vec4 Grey900 = ColorFromHex(0x212121);
    inline constexpr Vec4 BlueGrey50 = ColorFromHex(0xECEFF1);
    inline constexpr Vec4 BlueGrey100 = ColorFromHex(0xCFD8DC);
    inline constexpr Vec4 BlueGrey200 = ColorFromHex(0xB0BEC5);
    inline constexpr Vec4 BlueGrey300 = ColorFromHex(0x90A4AE);
    inline constexpr Vec4 BlueGrey400 = ColorFromHex(0x78909C);
    inline constexpr Vec4 BlueGrey500 = ColorFromHex(0x607D8B);
    inline constexpr Vec4 BlueGrey600 = ColorFromHex(0x546E7A);
    inline constexpr Vec4 BlueGrey700 = ColorFromHex(0x455A64);
    inline constexpr Vec4 BlueGrey800 = ColorFromHex(0x37474F);
    inline constexpr Vec4 BlueGrey900 = ColorFromHex(0x263238);
    inline constexpr Vec4 Black = ColorFromHex(0x000000);
    inline constexpr Vec4 White = ColorFromHex(0xFFFFFF);
}

namespace detail {
    inline constexpr u32 MaterialShades[19][10] = {
        {0xFFEBEE, 0xFFCDD2, 0xEF9A9A, 0xE57373, 0xEF5350, 0xF44336, 0xE53935, 0xD32F2F, 0xC62828, 0xB71C1C},
        {0xFCE4EC, 0xF8BBD0, 0xF48FB1, 0xF06292, 0xEC407A, 0xE91E63, 0xD81B60, 0xC2185B, 0xAD1457, 0x880E4F},
        {0xF3E5F5, 0xE1BEE7, 0xCE93D8, 0xBA68C8, 0xAB47BC, 0x9C27B0, 0x8E24AA, 0x7B1FA2, 0x6A1B9A, 0x4A148C},
        {0xEDE7F6, 0xD1C4E9, 0xB39DDB, 0x9575CD, 0x7E57C2, 0x673AB7, 0x5E35B1, 0x512DA8, 0x4527A0, 0x311B92},
        {0xE8EAF6, 0xC5CAE9, 0x9FA8DA, 0x7986CB, 0x5C6BC0, 0x3F51B5, 0x3949AB, 0x303F9F, 0x283593, 0x1A237E},
        {0xE3F2FD, 0xBBDEFB, 0x90CAF9, 0x64B5F6, 0x42A5F5, 0x2196F3, 0x1E88E5, 0x1976D2, 0x1565C0, 0x0D47A1},
        {0xE1F5FE, 0xB3E5FC, 0x81D4FA, 0x4FC3F7, 0x29B6F6, 0x03A9F4, 0x039BE5, 0x0288D1, 0x0277BD, 0x01579B},
        {0xE0F7FA, 0xB2EBF2, 0x80DEEA, 0x4DD0E1, 0x26C6DA, 0x00BCD4, 0x00ACC1, 0x0097A7, 0x00838F, 0x006064},
        {0xE0F2F1, 0xB2DFDB, 0x80CBC4, 0x4DB6AC, 0x26A69A, 0x009688, 0x00897B, 0x00796B, 0x00695C, 0x004D40},
        {0xE8F5E9, 0xC8E6C9, 0xA5D6A7, 0x81C784, 0x66BB6A, 0x4CAF50, 0x43A047, 0x388E3C, 0x2E7D32, 0x1B5E20},
        {0xF1F8E9, 0xDCEDC8, 0xC5E1A5, 0xAED581, 0x9CCC65, 0x8BC34A, 0x7CB342, 0x689F38, 0x558B2F, 0x33691E},
        {0xF9FBE7, 0xF0F4C3, 0xE6EE9C, 0xDCE775, 0xD4E157, 0xCDDC39, 0xC0CA33, 0xAFB42B, 0x9E9D24, 0x827717},
        {0xFFFDE7, 0xFFF9C4, 0xFFF59D, 0xFFF176, 0xFFEE58, 0xFFEB3B, 0xFDD835, 0xFBC02D, 0xF9A825, 0xF57F17},
        {0xFFF8E1, 0xFFECB3, 0xFFE082, 0xFFD54F, 0xFFCA28, 0xFFC107, 0xFFB300, 0xFFA000, 0xFF8F00, 0xFF6F00},
        {0xFFF3E0, 0xFFE0B2, 0xFFCC80, 0xFFB74D, 0xFFA726, 0xFF9800, 0xFB8C00, 0xF57C00, 0xEF6C00, 0xE65100},
        {0xFBE9E7, 0xFFCCBC, 0xFFAB91, 0xFF8A65, 0xFF7043, 0xFF5722, 0xF4511E, 0xE64A19, 0xD84315, 0xBF360C},
        {0xEFEBE9, 0xD7CCC8, 0xBCAAA4, 0xA1887F, 0x8D6E63, 0x795548, 0x6D4C41, 0x5D4037, 0x4E342E, 0x3E2723},
        {0xFAFAFA, 0xF5F5F5, 0xEEEEEE, 0xE0E0E0, 0xBDBDBD, 0x9E9E9E, 0x757575, 0x616161, 0x424242, 0x212121},
        {0xECEFF1, 0xCFD8DC, 0xB0BEC5, 0x90A4AE, 0x78909C, 0x607D8B, 0x546E7A, 0x455A64, 0x37474F, 0x263238},
    };
    /// 0: the hue has no accents.
    inline constexpr u32 MaterialAccents[19][4] = {
        {0xFF8A80, 0xFF5252, 0xFF1744, 0xD50000},
        {0xFF80AB, 0xFF4081, 0xF50057, 0xC51162},
        {0xEA80FC, 0xE040FB, 0xD500F9, 0xAA00FF},
        {0xB388FF, 0x7C4DFF, 0x651FFF, 0x6200EA},
        {0x8C9EFF, 0x536DFE, 0x3D5AFE, 0x304FFE},
        {0x82B1FF, 0x448AFF, 0x2979FF, 0x2962FF},
        {0x80D8FF, 0x40C4FF, 0x00B0FF, 0x0091EA},
        {0x84FFFF, 0x18FFFF, 0x00E5FF, 0x00B8D4},
        {0xA7FFEB, 0x64FFDA, 0x1DE9B6, 0x00BFA5},
        {0xB9F6CA, 0x69F0AE, 0x00E676, 0x00C853},
        {0xCCFF90, 0xB2FF59, 0x76FF03, 0x64DD17},
        {0xF4FF81, 0xEEFF41, 0xC6FF00, 0xAEEA00},
        {0xFFFF8D, 0xFFFF00, 0xFFEA00, 0xFFD600},
        {0xFFE57F, 0xFFD740, 0xFFC400, 0xFFAB00},
        {0xFFD180, 0xFFAB40, 0xFF9100, 0xFF6D00},
        {0xFF9E80, 0xFF6E40, 0xFF3D00, 0xDD2C00},
        {0, 0, 0, 0},
        {0, 0, 0, 0},
        {0, 0, 0, 0},
    };
}
