// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>
// Included inside kor::Vec<T, 4>: every read swizzle, as glm's GLM_FORCE_SWIZZLE has them — v.ZYX(), v.XXYY().

constexpr Vec<T, 2> XX() const { return {x, x}; }
constexpr Vec<T, 2> XY() const { return {x, y}; }
constexpr Vec<T, 2> XZ() const { return {x, z}; }
constexpr Vec<T, 2> XW() const { return {x, w}; }
constexpr Vec<T, 2> YX() const { return {y, x}; }
constexpr Vec<T, 2> YY() const { return {y, y}; }
constexpr Vec<T, 2> YZ() const { return {y, z}; }
constexpr Vec<T, 2> YW() const { return {y, w}; }
constexpr Vec<T, 2> ZX() const { return {z, x}; }
constexpr Vec<T, 2> ZY() const { return {z, y}; }
constexpr Vec<T, 2> ZZ() const { return {z, z}; }
constexpr Vec<T, 2> ZW() const { return {z, w}; }
constexpr Vec<T, 2> WX() const { return {w, x}; }
constexpr Vec<T, 2> WY() const { return {w, y}; }
constexpr Vec<T, 2> WZ() const { return {w, z}; }
constexpr Vec<T, 2> WW() const { return {w, w}; }
constexpr Vec<T, 3> XXX() const { return {x, x, x}; }
constexpr Vec<T, 3> XXY() const { return {x, x, y}; }
constexpr Vec<T, 3> XXZ() const { return {x, x, z}; }
constexpr Vec<T, 3> XXW() const { return {x, x, w}; }
constexpr Vec<T, 3> XYX() const { return {x, y, x}; }
constexpr Vec<T, 3> XYY() const { return {x, y, y}; }
constexpr Vec<T, 3> XYZ() const { return {x, y, z}; }
constexpr Vec<T, 3> XYW() const { return {x, y, w}; }
constexpr Vec<T, 3> XZX() const { return {x, z, x}; }
constexpr Vec<T, 3> XZY() const { return {x, z, y}; }
constexpr Vec<T, 3> XZZ() const { return {x, z, z}; }
constexpr Vec<T, 3> XZW() const { return {x, z, w}; }
constexpr Vec<T, 3> XWX() const { return {x, w, x}; }
constexpr Vec<T, 3> XWY() const { return {x, w, y}; }
constexpr Vec<T, 3> XWZ() const { return {x, w, z}; }
constexpr Vec<T, 3> XWW() const { return {x, w, w}; }
constexpr Vec<T, 3> YXX() const { return {y, x, x}; }
constexpr Vec<T, 3> YXY() const { return {y, x, y}; }
constexpr Vec<T, 3> YXZ() const { return {y, x, z}; }
constexpr Vec<T, 3> YXW() const { return {y, x, w}; }
constexpr Vec<T, 3> YYX() const { return {y, y, x}; }
constexpr Vec<T, 3> YYY() const { return {y, y, y}; }
constexpr Vec<T, 3> YYZ() const { return {y, y, z}; }
constexpr Vec<T, 3> YYW() const { return {y, y, w}; }
constexpr Vec<T, 3> YZX() const { return {y, z, x}; }
constexpr Vec<T, 3> YZY() const { return {y, z, y}; }
constexpr Vec<T, 3> YZZ() const { return {y, z, z}; }
constexpr Vec<T, 3> YZW() const { return {y, z, w}; }
constexpr Vec<T, 3> YWX() const { return {y, w, x}; }
constexpr Vec<T, 3> YWY() const { return {y, w, y}; }
constexpr Vec<T, 3> YWZ() const { return {y, w, z}; }
constexpr Vec<T, 3> YWW() const { return {y, w, w}; }
constexpr Vec<T, 3> ZXX() const { return {z, x, x}; }
constexpr Vec<T, 3> ZXY() const { return {z, x, y}; }
constexpr Vec<T, 3> ZXZ() const { return {z, x, z}; }
constexpr Vec<T, 3> ZXW() const { return {z, x, w}; }
constexpr Vec<T, 3> ZYX() const { return {z, y, x}; }
constexpr Vec<T, 3> ZYY() const { return {z, y, y}; }
constexpr Vec<T, 3> ZYZ() const { return {z, y, z}; }
constexpr Vec<T, 3> ZYW() const { return {z, y, w}; }
constexpr Vec<T, 3> ZZX() const { return {z, z, x}; }
constexpr Vec<T, 3> ZZY() const { return {z, z, y}; }
constexpr Vec<T, 3> ZZZ() const { return {z, z, z}; }
constexpr Vec<T, 3> ZZW() const { return {z, z, w}; }
constexpr Vec<T, 3> ZWX() const { return {z, w, x}; }
constexpr Vec<T, 3> ZWY() const { return {z, w, y}; }
constexpr Vec<T, 3> ZWZ() const { return {z, w, z}; }
constexpr Vec<T, 3> ZWW() const { return {z, w, w}; }
constexpr Vec<T, 3> WXX() const { return {w, x, x}; }
constexpr Vec<T, 3> WXY() const { return {w, x, y}; }
constexpr Vec<T, 3> WXZ() const { return {w, x, z}; }
constexpr Vec<T, 3> WXW() const { return {w, x, w}; }
constexpr Vec<T, 3> WYX() const { return {w, y, x}; }
constexpr Vec<T, 3> WYY() const { return {w, y, y}; }
constexpr Vec<T, 3> WYZ() const { return {w, y, z}; }
constexpr Vec<T, 3> WYW() const { return {w, y, w}; }
constexpr Vec<T, 3> WZX() const { return {w, z, x}; }
constexpr Vec<T, 3> WZY() const { return {w, z, y}; }
constexpr Vec<T, 3> WZZ() const { return {w, z, z}; }
constexpr Vec<T, 3> WZW() const { return {w, z, w}; }
constexpr Vec<T, 3> WWX() const { return {w, w, x}; }
constexpr Vec<T, 3> WWY() const { return {w, w, y}; }
constexpr Vec<T, 3> WWZ() const { return {w, w, z}; }
constexpr Vec<T, 3> WWW() const { return {w, w, w}; }
constexpr Vec<T, 4> XXXX() const { return {x, x, x, x}; }
constexpr Vec<T, 4> XXXY() const { return {x, x, x, y}; }
constexpr Vec<T, 4> XXXZ() const { return {x, x, x, z}; }
constexpr Vec<T, 4> XXXW() const { return {x, x, x, w}; }
constexpr Vec<T, 4> XXYX() const { return {x, x, y, x}; }
constexpr Vec<T, 4> XXYY() const { return {x, x, y, y}; }
constexpr Vec<T, 4> XXYZ() const { return {x, x, y, z}; }
constexpr Vec<T, 4> XXYW() const { return {x, x, y, w}; }
constexpr Vec<T, 4> XXZX() const { return {x, x, z, x}; }
constexpr Vec<T, 4> XXZY() const { return {x, x, z, y}; }
constexpr Vec<T, 4> XXZZ() const { return {x, x, z, z}; }
constexpr Vec<T, 4> XXZW() const { return {x, x, z, w}; }
constexpr Vec<T, 4> XXWX() const { return {x, x, w, x}; }
constexpr Vec<T, 4> XXWY() const { return {x, x, w, y}; }
constexpr Vec<T, 4> XXWZ() const { return {x, x, w, z}; }
constexpr Vec<T, 4> XXWW() const { return {x, x, w, w}; }
constexpr Vec<T, 4> XYXX() const { return {x, y, x, x}; }
constexpr Vec<T, 4> XYXY() const { return {x, y, x, y}; }
constexpr Vec<T, 4> XYXZ() const { return {x, y, x, z}; }
constexpr Vec<T, 4> XYXW() const { return {x, y, x, w}; }
constexpr Vec<T, 4> XYYX() const { return {x, y, y, x}; }
constexpr Vec<T, 4> XYYY() const { return {x, y, y, y}; }
constexpr Vec<T, 4> XYYZ() const { return {x, y, y, z}; }
constexpr Vec<T, 4> XYYW() const { return {x, y, y, w}; }
constexpr Vec<T, 4> XYZX() const { return {x, y, z, x}; }
constexpr Vec<T, 4> XYZY() const { return {x, y, z, y}; }
constexpr Vec<T, 4> XYZZ() const { return {x, y, z, z}; }
constexpr Vec<T, 4> XYZW() const { return {x, y, z, w}; }
constexpr Vec<T, 4> XYWX() const { return {x, y, w, x}; }
constexpr Vec<T, 4> XYWY() const { return {x, y, w, y}; }
constexpr Vec<T, 4> XYWZ() const { return {x, y, w, z}; }
constexpr Vec<T, 4> XYWW() const { return {x, y, w, w}; }
constexpr Vec<T, 4> XZXX() const { return {x, z, x, x}; }
constexpr Vec<T, 4> XZXY() const { return {x, z, x, y}; }
constexpr Vec<T, 4> XZXZ() const { return {x, z, x, z}; }
constexpr Vec<T, 4> XZXW() const { return {x, z, x, w}; }
constexpr Vec<T, 4> XZYX() const { return {x, z, y, x}; }
constexpr Vec<T, 4> XZYY() const { return {x, z, y, y}; }
constexpr Vec<T, 4> XZYZ() const { return {x, z, y, z}; }
constexpr Vec<T, 4> XZYW() const { return {x, z, y, w}; }
constexpr Vec<T, 4> XZZX() const { return {x, z, z, x}; }
constexpr Vec<T, 4> XZZY() const { return {x, z, z, y}; }
constexpr Vec<T, 4> XZZZ() const { return {x, z, z, z}; }
constexpr Vec<T, 4> XZZW() const { return {x, z, z, w}; }
constexpr Vec<T, 4> XZWX() const { return {x, z, w, x}; }
constexpr Vec<T, 4> XZWY() const { return {x, z, w, y}; }
constexpr Vec<T, 4> XZWZ() const { return {x, z, w, z}; }
constexpr Vec<T, 4> XZWW() const { return {x, z, w, w}; }
constexpr Vec<T, 4> XWXX() const { return {x, w, x, x}; }
constexpr Vec<T, 4> XWXY() const { return {x, w, x, y}; }
constexpr Vec<T, 4> XWXZ() const { return {x, w, x, z}; }
constexpr Vec<T, 4> XWXW() const { return {x, w, x, w}; }
constexpr Vec<T, 4> XWYX() const { return {x, w, y, x}; }
constexpr Vec<T, 4> XWYY() const { return {x, w, y, y}; }
constexpr Vec<T, 4> XWYZ() const { return {x, w, y, z}; }
constexpr Vec<T, 4> XWYW() const { return {x, w, y, w}; }
constexpr Vec<T, 4> XWZX() const { return {x, w, z, x}; }
constexpr Vec<T, 4> XWZY() const { return {x, w, z, y}; }
constexpr Vec<T, 4> XWZZ() const { return {x, w, z, z}; }
constexpr Vec<T, 4> XWZW() const { return {x, w, z, w}; }
constexpr Vec<T, 4> XWWX() const { return {x, w, w, x}; }
constexpr Vec<T, 4> XWWY() const { return {x, w, w, y}; }
constexpr Vec<T, 4> XWWZ() const { return {x, w, w, z}; }
constexpr Vec<T, 4> XWWW() const { return {x, w, w, w}; }
constexpr Vec<T, 4> YXXX() const { return {y, x, x, x}; }
constexpr Vec<T, 4> YXXY() const { return {y, x, x, y}; }
constexpr Vec<T, 4> YXXZ() const { return {y, x, x, z}; }
constexpr Vec<T, 4> YXXW() const { return {y, x, x, w}; }
constexpr Vec<T, 4> YXYX() const { return {y, x, y, x}; }
constexpr Vec<T, 4> YXYY() const { return {y, x, y, y}; }
constexpr Vec<T, 4> YXYZ() const { return {y, x, y, z}; }
constexpr Vec<T, 4> YXYW() const { return {y, x, y, w}; }
constexpr Vec<T, 4> YXZX() const { return {y, x, z, x}; }
constexpr Vec<T, 4> YXZY() const { return {y, x, z, y}; }
constexpr Vec<T, 4> YXZZ() const { return {y, x, z, z}; }
constexpr Vec<T, 4> YXZW() const { return {y, x, z, w}; }
constexpr Vec<T, 4> YXWX() const { return {y, x, w, x}; }
constexpr Vec<T, 4> YXWY() const { return {y, x, w, y}; }
constexpr Vec<T, 4> YXWZ() const { return {y, x, w, z}; }
constexpr Vec<T, 4> YXWW() const { return {y, x, w, w}; }
constexpr Vec<T, 4> YYXX() const { return {y, y, x, x}; }
constexpr Vec<T, 4> YYXY() const { return {y, y, x, y}; }
constexpr Vec<T, 4> YYXZ() const { return {y, y, x, z}; }
constexpr Vec<T, 4> YYXW() const { return {y, y, x, w}; }
constexpr Vec<T, 4> YYYX() const { return {y, y, y, x}; }
constexpr Vec<T, 4> YYYY() const { return {y, y, y, y}; }
constexpr Vec<T, 4> YYYZ() const { return {y, y, y, z}; }
constexpr Vec<T, 4> YYYW() const { return {y, y, y, w}; }
constexpr Vec<T, 4> YYZX() const { return {y, y, z, x}; }
constexpr Vec<T, 4> YYZY() const { return {y, y, z, y}; }
constexpr Vec<T, 4> YYZZ() const { return {y, y, z, z}; }
constexpr Vec<T, 4> YYZW() const { return {y, y, z, w}; }
constexpr Vec<T, 4> YYWX() const { return {y, y, w, x}; }
constexpr Vec<T, 4> YYWY() const { return {y, y, w, y}; }
constexpr Vec<T, 4> YYWZ() const { return {y, y, w, z}; }
constexpr Vec<T, 4> YYWW() const { return {y, y, w, w}; }
constexpr Vec<T, 4> YZXX() const { return {y, z, x, x}; }
constexpr Vec<T, 4> YZXY() const { return {y, z, x, y}; }
constexpr Vec<T, 4> YZXZ() const { return {y, z, x, z}; }
constexpr Vec<T, 4> YZXW() const { return {y, z, x, w}; }
constexpr Vec<T, 4> YZYX() const { return {y, z, y, x}; }
constexpr Vec<T, 4> YZYY() const { return {y, z, y, y}; }
constexpr Vec<T, 4> YZYZ() const { return {y, z, y, z}; }
constexpr Vec<T, 4> YZYW() const { return {y, z, y, w}; }
constexpr Vec<T, 4> YZZX() const { return {y, z, z, x}; }
constexpr Vec<T, 4> YZZY() const { return {y, z, z, y}; }
constexpr Vec<T, 4> YZZZ() const { return {y, z, z, z}; }
constexpr Vec<T, 4> YZZW() const { return {y, z, z, w}; }
constexpr Vec<T, 4> YZWX() const { return {y, z, w, x}; }
constexpr Vec<T, 4> YZWY() const { return {y, z, w, y}; }
constexpr Vec<T, 4> YZWZ() const { return {y, z, w, z}; }
constexpr Vec<T, 4> YZWW() const { return {y, z, w, w}; }
constexpr Vec<T, 4> YWXX() const { return {y, w, x, x}; }
constexpr Vec<T, 4> YWXY() const { return {y, w, x, y}; }
constexpr Vec<T, 4> YWXZ() const { return {y, w, x, z}; }
constexpr Vec<T, 4> YWXW() const { return {y, w, x, w}; }
constexpr Vec<T, 4> YWYX() const { return {y, w, y, x}; }
constexpr Vec<T, 4> YWYY() const { return {y, w, y, y}; }
constexpr Vec<T, 4> YWYZ() const { return {y, w, y, z}; }
constexpr Vec<T, 4> YWYW() const { return {y, w, y, w}; }
constexpr Vec<T, 4> YWZX() const { return {y, w, z, x}; }
constexpr Vec<T, 4> YWZY() const { return {y, w, z, y}; }
constexpr Vec<T, 4> YWZZ() const { return {y, w, z, z}; }
constexpr Vec<T, 4> YWZW() const { return {y, w, z, w}; }
constexpr Vec<T, 4> YWWX() const { return {y, w, w, x}; }
constexpr Vec<T, 4> YWWY() const { return {y, w, w, y}; }
constexpr Vec<T, 4> YWWZ() const { return {y, w, w, z}; }
constexpr Vec<T, 4> YWWW() const { return {y, w, w, w}; }
constexpr Vec<T, 4> ZXXX() const { return {z, x, x, x}; }
constexpr Vec<T, 4> ZXXY() const { return {z, x, x, y}; }
constexpr Vec<T, 4> ZXXZ() const { return {z, x, x, z}; }
constexpr Vec<T, 4> ZXXW() const { return {z, x, x, w}; }
constexpr Vec<T, 4> ZXYX() const { return {z, x, y, x}; }
constexpr Vec<T, 4> ZXYY() const { return {z, x, y, y}; }
constexpr Vec<T, 4> ZXYZ() const { return {z, x, y, z}; }
constexpr Vec<T, 4> ZXYW() const { return {z, x, y, w}; }
constexpr Vec<T, 4> ZXZX() const { return {z, x, z, x}; }
constexpr Vec<T, 4> ZXZY() const { return {z, x, z, y}; }
constexpr Vec<T, 4> ZXZZ() const { return {z, x, z, z}; }
constexpr Vec<T, 4> ZXZW() const { return {z, x, z, w}; }
constexpr Vec<T, 4> ZXWX() const { return {z, x, w, x}; }
constexpr Vec<T, 4> ZXWY() const { return {z, x, w, y}; }
constexpr Vec<T, 4> ZXWZ() const { return {z, x, w, z}; }
constexpr Vec<T, 4> ZXWW() const { return {z, x, w, w}; }
constexpr Vec<T, 4> ZYXX() const { return {z, y, x, x}; }
constexpr Vec<T, 4> ZYXY() const { return {z, y, x, y}; }
constexpr Vec<T, 4> ZYXZ() const { return {z, y, x, z}; }
constexpr Vec<T, 4> ZYXW() const { return {z, y, x, w}; }
constexpr Vec<T, 4> ZYYX() const { return {z, y, y, x}; }
constexpr Vec<T, 4> ZYYY() const { return {z, y, y, y}; }
constexpr Vec<T, 4> ZYYZ() const { return {z, y, y, z}; }
constexpr Vec<T, 4> ZYYW() const { return {z, y, y, w}; }
constexpr Vec<T, 4> ZYZX() const { return {z, y, z, x}; }
constexpr Vec<T, 4> ZYZY() const { return {z, y, z, y}; }
constexpr Vec<T, 4> ZYZZ() const { return {z, y, z, z}; }
constexpr Vec<T, 4> ZYZW() const { return {z, y, z, w}; }
constexpr Vec<T, 4> ZYWX() const { return {z, y, w, x}; }
constexpr Vec<T, 4> ZYWY() const { return {z, y, w, y}; }
constexpr Vec<T, 4> ZYWZ() const { return {z, y, w, z}; }
constexpr Vec<T, 4> ZYWW() const { return {z, y, w, w}; }
constexpr Vec<T, 4> ZZXX() const { return {z, z, x, x}; }
constexpr Vec<T, 4> ZZXY() const { return {z, z, x, y}; }
constexpr Vec<T, 4> ZZXZ() const { return {z, z, x, z}; }
constexpr Vec<T, 4> ZZXW() const { return {z, z, x, w}; }
constexpr Vec<T, 4> ZZYX() const { return {z, z, y, x}; }
constexpr Vec<T, 4> ZZYY() const { return {z, z, y, y}; }
constexpr Vec<T, 4> ZZYZ() const { return {z, z, y, z}; }
constexpr Vec<T, 4> ZZYW() const { return {z, z, y, w}; }
constexpr Vec<T, 4> ZZZX() const { return {z, z, z, x}; }
constexpr Vec<T, 4> ZZZY() const { return {z, z, z, y}; }
constexpr Vec<T, 4> ZZZZ() const { return {z, z, z, z}; }
constexpr Vec<T, 4> ZZZW() const { return {z, z, z, w}; }
constexpr Vec<T, 4> ZZWX() const { return {z, z, w, x}; }
constexpr Vec<T, 4> ZZWY() const { return {z, z, w, y}; }
constexpr Vec<T, 4> ZZWZ() const { return {z, z, w, z}; }
constexpr Vec<T, 4> ZZWW() const { return {z, z, w, w}; }
constexpr Vec<T, 4> ZWXX() const { return {z, w, x, x}; }
constexpr Vec<T, 4> ZWXY() const { return {z, w, x, y}; }
constexpr Vec<T, 4> ZWXZ() const { return {z, w, x, z}; }
constexpr Vec<T, 4> ZWXW() const { return {z, w, x, w}; }
constexpr Vec<T, 4> ZWYX() const { return {z, w, y, x}; }
constexpr Vec<T, 4> ZWYY() const { return {z, w, y, y}; }
constexpr Vec<T, 4> ZWYZ() const { return {z, w, y, z}; }
constexpr Vec<T, 4> ZWYW() const { return {z, w, y, w}; }
constexpr Vec<T, 4> ZWZX() const { return {z, w, z, x}; }
constexpr Vec<T, 4> ZWZY() const { return {z, w, z, y}; }
constexpr Vec<T, 4> ZWZZ() const { return {z, w, z, z}; }
constexpr Vec<T, 4> ZWZW() const { return {z, w, z, w}; }
constexpr Vec<T, 4> ZWWX() const { return {z, w, w, x}; }
constexpr Vec<T, 4> ZWWY() const { return {z, w, w, y}; }
constexpr Vec<T, 4> ZWWZ() const { return {z, w, w, z}; }
constexpr Vec<T, 4> ZWWW() const { return {z, w, w, w}; }
constexpr Vec<T, 4> WXXX() const { return {w, x, x, x}; }
constexpr Vec<T, 4> WXXY() const { return {w, x, x, y}; }
constexpr Vec<T, 4> WXXZ() const { return {w, x, x, z}; }
constexpr Vec<T, 4> WXXW() const { return {w, x, x, w}; }
constexpr Vec<T, 4> WXYX() const { return {w, x, y, x}; }
constexpr Vec<T, 4> WXYY() const { return {w, x, y, y}; }
constexpr Vec<T, 4> WXYZ() const { return {w, x, y, z}; }
constexpr Vec<T, 4> WXYW() const { return {w, x, y, w}; }
constexpr Vec<T, 4> WXZX() const { return {w, x, z, x}; }
constexpr Vec<T, 4> WXZY() const { return {w, x, z, y}; }
constexpr Vec<T, 4> WXZZ() const { return {w, x, z, z}; }
constexpr Vec<T, 4> WXZW() const { return {w, x, z, w}; }
constexpr Vec<T, 4> WXWX() const { return {w, x, w, x}; }
constexpr Vec<T, 4> WXWY() const { return {w, x, w, y}; }
constexpr Vec<T, 4> WXWZ() const { return {w, x, w, z}; }
constexpr Vec<T, 4> WXWW() const { return {w, x, w, w}; }
constexpr Vec<T, 4> WYXX() const { return {w, y, x, x}; }
constexpr Vec<T, 4> WYXY() const { return {w, y, x, y}; }
constexpr Vec<T, 4> WYXZ() const { return {w, y, x, z}; }
constexpr Vec<T, 4> WYXW() const { return {w, y, x, w}; }
constexpr Vec<T, 4> WYYX() const { return {w, y, y, x}; }
constexpr Vec<T, 4> WYYY() const { return {w, y, y, y}; }
constexpr Vec<T, 4> WYYZ() const { return {w, y, y, z}; }
constexpr Vec<T, 4> WYYW() const { return {w, y, y, w}; }
constexpr Vec<T, 4> WYZX() const { return {w, y, z, x}; }
constexpr Vec<T, 4> WYZY() const { return {w, y, z, y}; }
constexpr Vec<T, 4> WYZZ() const { return {w, y, z, z}; }
constexpr Vec<T, 4> WYZW() const { return {w, y, z, w}; }
constexpr Vec<T, 4> WYWX() const { return {w, y, w, x}; }
constexpr Vec<T, 4> WYWY() const { return {w, y, w, y}; }
constexpr Vec<T, 4> WYWZ() const { return {w, y, w, z}; }
constexpr Vec<T, 4> WYWW() const { return {w, y, w, w}; }
constexpr Vec<T, 4> WZXX() const { return {w, z, x, x}; }
constexpr Vec<T, 4> WZXY() const { return {w, z, x, y}; }
constexpr Vec<T, 4> WZXZ() const { return {w, z, x, z}; }
constexpr Vec<T, 4> WZXW() const { return {w, z, x, w}; }
constexpr Vec<T, 4> WZYX() const { return {w, z, y, x}; }
constexpr Vec<T, 4> WZYY() const { return {w, z, y, y}; }
constexpr Vec<T, 4> WZYZ() const { return {w, z, y, z}; }
constexpr Vec<T, 4> WZYW() const { return {w, z, y, w}; }
constexpr Vec<T, 4> WZZX() const { return {w, z, z, x}; }
constexpr Vec<T, 4> WZZY() const { return {w, z, z, y}; }
constexpr Vec<T, 4> WZZZ() const { return {w, z, z, z}; }
constexpr Vec<T, 4> WZZW() const { return {w, z, z, w}; }
constexpr Vec<T, 4> WZWX() const { return {w, z, w, x}; }
constexpr Vec<T, 4> WZWY() const { return {w, z, w, y}; }
constexpr Vec<T, 4> WZWZ() const { return {w, z, w, z}; }
constexpr Vec<T, 4> WZWW() const { return {w, z, w, w}; }
constexpr Vec<T, 4> WWXX() const { return {w, w, x, x}; }
constexpr Vec<T, 4> WWXY() const { return {w, w, x, y}; }
constexpr Vec<T, 4> WWXZ() const { return {w, w, x, z}; }
constexpr Vec<T, 4> WWXW() const { return {w, w, x, w}; }
constexpr Vec<T, 4> WWYX() const { return {w, w, y, x}; }
constexpr Vec<T, 4> WWYY() const { return {w, w, y, y}; }
constexpr Vec<T, 4> WWYZ() const { return {w, w, y, z}; }
constexpr Vec<T, 4> WWYW() const { return {w, w, y, w}; }
constexpr Vec<T, 4> WWZX() const { return {w, w, z, x}; }
constexpr Vec<T, 4> WWZY() const { return {w, w, z, y}; }
constexpr Vec<T, 4> WWZZ() const { return {w, w, z, z}; }
constexpr Vec<T, 4> WWZW() const { return {w, w, z, w}; }
constexpr Vec<T, 4> WWWX() const { return {w, w, w, x}; }
constexpr Vec<T, 4> WWWY() const { return {w, w, w, y}; }
constexpr Vec<T, 4> WWWZ() const { return {w, w, w, z}; }
constexpr Vec<T, 4> WWWW() const { return {w, w, w, w}; }
