// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>
// Included inside kor::Vec<T, 3>: every read swizzle, as glm's GLM_FORCE_SWIZZLE has them — v.ZYX(), v.XXYY().

constexpr Vec<T, 2> XX() const { return {x, x}; }
constexpr Vec<T, 2> XY() const { return {x, y}; }
constexpr Vec<T, 2> XZ() const { return {x, z}; }
constexpr Vec<T, 2> YX() const { return {y, x}; }
constexpr Vec<T, 2> YY() const { return {y, y}; }
constexpr Vec<T, 2> YZ() const { return {y, z}; }
constexpr Vec<T, 2> ZX() const { return {z, x}; }
constexpr Vec<T, 2> ZY() const { return {z, y}; }
constexpr Vec<T, 2> ZZ() const { return {z, z}; }
constexpr Vec<T, 3> XXX() const { return {x, x, x}; }
constexpr Vec<T, 3> XXY() const { return {x, x, y}; }
constexpr Vec<T, 3> XXZ() const { return {x, x, z}; }
constexpr Vec<T, 3> XYX() const { return {x, y, x}; }
constexpr Vec<T, 3> XYY() const { return {x, y, y}; }
constexpr Vec<T, 3> XYZ() const { return {x, y, z}; }
constexpr Vec<T, 3> XZX() const { return {x, z, x}; }
constexpr Vec<T, 3> XZY() const { return {x, z, y}; }
constexpr Vec<T, 3> XZZ() const { return {x, z, z}; }
constexpr Vec<T, 3> YXX() const { return {y, x, x}; }
constexpr Vec<T, 3> YXY() const { return {y, x, y}; }
constexpr Vec<T, 3> YXZ() const { return {y, x, z}; }
constexpr Vec<T, 3> YYX() const { return {y, y, x}; }
constexpr Vec<T, 3> YYY() const { return {y, y, y}; }
constexpr Vec<T, 3> YYZ() const { return {y, y, z}; }
constexpr Vec<T, 3> YZX() const { return {y, z, x}; }
constexpr Vec<T, 3> YZY() const { return {y, z, y}; }
constexpr Vec<T, 3> YZZ() const { return {y, z, z}; }
constexpr Vec<T, 3> ZXX() const { return {z, x, x}; }
constexpr Vec<T, 3> ZXY() const { return {z, x, y}; }
constexpr Vec<T, 3> ZXZ() const { return {z, x, z}; }
constexpr Vec<T, 3> ZYX() const { return {z, y, x}; }
constexpr Vec<T, 3> ZYY() const { return {z, y, y}; }
constexpr Vec<T, 3> ZYZ() const { return {z, y, z}; }
constexpr Vec<T, 3> ZZX() const { return {z, z, x}; }
constexpr Vec<T, 3> ZZY() const { return {z, z, y}; }
constexpr Vec<T, 3> ZZZ() const { return {z, z, z}; }
constexpr Vec<T, 4> XXXX() const { return {x, x, x, x}; }
constexpr Vec<T, 4> XXXY() const { return {x, x, x, y}; }
constexpr Vec<T, 4> XXXZ() const { return {x, x, x, z}; }
constexpr Vec<T, 4> XXYX() const { return {x, x, y, x}; }
constexpr Vec<T, 4> XXYY() const { return {x, x, y, y}; }
constexpr Vec<T, 4> XXYZ() const { return {x, x, y, z}; }
constexpr Vec<T, 4> XXZX() const { return {x, x, z, x}; }
constexpr Vec<T, 4> XXZY() const { return {x, x, z, y}; }
constexpr Vec<T, 4> XXZZ() const { return {x, x, z, z}; }
constexpr Vec<T, 4> XYXX() const { return {x, y, x, x}; }
constexpr Vec<T, 4> XYXY() const { return {x, y, x, y}; }
constexpr Vec<T, 4> XYXZ() const { return {x, y, x, z}; }
constexpr Vec<T, 4> XYYX() const { return {x, y, y, x}; }
constexpr Vec<T, 4> XYYY() const { return {x, y, y, y}; }
constexpr Vec<T, 4> XYYZ() const { return {x, y, y, z}; }
constexpr Vec<T, 4> XYZX() const { return {x, y, z, x}; }
constexpr Vec<T, 4> XYZY() const { return {x, y, z, y}; }
constexpr Vec<T, 4> XYZZ() const { return {x, y, z, z}; }
constexpr Vec<T, 4> XZXX() const { return {x, z, x, x}; }
constexpr Vec<T, 4> XZXY() const { return {x, z, x, y}; }
constexpr Vec<T, 4> XZXZ() const { return {x, z, x, z}; }
constexpr Vec<T, 4> XZYX() const { return {x, z, y, x}; }
constexpr Vec<T, 4> XZYY() const { return {x, z, y, y}; }
constexpr Vec<T, 4> XZYZ() const { return {x, z, y, z}; }
constexpr Vec<T, 4> XZZX() const { return {x, z, z, x}; }
constexpr Vec<T, 4> XZZY() const { return {x, z, z, y}; }
constexpr Vec<T, 4> XZZZ() const { return {x, z, z, z}; }
constexpr Vec<T, 4> YXXX() const { return {y, x, x, x}; }
constexpr Vec<T, 4> YXXY() const { return {y, x, x, y}; }
constexpr Vec<T, 4> YXXZ() const { return {y, x, x, z}; }
constexpr Vec<T, 4> YXYX() const { return {y, x, y, x}; }
constexpr Vec<T, 4> YXYY() const { return {y, x, y, y}; }
constexpr Vec<T, 4> YXYZ() const { return {y, x, y, z}; }
constexpr Vec<T, 4> YXZX() const { return {y, x, z, x}; }
constexpr Vec<T, 4> YXZY() const { return {y, x, z, y}; }
constexpr Vec<T, 4> YXZZ() const { return {y, x, z, z}; }
constexpr Vec<T, 4> YYXX() const { return {y, y, x, x}; }
constexpr Vec<T, 4> YYXY() const { return {y, y, x, y}; }
constexpr Vec<T, 4> YYXZ() const { return {y, y, x, z}; }
constexpr Vec<T, 4> YYYX() const { return {y, y, y, x}; }
constexpr Vec<T, 4> YYYY() const { return {y, y, y, y}; }
constexpr Vec<T, 4> YYYZ() const { return {y, y, y, z}; }
constexpr Vec<T, 4> YYZX() const { return {y, y, z, x}; }
constexpr Vec<T, 4> YYZY() const { return {y, y, z, y}; }
constexpr Vec<T, 4> YYZZ() const { return {y, y, z, z}; }
constexpr Vec<T, 4> YZXX() const { return {y, z, x, x}; }
constexpr Vec<T, 4> YZXY() const { return {y, z, x, y}; }
constexpr Vec<T, 4> YZXZ() const { return {y, z, x, z}; }
constexpr Vec<T, 4> YZYX() const { return {y, z, y, x}; }
constexpr Vec<T, 4> YZYY() const { return {y, z, y, y}; }
constexpr Vec<T, 4> YZYZ() const { return {y, z, y, z}; }
constexpr Vec<T, 4> YZZX() const { return {y, z, z, x}; }
constexpr Vec<T, 4> YZZY() const { return {y, z, z, y}; }
constexpr Vec<T, 4> YZZZ() const { return {y, z, z, z}; }
constexpr Vec<T, 4> ZXXX() const { return {z, x, x, x}; }
constexpr Vec<T, 4> ZXXY() const { return {z, x, x, y}; }
constexpr Vec<T, 4> ZXXZ() const { return {z, x, x, z}; }
constexpr Vec<T, 4> ZXYX() const { return {z, x, y, x}; }
constexpr Vec<T, 4> ZXYY() const { return {z, x, y, y}; }
constexpr Vec<T, 4> ZXYZ() const { return {z, x, y, z}; }
constexpr Vec<T, 4> ZXZX() const { return {z, x, z, x}; }
constexpr Vec<T, 4> ZXZY() const { return {z, x, z, y}; }
constexpr Vec<T, 4> ZXZZ() const { return {z, x, z, z}; }
constexpr Vec<T, 4> ZYXX() const { return {z, y, x, x}; }
constexpr Vec<T, 4> ZYXY() const { return {z, y, x, y}; }
constexpr Vec<T, 4> ZYXZ() const { return {z, y, x, z}; }
constexpr Vec<T, 4> ZYYX() const { return {z, y, y, x}; }
constexpr Vec<T, 4> ZYYY() const { return {z, y, y, y}; }
constexpr Vec<T, 4> ZYYZ() const { return {z, y, y, z}; }
constexpr Vec<T, 4> ZYZX() const { return {z, y, z, x}; }
constexpr Vec<T, 4> ZYZY() const { return {z, y, z, y}; }
constexpr Vec<T, 4> ZYZZ() const { return {z, y, z, z}; }
constexpr Vec<T, 4> ZZXX() const { return {z, z, x, x}; }
constexpr Vec<T, 4> ZZXY() const { return {z, z, x, y}; }
constexpr Vec<T, 4> ZZXZ() const { return {z, z, x, z}; }
constexpr Vec<T, 4> ZZYX() const { return {z, z, y, x}; }
constexpr Vec<T, 4> ZZYY() const { return {z, z, y, y}; }
constexpr Vec<T, 4> ZZYZ() const { return {z, z, y, z}; }
constexpr Vec<T, 4> ZZZX() const { return {z, z, z, x}; }
constexpr Vec<T, 4> ZZZY() const { return {z, z, z, y}; }
constexpr Vec<T, 4> ZZZZ() const { return {z, z, z, z}; }
