// <auto-generated> by scripts/kmath/generate.py: do not edit. </auto-generated>
// Included inside kor::Vec<T, 2>: every read swizzle, as glm's GLM_FORCE_SWIZZLE has them — v.ZYX(), v.XXYY().

constexpr Vec<T, 2> XX() const { return {x, x}; }
constexpr Vec<T, 2> XY() const { return {x, y}; }
constexpr Vec<T, 2> YX() const { return {y, x}; }
constexpr Vec<T, 2> YY() const { return {y, y}; }
constexpr Vec<T, 3> XXX() const { return {x, x, x}; }
constexpr Vec<T, 3> XXY() const { return {x, x, y}; }
constexpr Vec<T, 3> XYX() const { return {x, y, x}; }
constexpr Vec<T, 3> XYY() const { return {x, y, y}; }
constexpr Vec<T, 3> YXX() const { return {y, x, x}; }
constexpr Vec<T, 3> YXY() const { return {y, x, y}; }
constexpr Vec<T, 3> YYX() const { return {y, y, x}; }
constexpr Vec<T, 3> YYY() const { return {y, y, y}; }
constexpr Vec<T, 4> XXXX() const { return {x, x, x, x}; }
constexpr Vec<T, 4> XXXY() const { return {x, x, x, y}; }
constexpr Vec<T, 4> XXYX() const { return {x, x, y, x}; }
constexpr Vec<T, 4> XXYY() const { return {x, x, y, y}; }
constexpr Vec<T, 4> XYXX() const { return {x, y, x, x}; }
constexpr Vec<T, 4> XYXY() const { return {x, y, x, y}; }
constexpr Vec<T, 4> XYYX() const { return {x, y, y, x}; }
constexpr Vec<T, 4> XYYY() const { return {x, y, y, y}; }
constexpr Vec<T, 4> YXXX() const { return {y, x, x, x}; }
constexpr Vec<T, 4> YXXY() const { return {y, x, x, y}; }
constexpr Vec<T, 4> YXYX() const { return {y, x, y, x}; }
constexpr Vec<T, 4> YXYY() const { return {y, x, y, y}; }
constexpr Vec<T, 4> YYXX() const { return {y, y, x, x}; }
constexpr Vec<T, 4> YYXY() const { return {y, y, x, y}; }
constexpr Vec<T, 4> YYYX() const { return {y, y, y, x}; }
constexpr Vec<T, 4> YYYY() const { return {y, y, y, y}; }
