// <auto-generated> by tools/generate_kotlin.py from include/koral_math_c.h: do not edit. </auto-generated>
@file:Suppress("FunctionName", "LocalVariableName", "unused", "ObjectPropertyName", "PropertyName")

package koral.interop

import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout.*
import java.lang.invoke.MethodHandle

/** The C structs' layouts, with C's padding. */
object KoralMathLayouts {
    val KoralVec2: StructLayout = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y"),
    )
    val KoralVec3: StructLayout = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y"),
        JAVA_FLOAT.withName("z"),
    )
    val KoralVec4: StructLayout = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y"),
        JAVA_FLOAT.withName("z"),
        JAVA_FLOAT.withName("w"),
    )
    val KoralIVec2: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
    )
    val KoralIVec3: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("z"),
    )
    val KoralIVec4: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("z"),
        JAVA_INT.withName("w"),
    )
    val KoralUVec2: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
    )
    val KoralUVec3: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("z"),
    )
    val KoralUVec4: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("z"),
        JAVA_INT.withName("w"),
    )
    val KoralQuat: StructLayout = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y"),
        JAVA_FLOAT.withName("z"),
        JAVA_FLOAT.withName("w"),
    )
    val KoralMat3: StructLayout = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(9, JAVA_FLOAT).withName("m"),
    )
    val KoralMat4: StructLayout = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(16, JAVA_FLOAT).withName("m"),
    )
    val KoralTransform: StructLayout = MemoryLayout.structLayout(
        KoralVec3.withName("position"),
        KoralQuat.withName("rotation"),
        KoralVec3.withName("scale"),
    )
    val KoralRay: StructLayout = MemoryLayout.structLayout(
        KoralVec3.withName("origin"),
        KoralVec3.withName("direction"),
    )
    val KoralPlane: StructLayout = MemoryLayout.structLayout(
        KoralVec3.withName("normal"),
        JAVA_FLOAT.withName("distance"),
    )
    val KoralSphere: StructLayout = MemoryLayout.structLayout(
        KoralVec3.withName("center"),
        JAVA_FLOAT.withName("radius"),
    )
    val KoralAabb: StructLayout = MemoryLayout.structLayout(
        KoralVec3.withName("min"),
        KoralVec3.withName("max"),
    )
    val KoralObb: StructLayout = MemoryLayout.structLayout(
        KoralVec3.withName("center"),
        KoralVec3.withName("half_extents"),
        KoralQuat.withName("rotation"),
    )
    val KoralTriangle: StructLayout = MemoryLayout.structLayout(
        KoralVec3.withName("a"),
        KoralVec3.withName("b"),
        KoralVec3.withName("c"),
    )
    val KoralAabb2: StructLayout = MemoryLayout.structLayout(
        KoralVec2.withName("min"),
        KoralVec2.withName("max"),
    )
    val KoralFrustum: StructLayout = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(6, KoralPlane).withName("planes"),
    )
    val KoralTriangleHit: StructLayout = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("distance"),
        JAVA_FLOAT.withName("u"),
        JAVA_FLOAT.withName("v"),
    )
    val KoralRandom: StructLayout = MemoryLayout.structLayout(
        JAVA_LONG.withName("state"),
        JAVA_LONG.withName("increment"),
    )
    val KoralNoise: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("seed"),
        MemoryLayout.sequenceLayout(512, JAVA_BYTE).withName("perm"),
    )
    val KoralFractalOptions: StructLayout = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("octaves"),
        JAVA_FLOAT.withName("lacunarity"),
        JAVA_FLOAT.withName("gain"),
    )
}

object KoralMathNative {
    // A call to a void function is a statement, which Kotlin's call site types as void, as the handle is;
    // anything else is cast, which types the call site's return.
    private fun handle(name: String, descriptor: FunctionDescriptor): MethodHandle {
        val symbol = Native.koral.find(name).orElseThrow { UnsatisfiedLinkError("KoralMathNative: no " + name) }
        return Native.linker.downcallHandle(symbol, descriptor)
    }

    private val h_koral_mat4_identity by lazy { handle("koral_mat4_identity", FunctionDescriptor.of(KoralMathLayouts.KoralMat4)) }
    fun koral_mat4_identity(allocator: SegmentAllocator): MemorySegment = h_koral_mat4_identity.invokeExact(allocator) as MemorySegment
    private val h_koral_mat4_mul by lazy { handle("koral_mat4_mul", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralMat4)) }
    fun koral_mat4_mul(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment): MemorySegment = h_koral_mat4_mul.invokeExact(allocator, a, b) as MemorySegment
    private val h_koral_mat4_mul_vec4 by lazy { handle("koral_mat4_mul_vec4", FunctionDescriptor.of(KoralMathLayouts.KoralVec4, KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec4)) }
    fun koral_mat4_mul_vec4(allocator: SegmentAllocator, m: MemorySegment, v: MemorySegment): MemorySegment = h_koral_mat4_mul_vec4.invokeExact(allocator, m, v) as MemorySegment
    private val h_koral_mat4_inverse by lazy { handle("koral_mat4_inverse", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralMat4)) }
    fun koral_mat4_inverse(allocator: SegmentAllocator, m: MemorySegment): MemorySegment = h_koral_mat4_inverse.invokeExact(allocator, m) as MemorySegment
    private val h_koral_mat4_transpose by lazy { handle("koral_mat4_transpose", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralMat4)) }
    fun koral_mat4_transpose(allocator: SegmentAllocator, m: MemorySegment): MemorySegment = h_koral_mat4_transpose.invokeExact(allocator, m) as MemorySegment
    private val h_koral_mat4_determinant by lazy { handle("koral_mat4_determinant", FunctionDescriptor.of(JAVA_FLOAT, KoralMathLayouts.KoralMat4)) }
    fun koral_mat4_determinant(m: MemorySegment): Float = h_koral_mat4_determinant.invokeExact(m) as Float
    private val h_koral_mat4_normal_matrix by lazy { handle("koral_mat4_normal_matrix", FunctionDescriptor.of(KoralMathLayouts.KoralMat3, KoralMathLayouts.KoralMat4)) }
    fun koral_mat4_normal_matrix(allocator: SegmentAllocator, model: MemorySegment): MemorySegment = h_koral_mat4_normal_matrix.invokeExact(allocator, model) as MemorySegment
    private val h_koral_mat3_mul by lazy { handle("koral_mat3_mul", FunctionDescriptor.of(KoralMathLayouts.KoralMat3, KoralMathLayouts.KoralMat3, KoralMathLayouts.KoralMat3)) }
    fun koral_mat3_mul(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment): MemorySegment = h_koral_mat3_mul.invokeExact(allocator, a, b) as MemorySegment
    private val h_koral_mat3_mul_vec3 by lazy { handle("koral_mat3_mul_vec3", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralMat3, KoralMathLayouts.KoralVec3)) }
    fun koral_mat3_mul_vec3(allocator: SegmentAllocator, m: MemorySegment, v: MemorySegment): MemorySegment = h_koral_mat3_mul_vec3.invokeExact(allocator, m, v) as MemorySegment
    private val h_koral_mat3_inverse by lazy { handle("koral_mat3_inverse", FunctionDescriptor.of(KoralMathLayouts.KoralMat3, KoralMathLayouts.KoralMat3)) }
    fun koral_mat3_inverse(allocator: SegmentAllocator, m: MemorySegment): MemorySegment = h_koral_mat3_inverse.invokeExact(allocator, m) as MemorySegment
    private val h_koral_mat3_transpose by lazy { handle("koral_mat3_transpose", FunctionDescriptor.of(KoralMathLayouts.KoralMat3, KoralMathLayouts.KoralMat3)) }
    fun koral_mat3_transpose(allocator: SegmentAllocator, m: MemorySegment): MemorySegment = h_koral_mat3_transpose.invokeExact(allocator, m) as MemorySegment
    private val h_koral_mat3_determinant by lazy { handle("koral_mat3_determinant", FunctionDescriptor.of(JAVA_FLOAT, KoralMathLayouts.KoralMat3)) }
    fun koral_mat3_determinant(m: MemorySegment): Float = h_koral_mat3_determinant.invokeExact(m) as Float
    private val h_koral_translation by lazy { handle("koral_translation", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3)) }
    fun koral_translation(allocator: SegmentAllocator, by: MemorySegment): MemorySegment = h_koral_translation.invokeExact(allocator, by) as MemorySegment
    private val h_koral_scaling by lazy { handle("koral_scaling", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3)) }
    fun koral_scaling(allocator: SegmentAllocator, by: MemorySegment): MemorySegment = h_koral_scaling.invokeExact(allocator, by) as MemorySegment
    private val h_koral_rotation by lazy { handle("koral_rotation", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, JAVA_FLOAT, KoralMathLayouts.KoralVec3)) }
    fun koral_rotation(allocator: SegmentAllocator, angle: Float, axis: MemorySegment): MemorySegment = h_koral_rotation.invokeExact(allocator, angle, axis) as MemorySegment
    private val h_koral_rotation_quat by lazy { handle("koral_rotation_quat", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralQuat)) }
    fun koral_rotation_quat(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_rotation_quat.invokeExact(allocator, q) as MemorySegment
    private val h_koral_compose by lazy { handle("koral_compose", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralVec3)) }
    fun koral_compose(allocator: SegmentAllocator, translation: MemorySegment, rotation: MemorySegment, scale: MemorySegment): MemorySegment = h_koral_compose.invokeExact(allocator, translation, rotation, scale) as MemorySegment
    private val h_koral_decompose by lazy { handle("koral_decompose", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralMat4, ADDRESS, ADDRESS, ADDRESS)) }
    fun koral_decompose(m: MemorySegment, translation: MemorySegment, rotation: MemorySegment, scale: MemorySegment): Boolean = h_koral_decompose.invokeExact(m, translation, rotation, scale) as Boolean
    private val h_koral_translate by lazy { handle("koral_translate", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3)) }
    fun koral_translate(allocator: SegmentAllocator, m: MemorySegment, by: MemorySegment): MemorySegment = h_koral_translate.invokeExact(allocator, m, by) as MemorySegment
    private val h_koral_rotate by lazy { handle("koral_rotate", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralMat4, JAVA_FLOAT, KoralMathLayouts.KoralVec3)) }
    fun koral_rotate(allocator: SegmentAllocator, m: MemorySegment, angle: Float, axis: MemorySegment): MemorySegment = h_koral_rotate.invokeExact(allocator, m, angle, axis) as MemorySegment
    private val h_koral_scale by lazy { handle("koral_scale", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3)) }
    fun koral_scale(allocator: SegmentAllocator, m: MemorySegment, by: MemorySegment): MemorySegment = h_koral_scale.invokeExact(allocator, m, by) as MemorySegment
    private val h_koral_look_at by lazy { handle("koral_look_at", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_look_at(allocator: SegmentAllocator, eye: MemorySegment, target: MemorySegment, up: MemorySegment): MemorySegment = h_koral_look_at.invokeExact(allocator, eye, target, up) as MemorySegment
    private val h_koral_perspective by lazy { handle("koral_perspective", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_perspective(allocator: SegmentAllocator, fov_y: Float, aspect: Float, near_plane: Float, far_plane: Float): MemorySegment = h_koral_perspective.invokeExact(allocator, fov_y, aspect, near_plane, far_plane) as MemorySegment
    private val h_koral_perspective_reversed_z by lazy { handle("koral_perspective_reversed_z", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_perspective_reversed_z(allocator: SegmentAllocator, fov_y: Float, aspect: Float, near_plane: Float, far_plane: Float): MemorySegment = h_koral_perspective_reversed_z.invokeExact(allocator, fov_y, aspect, near_plane, far_plane) as MemorySegment
    private val h_koral_orthographic by lazy { handle("koral_orthographic", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_orthographic(allocator: SegmentAllocator, left: Float, right: Float, bottom: Float, top: Float, near_plane: Float, far_plane: Float): MemorySegment = h_koral_orthographic.invokeExact(allocator, left, right, bottom, top, near_plane, far_plane) as MemorySegment
    private val h_koral_transform_point by lazy { handle("koral_transform_point", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3)) }
    fun koral_transform_point(allocator: SegmentAllocator, m: MemorySegment, p: MemorySegment): MemorySegment = h_koral_transform_point.invokeExact(allocator, m, p) as MemorySegment
    private val h_koral_transform_point_projective by lazy { handle("koral_transform_point_projective", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3)) }
    fun koral_transform_point_projective(allocator: SegmentAllocator, m: MemorySegment, p: MemorySegment): MemorySegment = h_koral_transform_point_projective.invokeExact(allocator, m, p) as MemorySegment
    private val h_koral_transform_direction by lazy { handle("koral_transform_direction", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralVec3)) }
    fun koral_transform_direction(allocator: SegmentAllocator, m: MemorySegment, d: MemorySegment): MemorySegment = h_koral_transform_direction.invokeExact(allocator, m, d) as MemorySegment
    private val h_koral_quat_identity by lazy { handle("koral_quat_identity", FunctionDescriptor.of(KoralMathLayouts.KoralQuat)) }
    fun koral_quat_identity(allocator: SegmentAllocator): MemorySegment = h_koral_quat_identity.invokeExact(allocator) as MemorySegment
    private val h_koral_quat_angle_axis by lazy { handle("koral_quat_angle_axis", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, JAVA_FLOAT, KoralMathLayouts.KoralVec3)) }
    fun koral_quat_angle_axis(allocator: SegmentAllocator, angle: Float, axis: MemorySegment): MemorySegment = h_koral_quat_angle_axis.invokeExact(allocator, angle, axis) as MemorySegment
    private val h_koral_quat_from_euler by lazy { handle("koral_quat_from_euler", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralVec3)) }
    fun koral_quat_from_euler(allocator: SegmentAllocator, euler: MemorySegment): MemorySegment = h_koral_quat_from_euler.invokeExact(allocator, euler) as MemorySegment
    private val h_koral_quat_from_matrix by lazy { handle("koral_quat_from_matrix", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralMat3)) }
    fun koral_quat_from_matrix(allocator: SegmentAllocator, m: MemorySegment): MemorySegment = h_koral_quat_from_matrix.invokeExact(allocator, m) as MemorySegment
    private val h_koral_quat_look_rotation by lazy { handle("koral_quat_look_rotation", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_quat_look_rotation(allocator: SegmentAllocator, direction: MemorySegment, up: MemorySegment): MemorySegment = h_koral_quat_look_rotation.invokeExact(allocator, direction, up) as MemorySegment
    private val h_koral_quat_from_to by lazy { handle("koral_quat_from_to", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_quat_from_to(allocator: SegmentAllocator, from: MemorySegment, to: MemorySegment): MemorySegment = h_koral_quat_from_to.invokeExact(allocator, from, to) as MemorySegment
    private val h_koral_quat_mul by lazy { handle("koral_quat_mul", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_mul(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment): MemorySegment = h_koral_quat_mul.invokeExact(allocator, a, b) as MemorySegment
    private val h_koral_quat_rotate by lazy { handle("koral_quat_rotate", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralVec3)) }
    fun koral_quat_rotate(allocator: SegmentAllocator, q: MemorySegment, v: MemorySegment): MemorySegment = h_koral_quat_rotate.invokeExact(allocator, q, v) as MemorySegment
    private val h_koral_quat_conjugate by lazy { handle("koral_quat_conjugate", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_conjugate(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_quat_conjugate.invokeExact(allocator, q) as MemorySegment
    private val h_koral_quat_inverse by lazy { handle("koral_quat_inverse", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_inverse(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_quat_inverse.invokeExact(allocator, q) as MemorySegment
    private val h_koral_quat_normalize by lazy { handle("koral_quat_normalize", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_normalize(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_quat_normalize.invokeExact(allocator, q) as MemorySegment
    private val h_koral_quat_dot by lazy { handle("koral_quat_dot", FunctionDescriptor.of(JAVA_FLOAT, KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_dot(a: MemorySegment, b: MemorySegment): Float = h_koral_quat_dot.invokeExact(a, b) as Float
    private val h_koral_quat_angle by lazy { handle("koral_quat_angle", FunctionDescriptor.of(JAVA_FLOAT, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_angle(q: MemorySegment): Float = h_koral_quat_angle.invokeExact(q) as Float
    private val h_koral_quat_axis by lazy { handle("koral_quat_axis", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_axis(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_quat_axis.invokeExact(allocator, q) as MemorySegment
    private val h_koral_quat_euler_angles by lazy { handle("koral_quat_euler_angles", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_euler_angles(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_quat_euler_angles.invokeExact(allocator, q) as MemorySegment
    private val h_koral_quat_to_mat3 by lazy { handle("koral_quat_to_mat3", FunctionDescriptor.of(KoralMathLayouts.KoralMat3, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_to_mat3(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_quat_to_mat3.invokeExact(allocator, q) as MemorySegment
    private val h_koral_quat_to_mat4 by lazy { handle("koral_quat_to_mat4", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralQuat)) }
    fun koral_quat_to_mat4(allocator: SegmentAllocator, q: MemorySegment): MemorySegment = h_koral_quat_to_mat4.invokeExact(allocator, q) as MemorySegment
    private val h_koral_quat_slerp by lazy { handle("koral_quat_slerp", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat, JAVA_FLOAT)) }
    fun koral_quat_slerp(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment, t: Float): MemorySegment = h_koral_quat_slerp.invokeExact(allocator, a, b, t) as MemorySegment
    private val h_koral_quat_nlerp by lazy { handle("koral_quat_nlerp", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat, JAVA_FLOAT)) }
    fun koral_quat_nlerp(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment, t: Float): MemorySegment = h_koral_quat_nlerp.invokeExact(allocator, a, b, t) as MemorySegment
    private val h_koral_quat_rotate_towards by lazy { handle("koral_quat_rotate_towards", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat, KoralMathLayouts.KoralQuat, JAVA_FLOAT)) }
    fun koral_quat_rotate_towards(allocator: SegmentAllocator, from: MemorySegment, to: MemorySegment, max_radians: Float): MemorySegment = h_koral_quat_rotate_towards.invokeExact(allocator, from, to, max_radians) as MemorySegment
    private val h_koral_transform_identity by lazy { handle("koral_transform_identity", FunctionDescriptor.of(KoralMathLayouts.KoralTransform)) }
    fun koral_transform_identity(allocator: SegmentAllocator): MemorySegment = h_koral_transform_identity.invokeExact(allocator) as MemorySegment
    private val h_koral_transform_from_matrix by lazy { handle("koral_transform_from_matrix", FunctionDescriptor.of(KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralMat4)) }
    fun koral_transform_from_matrix(allocator: SegmentAllocator, m: MemorySegment): MemorySegment = h_koral_transform_from_matrix.invokeExact(allocator, m) as MemorySegment
    private val h_koral_transform_matrix by lazy { handle("koral_transform_matrix", FunctionDescriptor.of(KoralMathLayouts.KoralMat4, KoralMathLayouts.KoralTransform)) }
    fun koral_transform_matrix(allocator: SegmentAllocator, t: MemorySegment): MemorySegment = h_koral_transform_matrix.invokeExact(allocator, t) as MemorySegment
    private val h_koral_transform_mul by lazy { handle("koral_transform_mul", FunctionDescriptor.of(KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralTransform)) }
    fun koral_transform_mul(allocator: SegmentAllocator, parent: MemorySegment, child: MemorySegment): MemorySegment = h_koral_transform_mul.invokeExact(allocator, parent, child) as MemorySegment
    private val h_koral_transform_inverse by lazy { handle("koral_transform_inverse", FunctionDescriptor.of(KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralTransform)) }
    fun koral_transform_inverse(allocator: SegmentAllocator, t: MemorySegment): MemorySegment = h_koral_transform_inverse.invokeExact(allocator, t) as MemorySegment
    private val h_koral_transform_lerp by lazy { handle("koral_transform_lerp", FunctionDescriptor.of(KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralTransform, JAVA_FLOAT)) }
    fun koral_transform_lerp(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment, t: Float): MemorySegment = h_koral_transform_lerp.invokeExact(allocator, a, b, t) as MemorySegment
    private val h_koral_transform_transform_point by lazy { handle("koral_transform_transform_point", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralVec3)) }
    fun koral_transform_transform_point(allocator: SegmentAllocator, t: MemorySegment, p: MemorySegment): MemorySegment = h_koral_transform_transform_point.invokeExact(allocator, t, p) as MemorySegment
    private val h_koral_transform_transform_direction by lazy { handle("koral_transform_transform_direction", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralVec3)) }
    fun koral_transform_transform_direction(allocator: SegmentAllocator, t: MemorySegment, d: MemorySegment): MemorySegment = h_koral_transform_transform_direction.invokeExact(allocator, t, d) as MemorySegment
    private val h_koral_transform_inverse_transform_point by lazy { handle("koral_transform_inverse_transform_point", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralVec3)) }
    fun koral_transform_inverse_transform_point(allocator: SegmentAllocator, t: MemorySegment, p: MemorySegment): MemorySegment = h_koral_transform_inverse_transform_point.invokeExact(allocator, t, p) as MemorySegment
    private val h_koral_transform_forward by lazy { handle("koral_transform_forward", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTransform)) }
    fun koral_transform_forward(allocator: SegmentAllocator, t: MemorySegment): MemorySegment = h_koral_transform_forward.invokeExact(allocator, t) as MemorySegment
    private val h_koral_transform_right by lazy { handle("koral_transform_right", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTransform)) }
    fun koral_transform_right(allocator: SegmentAllocator, t: MemorySegment): MemorySegment = h_koral_transform_right.invokeExact(allocator, t) as MemorySegment
    private val h_koral_transform_up by lazy { handle("koral_transform_up", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTransform)) }
    fun koral_transform_up(allocator: SegmentAllocator, t: MemorySegment): MemorySegment = h_koral_transform_up.invokeExact(allocator, t) as MemorySegment
    private val h_koral_transform_look_at by lazy { handle("koral_transform_look_at", FunctionDescriptor.of(KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralTransform, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_transform_look_at(allocator: SegmentAllocator, t: MemorySegment, target: MemorySegment, up: MemorySegment): MemorySegment = h_koral_transform_look_at.invokeExact(allocator, t, target, up) as MemorySegment
    private val h_koral_plane_from_point_normal by lazy { handle("koral_plane_from_point_normal", FunctionDescriptor.of(KoralMathLayouts.KoralPlane, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_plane_from_point_normal(allocator: SegmentAllocator, point: MemorySegment, normal: MemorySegment): MemorySegment = h_koral_plane_from_point_normal.invokeExact(allocator, point, normal) as MemorySegment
    private val h_koral_plane_from_points by lazy { handle("koral_plane_from_points", FunctionDescriptor.of(KoralMathLayouts.KoralPlane, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_plane_from_points(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment, c: MemorySegment): MemorySegment = h_koral_plane_from_points.invokeExact(allocator, a, b, c) as MemorySegment
    private val h_koral_plane_signed_distance by lazy { handle("koral_plane_signed_distance", FunctionDescriptor.of(JAVA_FLOAT, KoralMathLayouts.KoralPlane, KoralMathLayouts.KoralVec3)) }
    fun koral_plane_signed_distance(plane: MemorySegment, p: MemorySegment): Float = h_koral_plane_signed_distance.invokeExact(plane, p) as Float
    private val h_koral_sphere_from_points by lazy { handle("koral_sphere_from_points", FunctionDescriptor.of(KoralMathLayouts.KoralSphere, ADDRESS, JAVA_LONG)) }
    fun koral_sphere_from_points(allocator: SegmentAllocator, points: MemorySegment, count: Long): MemorySegment = h_koral_sphere_from_points.invokeExact(allocator, points, count) as MemorySegment
    private val h_koral_aabb_empty by lazy { handle("koral_aabb_empty", FunctionDescriptor.of(KoralMathLayouts.KoralAabb)) }
    fun koral_aabb_empty(allocator: SegmentAllocator): MemorySegment = h_koral_aabb_empty.invokeExact(allocator) as MemorySegment
    private val h_koral_aabb_from_points by lazy { handle("koral_aabb_from_points", FunctionDescriptor.of(KoralMathLayouts.KoralAabb, ADDRESS, JAVA_LONG)) }
    fun koral_aabb_from_points(allocator: SegmentAllocator, points: MemorySegment, count: Long): MemorySegment = h_koral_aabb_from_points.invokeExact(allocator, points, count) as MemorySegment
    private val h_koral_aabb_expand by lazy { handle("koral_aabb_expand", FunctionDescriptor.of(KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralVec3)) }
    fun koral_aabb_expand(allocator: SegmentAllocator, box: MemorySegment, p: MemorySegment): MemorySegment = h_koral_aabb_expand.invokeExact(allocator, box, p) as MemorySegment
    private val h_koral_aabb_transformed by lazy { handle("koral_aabb_transformed", FunctionDescriptor.of(KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralMat4)) }
    fun koral_aabb_transformed(allocator: SegmentAllocator, box: MemorySegment, m: MemorySegment): MemorySegment = h_koral_aabb_transformed.invokeExact(allocator, box, m) as MemorySegment
    private val h_koral_aabb_contains by lazy { handle("koral_aabb_contains", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralVec3)) }
    fun koral_aabb_contains(box: MemorySegment, p: MemorySegment): Boolean = h_koral_aabb_contains.invokeExact(box, p) as Boolean
    private val h_koral_obb_from_aabb by lazy { handle("koral_obb_from_aabb", FunctionDescriptor.of(KoralMathLayouts.KoralObb, KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralMat4)) }
    fun koral_obb_from_aabb(allocator: SegmentAllocator, local: MemorySegment, m: MemorySegment): MemorySegment = h_koral_obb_from_aabb.invokeExact(allocator, local, m) as MemorySegment
    private val h_koral_obb_bounds by lazy { handle("koral_obb_bounds", FunctionDescriptor.of(KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralObb)) }
    fun koral_obb_bounds(allocator: SegmentAllocator, box: MemorySegment): MemorySegment = h_koral_obb_bounds.invokeExact(allocator, box) as MemorySegment
    private val h_koral_obb_contains by lazy { handle("koral_obb_contains", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralObb, KoralMathLayouts.KoralVec3)) }
    fun koral_obb_contains(box: MemorySegment, p: MemorySegment): Boolean = h_koral_obb_contains.invokeExact(box, p) as Boolean
    private val h_koral_triangle_barycentric by lazy { handle("koral_triangle_barycentric", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTriangle, KoralMathLayouts.KoralVec3)) }
    fun koral_triangle_barycentric(allocator: SegmentAllocator, triangle: MemorySegment, p: MemorySegment): MemorySegment = h_koral_triangle_barycentric.invokeExact(allocator, triangle, p) as MemorySegment
    private val h_koral_frustum_from_matrix by lazy { handle("koral_frustum_from_matrix", FunctionDescriptor.of(KoralMathLayouts.KoralFrustum, KoralMathLayouts.KoralMat4)) }
    fun koral_frustum_from_matrix(allocator: SegmentAllocator, view_projection: MemorySegment): MemorySegment = h_koral_frustum_from_matrix.invokeExact(allocator, view_projection) as MemorySegment
    private val h_koral_frustum_corners by lazy { handle("koral_frustum_corners", FunctionDescriptor.ofVoid(KoralMathLayouts.KoralMat4, ADDRESS)) }
    fun koral_frustum_corners(view_projection: MemorySegment, corners: MemorySegment): Unit { h_koral_frustum_corners.invokeExact(view_projection, corners) }
    private val h_koral_frustum_contains by lazy { handle("koral_frustum_contains", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralFrustum, KoralMathLayouts.KoralVec3)) }
    fun koral_frustum_contains(frustum: MemorySegment, p: MemorySegment): Boolean = h_koral_frustum_contains.invokeExact(frustum, p) as Boolean
    private val h_koral_frustum_classify_aabb by lazy { handle("koral_frustum_classify_aabb", FunctionDescriptor.of(JAVA_INT, KoralMathLayouts.KoralFrustum, KoralMathLayouts.KoralAabb)) }
    fun koral_frustum_classify_aabb(frustum: MemorySegment, box: MemorySegment): Int = h_koral_frustum_classify_aabb.invokeExact(frustum, box) as Int
    private val h_koral_frustum_classify_sphere by lazy { handle("koral_frustum_classify_sphere", FunctionDescriptor.of(JAVA_INT, KoralMathLayouts.KoralFrustum, KoralMathLayouts.KoralSphere)) }
    fun koral_frustum_classify_sphere(frustum: MemorySegment, sphere: MemorySegment): Int = h_koral_frustum_classify_sphere.invokeExact(frustum, sphere) as Int
    private val h_koral_raycast_plane by lazy { handle("koral_raycast_plane", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralRay, KoralMathLayouts.KoralPlane, JAVA_FLOAT, ADDRESS)) }
    fun koral_raycast_plane(ray: MemorySegment, plane: MemorySegment, max_distance: Float, distance: MemorySegment): Boolean = h_koral_raycast_plane.invokeExact(ray, plane, max_distance, distance) as Boolean
    private val h_koral_raycast_sphere by lazy { handle("koral_raycast_sphere", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralRay, KoralMathLayouts.KoralSphere, JAVA_FLOAT, ADDRESS)) }
    fun koral_raycast_sphere(ray: MemorySegment, sphere: MemorySegment, max_distance: Float, distance: MemorySegment): Boolean = h_koral_raycast_sphere.invokeExact(ray, sphere, max_distance, distance) as Boolean
    private val h_koral_raycast_aabb by lazy { handle("koral_raycast_aabb", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralRay, KoralMathLayouts.KoralAabb, JAVA_FLOAT, ADDRESS)) }
    fun koral_raycast_aabb(ray: MemorySegment, box: MemorySegment, max_distance: Float, distance: MemorySegment): Boolean = h_koral_raycast_aabb.invokeExact(ray, box, max_distance, distance) as Boolean
    private val h_koral_raycast_obb by lazy { handle("koral_raycast_obb", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralRay, KoralMathLayouts.KoralObb, JAVA_FLOAT, ADDRESS)) }
    fun koral_raycast_obb(ray: MemorySegment, box: MemorySegment, max_distance: Float, distance: MemorySegment): Boolean = h_koral_raycast_obb.invokeExact(ray, box, max_distance, distance) as Boolean
    private val h_koral_raycast_triangle by lazy { handle("koral_raycast_triangle", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralRay, KoralMathLayouts.KoralTriangle, JAVA_FLOAT, JAVA_BOOLEAN, ADDRESS)) }
    fun koral_raycast_triangle(ray: MemorySegment, triangle: MemorySegment, max_distance: Float, cull_back_faces: Boolean, hit: MemorySegment): Boolean = h_koral_raycast_triangle.invokeExact(ray, triangle, max_distance, cull_back_faces, hit) as Boolean
    private val h_koral_overlaps_aabb_aabb by lazy { handle("koral_overlaps_aabb_aabb", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralAabb)) }
    fun koral_overlaps_aabb_aabb(a: MemorySegment, b: MemorySegment): Boolean = h_koral_overlaps_aabb_aabb.invokeExact(a, b) as Boolean
    private val h_koral_overlaps_sphere_sphere by lazy { handle("koral_overlaps_sphere_sphere", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralSphere, KoralMathLayouts.KoralSphere)) }
    fun koral_overlaps_sphere_sphere(a: MemorySegment, b: MemorySegment): Boolean = h_koral_overlaps_sphere_sphere.invokeExact(a, b) as Boolean
    private val h_koral_overlaps_aabb_sphere by lazy { handle("koral_overlaps_aabb_sphere", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralSphere)) }
    fun koral_overlaps_aabb_sphere(box: MemorySegment, sphere: MemorySegment): Boolean = h_koral_overlaps_aabb_sphere.invokeExact(box, sphere) as Boolean
    private val h_koral_overlaps_obb_obb by lazy { handle("koral_overlaps_obb_obb", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralObb, KoralMathLayouts.KoralObb)) }
    fun koral_overlaps_obb_obb(a: MemorySegment, b: MemorySegment): Boolean = h_koral_overlaps_obb_obb.invokeExact(a, b) as Boolean
    private val h_koral_overlaps_aabb2_aabb2 by lazy { handle("koral_overlaps_aabb2_aabb2", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralAabb2, KoralMathLayouts.KoralAabb2)) }
    fun koral_overlaps_aabb2_aabb2(a: MemorySegment, b: MemorySegment): Boolean = h_koral_overlaps_aabb2_aabb2.invokeExact(a, b) as Boolean
    private val h_koral_overlaps_frustum_aabb by lazy { handle("koral_overlaps_frustum_aabb", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralFrustum, KoralMathLayouts.KoralAabb)) }
    fun koral_overlaps_frustum_aabb(frustum: MemorySegment, box: MemorySegment): Boolean = h_koral_overlaps_frustum_aabb.invokeExact(frustum, box) as Boolean
    private val h_koral_overlaps_frustum_sphere by lazy { handle("koral_overlaps_frustum_sphere", FunctionDescriptor.of(JAVA_BOOLEAN, KoralMathLayouts.KoralFrustum, KoralMathLayouts.KoralSphere)) }
    fun koral_overlaps_frustum_sphere(frustum: MemorySegment, sphere: MemorySegment): Boolean = h_koral_overlaps_frustum_sphere.invokeExact(frustum, sphere) as Boolean
    private val h_koral_closest_point_aabb by lazy { handle("koral_closest_point_aabb", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralAabb, KoralMathLayouts.KoralVec3)) }
    fun koral_closest_point_aabb(allocator: SegmentAllocator, box: MemorySegment, p: MemorySegment): MemorySegment = h_koral_closest_point_aabb.invokeExact(allocator, box, p) as MemorySegment
    private val h_koral_closest_point_plane by lazy { handle("koral_closest_point_plane", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralPlane, KoralMathLayouts.KoralVec3)) }
    fun koral_closest_point_plane(allocator: SegmentAllocator, plane: MemorySegment, p: MemorySegment): MemorySegment = h_koral_closest_point_plane.invokeExact(allocator, plane, p) as MemorySegment
    private val h_koral_closest_point_sphere by lazy { handle("koral_closest_point_sphere", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralSphere, KoralMathLayouts.KoralVec3)) }
    fun koral_closest_point_sphere(allocator: SegmentAllocator, sphere: MemorySegment, p: MemorySegment): MemorySegment = h_koral_closest_point_sphere.invokeExact(allocator, sphere, p) as MemorySegment
    private val h_koral_closest_point_obb by lazy { handle("koral_closest_point_obb", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralObb, KoralMathLayouts.KoralVec3)) }
    fun koral_closest_point_obb(allocator: SegmentAllocator, box: MemorySegment, p: MemorySegment): MemorySegment = h_koral_closest_point_obb.invokeExact(allocator, box, p) as MemorySegment
    private val h_koral_closest_point_triangle by lazy { handle("koral_closest_point_triangle", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralTriangle, KoralMathLayouts.KoralVec3)) }
    fun koral_closest_point_triangle(allocator: SegmentAllocator, triangle: MemorySegment, p: MemorySegment): MemorySegment = h_koral_closest_point_triangle.invokeExact(allocator, triangle, p) as MemorySegment
    private val h_koral_closest_point_on_segment by lazy { handle("koral_closest_point_on_segment", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_closest_point_on_segment(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment, p: MemorySegment): MemorySegment = h_koral_closest_point_on_segment.invokeExact(allocator, a, b, p) as MemorySegment
    private val h_koral_random_new by lazy { handle("koral_random_new", FunctionDescriptor.of(KoralMathLayouts.KoralRandom, JAVA_LONG, JAVA_LONG)) }
    fun koral_random_new(allocator: SegmentAllocator, seed: Long, stream: Long): MemorySegment = h_koral_random_new.invokeExact(allocator, seed, stream) as MemorySegment
    private val h_koral_random_from_entropy by lazy { handle("koral_random_from_entropy", FunctionDescriptor.of(KoralMathLayouts.KoralRandom)) }
    fun koral_random_from_entropy(allocator: SegmentAllocator): MemorySegment = h_koral_random_from_entropy.invokeExact(allocator) as MemorySegment
    private val h_koral_random_next_u32 by lazy { handle("koral_random_next_u32", FunctionDescriptor.of(JAVA_INT, ADDRESS)) }
    fun koral_random_next_u32(random: MemorySegment): Int = h_koral_random_next_u32.invokeExact(random) as Int
    private val h_koral_random_next_u64 by lazy { handle("koral_random_next_u64", FunctionDescriptor.of(JAVA_LONG, ADDRESS)) }
    fun koral_random_next_u64(random: MemorySegment): Long = h_koral_random_next_u64.invokeExact(random) as Long
    private val h_koral_random_next_u32_below by lazy { handle("koral_random_next_u32_below", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT)) }
    fun koral_random_next_u32_below(random: MemorySegment, bound: Int): Int = h_koral_random_next_u32_below.invokeExact(random, bound) as Int
    private val h_koral_random_next_int by lazy { handle("koral_random_next_int", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT)) }
    fun koral_random_next_int(random: MemorySegment, min: Int, max_exclusive: Int): Int = h_koral_random_next_int.invokeExact(random, min, max_exclusive) as Int
    private val h_koral_random_next_float by lazy { handle("koral_random_next_float", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS)) }
    fun koral_random_next_float(random: MemorySegment): Float = h_koral_random_next_float.invokeExact(random) as Float
    private val h_koral_random_next_float_range by lazy { handle("koral_random_next_float_range", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_random_next_float_range(random: MemorySegment, min: Float, max: Float): Float = h_koral_random_next_float_range.invokeExact(random, min, max) as Float
    private val h_koral_random_next_double by lazy { handle("koral_random_next_double", FunctionDescriptor.of(JAVA_DOUBLE, ADDRESS)) }
    fun koral_random_next_double(random: MemorySegment): Double = h_koral_random_next_double.invokeExact(random) as Double
    private val h_koral_random_next_bool by lazy { handle("koral_random_next_bool", FunctionDescriptor.of(JAVA_BOOLEAN, ADDRESS, JAVA_FLOAT)) }
    fun koral_random_next_bool(random: MemorySegment, probability: Float): Boolean = h_koral_random_next_bool.invokeExact(random, probability) as Boolean
    private val h_koral_random_next_gaussian by lazy { handle("koral_random_next_gaussian", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_random_next_gaussian(random: MemorySegment, mean: Float, standard_deviation: Float): Float = h_koral_random_next_gaussian.invokeExact(random, mean, standard_deviation) as Float
    private val h_koral_random_inside_unit_circle by lazy { handle("koral_random_inside_unit_circle", FunctionDescriptor.of(KoralMathLayouts.KoralVec2, ADDRESS)) }
    fun koral_random_inside_unit_circle(allocator: SegmentAllocator, random: MemorySegment): MemorySegment = h_koral_random_inside_unit_circle.invokeExact(allocator, random) as MemorySegment
    private val h_koral_random_inside_unit_sphere by lazy { handle("koral_random_inside_unit_sphere", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, ADDRESS)) }
    fun koral_random_inside_unit_sphere(allocator: SegmentAllocator, random: MemorySegment): MemorySegment = h_koral_random_inside_unit_sphere.invokeExact(allocator, random) as MemorySegment
    private val h_koral_random_on_unit_circle by lazy { handle("koral_random_on_unit_circle", FunctionDescriptor.of(KoralMathLayouts.KoralVec2, ADDRESS)) }
    fun koral_random_on_unit_circle(allocator: SegmentAllocator, random: MemorySegment): MemorySegment = h_koral_random_on_unit_circle.invokeExact(allocator, random) as MemorySegment
    private val h_koral_random_on_unit_sphere by lazy { handle("koral_random_on_unit_sphere", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, ADDRESS)) }
    fun koral_random_on_unit_sphere(allocator: SegmentAllocator, random: MemorySegment): MemorySegment = h_koral_random_on_unit_sphere.invokeExact(allocator, random) as MemorySegment
    private val h_koral_random_rotation by lazy { handle("koral_random_rotation", FunctionDescriptor.of(KoralMathLayouts.KoralQuat, ADDRESS)) }
    fun koral_random_rotation(allocator: SegmentAllocator, random: MemorySegment): MemorySegment = h_koral_random_rotation.invokeExact(allocator, random) as MemorySegment
    private val h_koral_random_inside_box by lazy { handle("koral_random_inside_box", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, ADDRESS, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_random_inside_box(allocator: SegmentAllocator, random: MemorySegment, min: MemorySegment, max: MemorySegment): MemorySegment = h_koral_random_inside_box.invokeExact(allocator, random, min, max) as MemorySegment
    private val h_koral_random_shuffle by lazy { handle("koral_random_shuffle", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, JAVA_LONG, JAVA_LONG)) }
    fun koral_random_shuffle(random: MemorySegment, items: MemorySegment, count: Long, size: Long): Unit { h_koral_random_shuffle.invokeExact(random, items, count, size) }
    private val h_koral_random_advance by lazy { handle("koral_random_advance", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG)) }
    fun koral_random_advance(random: MemorySegment, count: Long): Unit { h_koral_random_advance.invokeExact(random, count) }
    private val h_koral_hash by lazy { handle("koral_hash", FunctionDescriptor.of(JAVA_INT, JAVA_INT)) }
    fun koral_hash(v: Int): Int = h_koral_hash.invokeExact(v) as Int
    private val h_koral_hash_combine by lazy { handle("koral_hash_combine", FunctionDescriptor.of(JAVA_INT, JAVA_INT, JAVA_INT)) }
    fun koral_hash_combine(seed: Int, v: Int): Int = h_koral_hash_combine.invokeExact(seed, v) as Int
    private val h_koral_hash_to_float by lazy { handle("koral_hash_to_float", FunctionDescriptor.of(JAVA_FLOAT, JAVA_INT)) }
    fun koral_hash_to_float(v: Int): Float = h_koral_hash_to_float.invokeExact(v) as Float
    private val h_koral_noise_init by lazy { handle("koral_noise_init", FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT)) }
    fun koral_noise_init(noise: MemorySegment, seed: Int): Unit { h_koral_noise_init.invokeExact(noise, seed) }
    private val h_koral_noise_perlin2 by lazy { handle("koral_noise_perlin2", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_perlin2(noise: MemorySegment, x: Float, y: Float): Float = h_koral_noise_perlin2.invokeExact(noise, x, y) as Float
    private val h_koral_noise_perlin3 by lazy { handle("koral_noise_perlin3", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_perlin3(noise: MemorySegment, x: Float, y: Float, z: Float): Float = h_koral_noise_perlin3.invokeExact(noise, x, y, z) as Float
    private val h_koral_noise_simplex2 by lazy { handle("koral_noise_simplex2", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_simplex2(noise: MemorySegment, x: Float, y: Float): Float = h_koral_noise_simplex2.invokeExact(noise, x, y) as Float
    private val h_koral_noise_simplex3 by lazy { handle("koral_noise_simplex3", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_simplex3(noise: MemorySegment, x: Float, y: Float, z: Float): Float = h_koral_noise_simplex3.invokeExact(noise, x, y, z) as Float
    private val h_koral_noise_value2 by lazy { handle("koral_noise_value2", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_value2(noise: MemorySegment, x: Float, y: Float): Float = h_koral_noise_value2.invokeExact(noise, x, y) as Float
    private val h_koral_noise_value3 by lazy { handle("koral_noise_value3", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_value3(noise: MemorySegment, x: Float, y: Float, z: Float): Float = h_koral_noise_value3.invokeExact(noise, x, y, z) as Float
    private val h_koral_noise_cellular2 by lazy { handle("koral_noise_cellular2", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_cellular2(noise: MemorySegment, x: Float, y: Float): Float = h_koral_noise_cellular2.invokeExact(noise, x, y) as Float
    private val h_koral_noise_cellular3 by lazy { handle("koral_noise_cellular3", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_noise_cellular3(noise: MemorySegment, x: Float, y: Float, z: Float): Float = h_koral_noise_cellular3.invokeExact(noise, x, y, z) as Float
    private val h_koral_fractal_options_default by lazy { handle("koral_fractal_options_default", FunctionDescriptor.of(KoralMathLayouts.KoralFractalOptions)) }
    fun koral_fractal_options_default(allocator: SegmentAllocator): MemorySegment = h_koral_fractal_options_default.invokeExact(allocator) as MemorySegment
    private val h_koral_noise_fractal2 by lazy { handle("koral_noise_fractal2", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_INT, KoralMathLayouts.KoralVec2, KoralMathLayouts.KoralFractalOptions)) }
    fun koral_noise_fractal2(noise: MemorySegment, kind: Int, p: MemorySegment, options: MemorySegment): Float = h_koral_noise_fractal2.invokeExact(noise, kind, p, options) as Float
    private val h_koral_noise_fractal3 by lazy { handle("koral_noise_fractal3", FunctionDescriptor.of(JAVA_FLOAT, ADDRESS, JAVA_INT, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralFractalOptions)) }
    fun koral_noise_fractal3(noise: MemorySegment, kind: Int, p: MemorySegment, options: MemorySegment): Float = h_koral_noise_fractal3.invokeExact(noise, kind, p, options) as Float
    private val h_koral_ease by lazy { handle("koral_ease", FunctionDescriptor.of(JAVA_FLOAT, JAVA_INT, JAVA_FLOAT)) }
    fun koral_ease(easing: Int, t: Float): Float = h_koral_ease.invokeExact(easing, t) as Float
    private val h_koral_bezier_quadratic by lazy { handle("koral_bezier_quadratic", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, JAVA_FLOAT)) }
    fun koral_bezier_quadratic(allocator: SegmentAllocator, p0: MemorySegment, p1: MemorySegment, p2: MemorySegment, t: Float): MemorySegment = h_koral_bezier_quadratic.invokeExact(allocator, p0, p1, p2, t) as MemorySegment
    private val h_koral_bezier_cubic by lazy { handle("koral_bezier_cubic", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, JAVA_FLOAT)) }
    fun koral_bezier_cubic(allocator: SegmentAllocator, p0: MemorySegment, p1: MemorySegment, p2: MemorySegment, p3: MemorySegment, t: Float): MemorySegment = h_koral_bezier_cubic.invokeExact(allocator, p0, p1, p2, p3, t) as MemorySegment
    private val h_koral_bezier_tangent by lazy { handle("koral_bezier_tangent", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, JAVA_FLOAT)) }
    fun koral_bezier_tangent(allocator: SegmentAllocator, p0: MemorySegment, p1: MemorySegment, p2: MemorySegment, p3: MemorySegment, t: Float): MemorySegment = h_koral_bezier_tangent.invokeExact(allocator, p0, p1, p2, p3, t) as MemorySegment
    private val h_koral_hermite by lazy { handle("koral_hermite", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, JAVA_FLOAT)) }
    fun koral_hermite(allocator: SegmentAllocator, p0: MemorySegment, m0: MemorySegment, p1: MemorySegment, m1: MemorySegment, t: Float): MemorySegment = h_koral_hermite.invokeExact(allocator, p0, m0, p1, m1, t) as MemorySegment
    private val h_koral_catmull_rom by lazy { handle("koral_catmull_rom", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, JAVA_FLOAT)) }
    fun koral_catmull_rom(allocator: SegmentAllocator, p0: MemorySegment, p1: MemorySegment, p2: MemorySegment, p3: MemorySegment, t: Float): MemorySegment = h_koral_catmull_rom.invokeExact(allocator, p0, p1, p2, p3, t) as MemorySegment
    private val h_koral_sample_path by lazy { handle("koral_sample_path", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, ADDRESS, JAVA_LONG, JAVA_FLOAT, JAVA_BOOLEAN)) }
    fun koral_sample_path(allocator: SegmentAllocator, points: MemorySegment, count: Long, t: Float, closed: Boolean): MemorySegment = h_koral_sample_path.invokeExact(allocator, points, count, t, closed) as MemorySegment
    private val h_koral_srgb_to_linear by lazy { handle("koral_srgb_to_linear", FunctionDescriptor.of(JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_srgb_to_linear(c: Float): Float = h_koral_srgb_to_linear.invokeExact(c) as Float
    private val h_koral_linear_to_srgb by lazy { handle("koral_linear_to_srgb", FunctionDescriptor.of(JAVA_FLOAT, JAVA_FLOAT)) }
    fun koral_linear_to_srgb(c: Float): Float = h_koral_linear_to_srgb.invokeExact(c) as Float
    private val h_koral_color_from_hex by lazy { handle("koral_color_from_hex", FunctionDescriptor.of(KoralMathLayouts.KoralVec4, JAVA_INT)) }
    fun koral_color_from_hex(allocator: SegmentAllocator, rgb: Int): MemorySegment = h_koral_color_from_hex.invokeExact(allocator, rgb) as MemorySegment
    private val h_koral_color_from_hex_a by lazy { handle("koral_color_from_hex_a", FunctionDescriptor.of(KoralMathLayouts.KoralVec4, JAVA_INT)) }
    fun koral_color_from_hex_a(allocator: SegmentAllocator, rgba: Int): MemorySegment = h_koral_color_from_hex_a.invokeExact(allocator, rgba) as MemorySegment
    private val h_koral_luminance by lazy { handle("koral_luminance", FunctionDescriptor.of(JAVA_FLOAT, KoralMathLayouts.KoralVec3)) }
    fun koral_luminance(linear: MemorySegment): Float = h_koral_luminance.invokeExact(linear) as Float
    private val h_koral_rgb_to_hsv by lazy { handle("koral_rgb_to_hsv", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_rgb_to_hsv(allocator: SegmentAllocator, rgb: MemorySegment): MemorySegment = h_koral_rgb_to_hsv.invokeExact(allocator, rgb) as MemorySegment
    private val h_koral_hsv_to_rgb by lazy { handle("koral_hsv_to_rgb", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_hsv_to_rgb(allocator: SegmentAllocator, hsv: MemorySegment): MemorySegment = h_koral_hsv_to_rgb.invokeExact(allocator, hsv) as MemorySegment
    private val h_koral_rgb_to_hsl by lazy { handle("koral_rgb_to_hsl", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_rgb_to_hsl(allocator: SegmentAllocator, rgb: MemorySegment): MemorySegment = h_koral_rgb_to_hsl.invokeExact(allocator, rgb) as MemorySegment
    private val h_koral_hsl_to_rgb by lazy { handle("koral_hsl_to_rgb", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_hsl_to_rgb(allocator: SegmentAllocator, hsl: MemorySegment): MemorySegment = h_koral_hsl_to_rgb.invokeExact(allocator, hsl) as MemorySegment
    private val h_koral_linear_to_oklab by lazy { handle("koral_linear_to_oklab", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_linear_to_oklab(allocator: SegmentAllocator, linear: MemorySegment): MemorySegment = h_koral_linear_to_oklab.invokeExact(allocator, linear) as MemorySegment
    private val h_koral_oklab_to_linear by lazy { handle("koral_oklab_to_linear", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3)) }
    fun koral_oklab_to_linear(allocator: SegmentAllocator, lab: MemorySegment): MemorySegment = h_koral_oklab_to_linear.invokeExact(allocator, lab) as MemorySegment
    private val h_koral_mix_oklab by lazy { handle("koral_mix_oklab", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, KoralMathLayouts.KoralVec3, JAVA_FLOAT)) }
    fun koral_mix_oklab(allocator: SegmentAllocator, a: MemorySegment, b: MemorySegment, t: Float): MemorySegment = h_koral_mix_oklab.invokeExact(allocator, a, b, t) as MemorySegment
    private val h_koral_color_temperature by lazy { handle("koral_color_temperature", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, JAVA_FLOAT)) }
    fun koral_color_temperature(allocator: SegmentAllocator, kelvin: Float): MemorySegment = h_koral_color_temperature.invokeExact(allocator, kelvin) as MemorySegment
    private val h_koral_pack_unorm4x8 by lazy { handle("koral_pack_unorm4x8", FunctionDescriptor.of(JAVA_INT, KoralMathLayouts.KoralVec4)) }
    fun koral_pack_unorm4x8(c: MemorySegment): Int = h_koral_pack_unorm4x8.invokeExact(c) as Int
    private val h_koral_unpack_unorm4x8 by lazy { handle("koral_unpack_unorm4x8", FunctionDescriptor.of(KoralMathLayouts.KoralVec4, JAVA_INT)) }
    fun koral_unpack_unorm4x8(allocator: SegmentAllocator, packed: Int): MemorySegment = h_koral_unpack_unorm4x8.invokeExact(allocator, packed) as MemorySegment
    private val h_koral_float_to_half by lazy { handle("koral_float_to_half", FunctionDescriptor.of(JAVA_SHORT, JAVA_FLOAT)) }
    fun koral_float_to_half(value: Float): Short = h_koral_float_to_half.invokeExact(value) as Short
    private val h_koral_half_to_float by lazy { handle("koral_half_to_float", FunctionDescriptor.of(JAVA_FLOAT, JAVA_SHORT)) }
    fun koral_half_to_float(half: Short): Float = h_koral_half_to_float.invokeExact(half) as Float
    private val h_koral_pack_half2x16 by lazy { handle("koral_pack_half2x16", FunctionDescriptor.of(JAVA_INT, KoralMathLayouts.KoralVec2)) }
    fun koral_pack_half2x16(v: MemorySegment): Int = h_koral_pack_half2x16.invokeExact(v) as Int
    private val h_koral_unpack_half2x16 by lazy { handle("koral_unpack_half2x16", FunctionDescriptor.of(KoralMathLayouts.KoralVec2, JAVA_INT)) }
    fun koral_unpack_half2x16(allocator: SegmentAllocator, packed: Int): MemorySegment = h_koral_unpack_half2x16.invokeExact(allocator, packed) as MemorySegment
    private val h_koral_pack_octahedral by lazy { handle("koral_pack_octahedral", FunctionDescriptor.of(JAVA_INT, KoralMathLayouts.KoralVec3)) }
    fun koral_pack_octahedral(n: MemorySegment): Int = h_koral_pack_octahedral.invokeExact(n) as Int
    private val h_koral_unpack_octahedral by lazy { handle("koral_unpack_octahedral", FunctionDescriptor.of(KoralMathLayouts.KoralVec3, JAVA_INT)) }
    fun koral_unpack_octahedral(allocator: SegmentAllocator, packed: Int): MemorySegment = h_koral_unpack_octahedral.invokeExact(allocator, packed) as MemorySegment
    private val h_koral_bulk_transform_points by lazy { handle("koral_bulk_transform_points", FunctionDescriptor.ofVoid(KoralMathLayouts.KoralMat4, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_transform_points(m: MemorySegment, points: MemorySegment, out: MemorySegment, count: Long): Unit { h_koral_bulk_transform_points.invokeExact(m, points, out, count) }
    private val h_koral_bulk_transform_directions by lazy { handle("koral_bulk_transform_directions", FunctionDescriptor.ofVoid(KoralMathLayouts.KoralMat4, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_transform_directions(m: MemorySegment, directions: MemorySegment, out: MemorySegment, count: Long): Unit { h_koral_bulk_transform_directions.invokeExact(m, directions, out, count) }
    private val h_koral_bulk_transform by lazy { handle("koral_bulk_transform", FunctionDescriptor.ofVoid(KoralMathLayouts.KoralMat4, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_transform(m: MemorySegment, vectors: MemorySegment, out: MemorySegment, count: Long): Unit { h_koral_bulk_transform.invokeExact(m, vectors, out, count) }
    private val h_koral_bulk_multiply by lazy { handle("koral_bulk_multiply", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_multiply(a: MemorySegment, b: MemorySegment, out: MemorySegment, count: Long): Unit { h_koral_bulk_multiply.invokeExact(a, b, out, count) }
    private val h_koral_bulk_multiply_parent by lazy { handle("koral_bulk_multiply_parent", FunctionDescriptor.ofVoid(KoralMathLayouts.KoralMat4, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_multiply_parent(parent: MemorySegment, children: MemorySegment, out: MemorySegment, count: Long): Unit { h_koral_bulk_multiply_parent.invokeExact(parent, children, out, count) }
    private val h_koral_bulk_transform_aabbs by lazy { handle("koral_bulk_transform_aabbs", FunctionDescriptor.ofVoid(KoralMathLayouts.KoralMat4, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_transform_aabbs(m: MemorySegment, boxes: MemorySegment, out: MemorySegment, count: Long): Unit { h_koral_bulk_transform_aabbs.invokeExact(m, boxes, out, count) }
    private val h_koral_bulk_bounds by lazy { handle("koral_bulk_bounds", FunctionDescriptor.of(KoralMathLayouts.KoralAabb, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_bounds(allocator: SegmentAllocator, points: MemorySegment, count: Long): MemorySegment = h_koral_bulk_bounds.invokeExact(allocator, points, count) as MemorySegment
    private val h_koral_bulk_cull_spheres by lazy { handle("koral_bulk_cull_spheres", FunctionDescriptor.of(JAVA_LONG, KoralMathLayouts.KoralFrustum, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_cull_spheres(frustum: MemorySegment, spheres: MemorySegment, visible: MemorySegment, count: Long): Long = h_koral_bulk_cull_spheres.invokeExact(frustum, spheres, visible, count) as Long
    private val h_koral_bulk_cull_aabbs by lazy { handle("koral_bulk_cull_aabbs", FunctionDescriptor.of(JAVA_LONG, KoralMathLayouts.KoralFrustum, ADDRESS, ADDRESS, JAVA_LONG)) }
    fun koral_bulk_cull_aabbs(frustum: MemorySegment, boxes: MemorySegment, visible: MemorySegment, count: Long): Long = h_koral_bulk_cull_aabbs.invokeExact(frustum, boxes, visible, count) as Long
    private val h_koral_bulk_normalize by lazy { handle("koral_bulk_normalize", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG)) }
    fun koral_bulk_normalize(vectors: MemorySegment, count: Long): Unit { h_koral_bulk_normalize.invokeExact(vectors, count) }
}
